### PR TITLE
fix isinf return type to int: returns -1 for negative infinity

### PR DESCRIPTION
**Pull request by larsmans**
This changes behavior in, e.g., `print(isinf(x))`, but not the more common `cdef int infinite = isinf(x)`.

Patch to 0.22.x in the hopes of getting this into the next release.

### CODE REVIEW

**Comment by scoder** [comment]
Is there an actual reason for this change? The currect declaration should give the correct result when used from C, and "bint" has the advantage of coercing to a Python bool, i.e. you can say
```
def is_inf(x): return math.isinf(x)
```
and have it returns True/False. Your change kills that feature.

**Comment by larsmans** [comment]
The current declaration hides the fact that `isinf` is not supposed to be a boolean function. It returns `1` for infinity, `-1` for negative infinity.

**Comment by scoder** [comment]
Then wouldn't adding a comment be enough? I really find the coercion property helpful.

**Comment by larsmans** [comment]
But the coercion destroys one of `isinf`'s features. Python client code doesn't get to see the actual C semantics this way.

If you really don't like the change, would you still accept the test? I was worried about maybe getting conversions to {0,1} in C code.

**Comment by scoder** [comment]
Sure, the test is fine. It should also work without the change (bint == int in a C context).

And the reason why I'm still discussing this (rather than just closing the ticket) is because I admit that the decision about this is not entirely black or white. I consider it a nice feature that you get a True/False answer when passing the result through to Python. If you want a tristate result, you can get it by casting the result to <int>, but in that case, something nicer than the C-ish -1/0/1 might also be worth thinking about.

So, my gut feeling is that the use case of really wanting to pass -1/0/1 through to Python is somewhat less common than wanting True/False - but I also guess that neither is really common overall, which leaves me a bit indecisive. I think the main real obstacle is that it breaks backwards compatibility, and that usually requires some kind of convincing reason. I don't see that yet.

**Comment by argriffing** [comment]
Does the issue mentioned here affect compatibility?  I couldn't find it when I searched [CHANGES.rst](https://github.com/cython/cython/blob/master/CHANGES.rst) for information about backwards compatibility among Cython versions.

**Comment by robertwb** [comment]
I'd lean towards accepting this and respecting the -1/0/1 property of the C function, especially as ints can be used in a boolean context in Python.

**Comment by scoder** [comment]
Applied to master (pull request was for 0.22). Should we allow it into 0.23 ?
https://github.com/cython/cython/commit/34ff2d7b084c11032fabff234cb640f9345dfb65

**Comment by robertwb** [comment]
I'd avoid pulling this in 0.23, 'cause I think it'd require another round
of testing. But let's not wait as long for the next release :).

**Pull request closed without merging**
