### PR TITLE
Allow cast(...) to python types.

### PR DESCRIPTION
**Pull request by memeplex**
Currently `cython.cast('list', l)` will fail because of missing `typecheck` attr. Similarly, `cython.cast('MyType', o)` will fail because of missing `base_type` attr. The cause is that `ParseTreeTransforms` creates the `TypecastNode` directly from the type. Also, it forgets to set the `typecheck` attr (maybe I could add an optional kwattr to the cast function, say `cython.cast('list', l, typecheck=True)`).

### CODE REVIEW

**Comment by robertwb** [comment]
An optional typecheck=... attribute would be great.

**Comment by memeplex** [comment]
@robertwb I've added the `typecheck` attribute and some documentation. I would like to add unit tests also, but there is something about the Shadow `cast` implementation that smells bad to me:

```
def cast(type, *args, typecheck=None):
    if hasattr(type, '__call__'):
        return type(*args)
    else:
        return args[0]
```

1. If `type` is an extension class it will be callable but, in general, it won't have a "casting constructor", whatever that could mean in a python world.
2. If `type` is specified as a string it won't be called so, say, casting to `int` won't be the same than casting to `"int"`.
3. I'm not sure about the rationale for the unboxing in the else clause, but I beg for you to take a look at the discussion I started in the dev list last week about reference semantics in Shadow. Nobody answered yet but I still believe there are some problems in the current implementation.

All in all I think `Shadow.cast` should be an identity function, maybe treating typical narrowing casts as special cases.

**Comment by memeplex** [comment]
Please, tell me what do you think about my reimplementation of `Shadow.cast`. I addressed the issues I pointed out before and also a python2 compatibility issue that broke the CI build (btw,  `Shadow.cast` was taking `*args` but the parser only support one value to cast).

**Comment by memeplex** [comment]
@robertwb I decided to split the PR. Here I kept the least invasive change to `Shadow.cast` I came up with. I will create another PR to (try to) address the `Shadow.cast` shortcomings I pointed out above, because it's not trivial to get it right (nothing in `Shadow` really is).

**Comment by robertwb** [comment]
Thanks. I've merged it and added a small test.

**Pull request merged**
