### PR TITLE
refactor out use of numpy.distutils

### LINKED ISSUE #5607: `numpy.distutils` is deprecated.
### Describe your issue

When running test suite, I have discovered following warning:

```
[-1] compiling (c/cy2) and running numpy_cimport ...
=== C/C++ compiler error output: ===
/Users/ness-skmac3/dev/cython/runtests.py:250: DeprecationWarning:

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html


  from numpy.distutils.misc_util import get_info
====================================
```

Moreover, `numpy.distutils` is also used here:
https://github.com/cython/cython/blob/6ad6ca0e9e7d030354b7fe7d7b56c3f6e6a4bc23/Demos/setup.py#L15

I suppose it should be fix before python 3.12. Ref. https://github.com/numpy/numpy/issues/18588

### PR DESCRIPTION
**Pull request by mattip**
Fixes #5607 by refactoring places that import `numpy.distutils`, which is deprecated. `numpy.get_include` has existed forever (well, since 2006), there is no fear it is missing from an older NumPy.

### CODE REVIEW

**Comment by mattip** [comment]
While looking at the windows CI runs, I saw that the python3.6 one was finishing successfully in 2 minutes, which didn't make sense because all the other windows runs were failing. Looking more closely, it was [failing to build a wheel for pywinpty](https://github.com/cython/cython/actions/runs/5865066029/job/15901274772?pr=5620#step:6:262) (a dependency of jupyter), which declares support for python>=3.6 on [versions 2.0.1](https://pypi.org/project/pywinpty/2.0.1/#files) to version [2.0.3](https://pypi.org/project/pywinpty/2.0.3/#files) but does not supply a wheel, and fails to build from source. So I added a test-requirements-36.txt file and pinned the version there. I also relaxed the non-numpy restraint on python3.12 since NumPy released a 1.26.0rc1 wheel specifically for python3.12, let's see if tests pass.

**Comment by mattip** [comment]
CI is green, but 4 jobs failed with exit code 1, all python3.12-dev. I will try to make that fail and not pass, and then fix the dependency

**Comment by mattip** [comment]
Of course, CI was set to [allow failure for 3.12](https://github.com/cython/cython/blob/6f592646c069c4fd9fee76f96d4abbe060412e65/.github/workflows/ci.yml#L59), with a note
```
Temporary - Allow failure on Python 3.12-dev jobs until they are in beta (feature frozen)
```

3.12 is now in beta, so I will remove that condition

**Comment by mattip** [comment]
[`pstats_profile_test`](https://github.com/cython/cython/actions/runs/5867996550/job/15909904350#step:6:16470) and `pstats_profile_test_pyfunc` are failing on 3.12. [This is the source](https://github.com/cython/cython/blob/6f592646c069c4fd9fee76f96d4abbe060412e65/tests/run/pstats_profile_test_pycfunc.pyx#L1). Is there a way to run that test stand alone in python? Maybe the pstats format has changed for 3.12.

**Comment by mattip** [comment]
Maybe due to [inlining comprehensions](https://docs.python.org/3.12/whatsnew/3.12.html#pep-709-comprehension-inlining)

**Comment by da-woods** [comment]
> Is there a way to run that test stand alone in python?

Should just be `python3 runtests.py pstats_profile_test_pycfunc`. The other thing that might be useful is `--no-cleanup-sharedlibs` (which leaves the .so files in `TEST_TMP` so you can run them manually there. With that said, I don't think this needs to be in a numpy.distutils change...

> While looking at the windows CI runs [...]

Yeah, there were a few Windows runs that I couldn't easily make work when I was turning off "allow-failures" on the others.

**Comment by mattip** [comment]
> I don't think this needs to be in a numpy.distutils change...

OK. I will open an issue and backout the removal of `allowed_failure: true` for 3.12-dev

**Comment by mattip** [comment]
> Should just be `python3 runtests.py pstats_profile_test_pycfunc`

Right, I meant is there a way to run the test in pure-python mode without any cython compilation. I think there may be failures due to changes in traces that appear in the profile.

**Comment by da-woods** [comment]
> Right, I meant is there a way to run the test in pure-python mode without any cython compilation. I think there may be failures due to changes in traces that appear in the profile.

Not without editing it manually I think.

**Comment by scoder** [comment]
Thanks

**Pull request merged**
