### PR TITLE
Add C99 math.h functions to libc.math

### PR DESCRIPTION
**Pull request by p00ya**
Adds many long double variants (e.g. `expl`) that were previously omitted.
No functions have been (intentionally) removed.

Classes of functions/macros that are still missing:
 - error-handling ones, like `math_errhandling` and `MATH_ERRNO`
 - Bessel functions like `j0`, `y0`

Fixes cython/cython#3570

### CODE REVIEW

**Comment by scoder** [comment]
Thanks.

> No functions have been (intentionally) removed.

I want to believe you, but the reordering make it difficult to verify. I understand that it makes it easier to update, though. We can keep it like that, I'll just assume that you did a good job copying things around.

> omit the identifier for trivial parameters

However unlikely it may seem, that can break code that used keyword arguments with these functions. Could you put them back in, and also add similar argument names to the newly added functions?
That way, I could also more easily verify that there are only additions by diffing it with the original file after sorting that. Currently, I get a bit of an unclear diff due to the missing parameter names.

> use type* consistently instead of type *

IMHO, that improves the readability, yes.

Would be nice if you could also extend the (superficial) test in `tests/run/libc_math.pyx` a little, although only with portable usages (i.e. only safe C89 stuff). The intention is not to have anywhere near full coverage of the functions used (we're not testing libc here), but testing keyword arguments and some non-trivial signatures would be nice. In other words, test usages, not functionality.

**Comment by scoder** [comment]
Thanks, the diff now only shows `nearbyint()` and `ilogb()` as missing their argument names, and the rest are only additions.

**Comment by scoder** [comment]
Ah, perfect. Yes, that gives me a clear view on the changes now. I'll wait for CI and then merge it. Thanks!

**Comment by p00ya** [comment]
> Thanks.
> 
> > No functions have been (intentionally) removed.
> 
> I want to believe you, but the reordering make it difficult to verify. I understand that it makes it easier to update, though. We can keep it like that, I'll just assume that you did a good job copying things around.

To make it easier to verify this PR, I've split the commits.  You'll have to squint at the first commit (though you can verify that the number of lines excluding whitespace is the same).  Then you should be able to see no lines were removed in the 2nd commit.

> 
> > omit the identifier for trivial parameters
> 
> However unlikely it may seem, that can break code that used keyword arguments with these functions. Could you put them back in, and also add similar argument names to the newly added functions?
> That way, I could also more easily verify that there are only additions by diffing it with the original file after sorting that. Currently, I get a bit of an unclear diff due to the missing parameter names.

Oops, discovered this when the tests finally finished locally.  I think it's weird to rely on kwargs when they weren't there consistent to start with (many in `math.pxd` were missing, and the standards switch between`x` and `value` somewhat unpredictably).  What do you think of this: keep the names for the functions that already had them, but omit them for the new variants?  I've done that in the latest commit.  If you really do want to have names on everything though, I'll update.

> Would be nice if you could also extend the (superficial) test in `tests/run/libc_math.pyx` a little, although only with portable usages (i.e. only safe C89 stuff). The intention is not to have anywhere near full coverage of the functions used (we're not testing libc here), but testing keyword arguments and some non-trivial signatures would be nice. In other words, test usages, not functionality.

So none of the xxxf or xxxl variants are portable to C89 as far as I know.  I've added some to the test just as imports - is that still a problem for emitted code if they're never used?  I also added a kwarg test for an existing extern.

**Pull request merged**
