### PR TITLE
Fix unchecked return value in utility code

### PR DESCRIPTION
**Pull request by dalcinl**
Found by Coverity Scan on mpi4py sources

### CODE REVIEW

**Comment by scoder** [comment]
Thanks for bringing this up, but this is not an issue. Right below, the error state is reset either way. There is no need to also reset it conditionally. I'll add a `(void)` instead to explicitly ignore the return value.

**Comment by scoder** [comment]
BTW, could you please push PR branches to your own repo fork instead of the main Cython repo? Otherwise, people who clone the main repo will replicate them all over the place.

**Comment by scoder** [comment]
Closed in https://github.com/cython/cython/commit/8235d1c98aede02dcf97b36f4d7ccb5703c39ce1

**Comment by dalcinl** [comment]
> BTW, could you please push PR branches to your own repo fork instead of the main Cython repo?

Of course I can.

>  Otherwise, people who clone the main repo will replicate them all over the place.

I was not aware of this being a concern, otherwise I would have done things differently. Branches can be automatically deleted on merges, and pruned on pulls, and a centralized repo to push in-work branches facilitates exchanges. But OK, I'm not going to fight this policy. However, there are lot other ones that people will get if they clone. May I ask for all these branches to be removed?

```
    ci_compile_all                tracked
    enable_limited_api_file_tests tracked
    fixed_code_objects            tracked
    full_code_writer              tracked
    gh1807_getitem_mapping_first  tracked
    gh2343_heap_types             tracked
    gh2565_language_level_3str    tracked
    gh2670_win_intop              tracked
    gh2983_lambda_sig             tracked
    gsoc-kurt-regraft             tracked
    ipython711                    tracked
    msvc_cpp                      tracked
    pep484_typing                 tracked
    release                       tracked
    robertwb-rect                 tracked
```

**Comment by scoder** [comment]
Yes, I noticed those branches, too. They should probably be looked through and, if outdated (and most of them should be that), removed.

Regarding branch handling (and this is the wrong place to discuss this), I don't see an *advantage* in having pending PRs in the main repo. PRs are best found through the Github web interface, not by looking through the current branches. And while they "can be pruned" and all that, sure, everyone can do everything. But if those branches are not there in the first place, then no-one has to. I consider that an advantage. Almost no-one who clones a repo cares about other branches than the main development branch (of that repo). Sometimes a legacy release branch, but that's already far down. Let alone anything else.

**Pull request closed without merging**
