### PR TITLE
Fix missing new lines in generated html file

### LINKED ISSUE #4945: [BUG] HTML generated by cython -3a renders all C code in single line
**Describe the bug**
`cython -3a` command generates C code in html file which is rendered to single line:

**To Reproduce**
Code to reproduce the behaviour:
```cython
cdef int a = 3
cdef int b = 5

print(a * b)
```
image

**Expected behavior**
C code rendered in browser should be splited into several lines

**Environment (please complete the following information):**
 - OS: Any
 - Python version 3.9
 - Cython version master

**Additional context**
Issue was introduced by following commit:
```
commit 0b4370678e5b00a020cd990f922964d3aba59884
Author: Stefan Behnel <stefan_ml@behnel.de>
Date:   Sat Jul 16 22:14:48 2022 +0200

    Reduce overhead in the code writer when writing out simple code without newlines.

 Cython/Compiler/Code.pxd |  1 +
 Cython/Compiler/Code.py  | 19 ++++++++++++-------
```

### PR DESCRIPTION
**Pull request by matusvalo**
Fixes #4945

### CODE REVIEW

**Comment by matusvalo** [comment]
Not sure even if following `write_lines()` should not be converted to `write()`:

https://github.com/cython/cython/blob/287a11e55259ffe01cf43a450159be7f946f1cfb/Cython/Compiler/Code.py#L1994-L2005

The bug is fixed by PR but I am thinking if it is not right to convert **all** `write_lines()` to `write()`

**Comment by matusvalo** [comment]
It would be great to have unittest for this PR (there are some tests in `run/annotate_html.pyx`), but it can be tricky to do it right...

**Comment by da-woods** [comment]
I'm not quite sure I understand why this works. `write` contains

```
if '\n' in s:
    self.write_lines(s)
```

So in both the cases you've changed it should be calling `write_lines` anyway? So if I understand it right this PR shouldn't do anything?

**Comment by matusvalo** [comment]
Well at first I was also puzzled but it is due following code:
https://github.com/cython/cython/blob/287a11e55259ffe01cf43a450159be7f946f1cfb/Cython/Compiler/Annotate.py#L24-L54

`AnnotationCCodeWriter` class is inheriting from CCodeWriter and overrides `write()` method. Hence if the code uses `write_line()` instead of write it breaks the logic because `AnnotationCCodeWriter.write()` is not called anymore.

> PR shouldn't do anything?

I checked on my computer and it fixes the issue.

**Comment by da-woods** [comment]
Thanks for clarifying. I hadn't realised that there was inheritance involved. Makes sense now!

To me it sounds like the right fix is would be to provide an implementation for `AnnotationCCodeWriter.write_lines`. The simplest version might just be calling `self.write` (really just undoing the optimization in https://github.com/cython/cython/commit/0b4370678e5b00a020cd990f922964d3aba59884 for the annotation code writer).

Possibly there's other fixes which use the inheritance more nicely? Either way I think the fix should change the code writer.

**Comment by da-woods** [comment]
I will ping @scoder though because it's based on his change...

**Comment by matusvalo** [comment]
If you find better fix feel free go with it. I am fine with close my PR in favour of better fix.

**Comment by scoder** [comment]
>If you find better fix feel free go with it

I'm working on it, also trying to allow assertions on the generated HTML file.

**Comment by matusvalo** [comment]
Closing in favor 8afd932c28d08428d45bba03d6b642093e4c973b

**Pull request closed without merging**
