### PR TITLE
Mark Py_EnterRecursiveCall as unlikely

### PR DESCRIPTION
**Pull request by alexhenrie**
This allows the compiler to reorganize the code to minimize jumps.

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Did you see an actual difference for any compiler that you tried? Did you look at the generated assembly, for example?

**Comment by alexhenrie** [comment]
I haven't looked at the assembly output for Py_EnterRecursiveCall specifically, but I did see assembly differences when I removed __builtin_expect from the following very similar test program:

```
#include <stdio.h>

int main(int argc, char *argv)
{
    if (__builtin_expect(argc < 2, 0)) return -1;
    printf("%s\n", argv[1]);
    return 0;
}
```

**Comment by scoder** [comment]
That's ok. I just wanted to know if you saw an actual improvement in any way, because C compilers should be able to guess correctly here even without the `unlikely()`. The program you showed might look similar, but is actually very different when it comes to C compiler heuristics.

It's not wrong to add the `unikely()`, just in case.

**Comment by alexhenrie** [comment]
Thanks!

**Pull request merged**
