### PR TITLE
cythonize --no-docstrings

### PR DESCRIPTION
**Pull request by mo-han**
Add `-D, --no-docstrings` option for the cythonize script.

### CODE REVIEW

**Comment by scoder** [comment]
Hmm, while this seems a simple and obvious feature, I just added support for doing that at the C level. When you compile your CPython without docstrings, Cython extensions won't have them either.

I admit that compiling your own CPython is less likely than compiling your Cython extension, though… :)

May I ask what your incentive is for removing docstrings? Is it a size issue?

**Comment by mo-han** [comment]
Not a size issue definitely. Just need to prevent some of our customers from getting documents (Maybe they didn't pay enough to our boss I guess ;P). I tried to strip all docstrings with this script, and found that I need to do some tweak to it to achieve this goal. So I did the modification to my local copy of cython, and then create a pull-request. Maybe some other guys need it too, though the reasons would vary.

**Comment by scoder** [comment]
Ok, I'm fine with adding an option for this, just not a short one. Given that most users will not care at all, providing only the long option avoids accidental misuse and keeps -D free for more important use cases. Could you remove the -D, please?

**Comment by mo-han** [comment]
So it's not in release stream yet? Do I need to modify the local installed copy to use this feature?

**Comment by scoder** [comment]
This was released in Cython 3.0a1.

**Pull request merged**
