### PR TITLE
Fixed over-zealous optimization of __Pyx_PyObject_Append

### PR DESCRIPTION
**Pull request by da-woods**
fixes https://github.com/cython/cython/issues/4828

### CODE REVIEW

**Comment by da-woods** [comment]
The tests look to be in https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/tests/run/append.pyx. Possibly the tests for this PR should be moved to there?

**Comment by da-woods** [comment]
(And a few list tests in https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/tests/run/list.pyx)

**Comment by scoder** [comment]
>https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/tests/run/append.pyx.
>Possibly the tests for this PR should be moved to there?

That would be better, yes.

**Comment by scoder** [comment]
Backported in https://github.com/cython/cython/commit/2f1c338ac4e7333823be84cc0d8df80acc5e23f3

**Pull request merged**
