### PR TITLE
[Docs] Create links to Python/C API

### PR DESCRIPTION
**Pull request by matusvalo**
This PR introduces links to Python/C API documentation.

### CODE REVIEW

**Comment by da-woods** [comment]
Just for my understanding, it's creating the links with this configuration option?

https://github.com/cython/cython/blob/a44bbd363029aa9ba16fefcb485c68162f8ab663/docs/conf.py#L125

**Comment by matusvalo** [comment]
> Just for my understanding, it's creating the links with this configuration option?

I am not sphinx expert but yes. This is triggering creation of links to python (C links and python links)

**Comment by matusvalo** [comment]
BTW the PR is not migrating all mentions of Python/C API. There are some tables (e.g. [1]) which needs to be migrated, but maybe more refactoring should go there so I left it to next PR...

[1] https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#sequences-and-mappings

**Comment by matusvalo** [comment]
Uff this PR is old. Maybe we need to refresh it with master first...

**Comment by da-woods** [comment]
I believe the CI runs on "PR merged into master" so there isn't a huge need to manually merge if there aren't conflicts.

**Comment by da-woods** [comment]
If it's (still?) generating the links correctly then I think it's a good idea and we should just merge it even if it isn't absolutely 100% comprehensive

**Comment by da-woods** [comment]
Docs look good to me so I'm merging this...

**Pull request merged**
