### PR TITLE
codespell: add config, workflow (so no new typos sneak in) and get some typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
Config does exclude quite a bit of ideosyncratic constructs and even a typo (`delimeters`) which is now part of the API, so I decided to leave it alone for this round.

### CODE REVIEW

**Comment by da-woods** [comment]
I think this is probably worth doing. Will give it a few days to see if there's any objections, but if not I'll merge it.

**Comment by da-woods** [comment]
I also don't think "delimeters" is really in an API that anyone uses. I know Numpy/Scipy/Pandas/Scikit (and probably others) learn do use tempita in places, but not via those interfaces. So I think I'd be comfortable with that change too.

**Comment by yarikoptic** [comment]
> I also don't think "delimeters" is really in an API that anyone uses. I know Numpy/Scipy/Pandas/Scikit (and probably others) learn do use tempita in places, but not via those interfaces. So I think I'd be comfortable with that change too.

ok, should I provide compatibility/deprecation layer to possibly ease transition for a possible happen to be user?

**Comment by da-woods** [comment]
Thanks. Think this should be useful.

Still not quite sure about the delimiter/delimeter issue

> ok, should I provide compatibility/deprecation layer to possibly ease transition for a possible happen to be user?

I think if we do change it we should just change it and not do a compatibility layer.

> edit: probably would do it as a separate PR for ease of review/etc

Yeah that's what I decided - separate out the trickier bit

**Pull request merged**
