### PR TITLE
TEST: add test for 'binary incompatibility' warning

### LINKED ISSUE #2221: add compile option to hide binary size warnings
Hi, I propose to add an option (by default not enabled) to hide the binary size warnings that are in general useful but can easily give false alarms. Examples:

- https://github.com/numpy/numpy/pull/432
- https://github.com/numpy/numpy/pull/5343
- https://morepypy.blogspot.ca/2018/04/how-to-ignore-annoying-cython-warnings.html

The second link is an example of NumPy devs considering not merging a clear improvement because of this warning, and the third one of PyPy devs publishing a complete package just to install a warning filter to work around the false alarm. 

When package authors know that it's going to be a user-visible false alarm (and it's quite an alarming/confusing one for users), then giving them an option to do a release with the check disabled seems quite valuable.

### PR DESCRIPTION
**Pull request by mattip**
Beginning of a PR to work on #2221.

The first step is to add tests for the "binary incompatibilty" check. ~How do I get the test to pass? I need to build a module around the header file added in commit 2eb0fe2 before starting the test, so I can play with the `tp_basicsize` field. Any hints? If I add a C file with the module init code, how will it get compiled for the test?~

Edit: using `check_size.srctree` to build the module and tests

Edit2: make sure this does not close #2221

### CODE REVIEW

**Comment by robertwb** [comment]
Thanks for looking into this.

Perhaps the best way to write a test would be to have two separate modules,
one defining the classes, and one in Cython that declares them as extern
classes naming the former module as where they come from. You could do this
with a .srctree test.

You could also do this with two Cython modules, and then have a .h file
which does nothing but declare structs of the right (or wrong) size to use
in their "extern" declarations. (They don't even have to be used in the
defining module at all.)

**Comment by mattip** [comment]
Thanks for the hints. I added a short sentence about `.srctree` to the [hacking wiki](https://github.com/cython/cython/wiki/HackerGuide), please review/revert. It would be nice if somehow that wiki would make it directly into the [documentation](http://docs.cython.org/en/latest/).

**Comment by mattip** [comment]
Now I have a passing test that replaces the `FooStruct` with a `FooStructNominal`, which renames the fields but does not change the size

**Comment by scoder** [comment]
Sounds good to me. I'll wait for travis to give its placet, then I'll merge it in. Thanks!

**Pull request merged**
