### PR TITLE
ci-run.sh: run msvc build with multiple processes

### PR DESCRIPTION
**Pull request by 0dminnimda**
Partial fix for #4963

### CODE REVIEW

**Comment by 0dminnimda** [comment]
Not sure if there is any speedup.
Maybe a tiny one

**Comment by 0dminnimda** [comment]
I looked through all of the cl command line options and it seems that's the most speedup we're gonna get out of them.

**Comment by 0dminnimda** [comment]
Well, we can ty to fixate number of processes, but it seems better to leave this choice to the cl

**Comment by scoder** [comment]
Thanks

**Pull request merged**
