### PR TITLE
Drop Numpy includes

### PR DESCRIPTION
**Pull request by da-woods**
In https://github.com/cython/cython/issues/5820#issuecomment-1812491784 @mattip suggests that Cython providing slightly different Numpy includes is a source of confusing error messages.

They've been in Numpy for a reasonable length of time now, so it's probably time to drop Cython's copy. It'll hopefully avoid people raising issues about Cython's copy too.

### CODE REVIEW

**Comment by da-woods** [comment]
The one issue seems to be that Numpy don't seem to have adopted the math.pxd file in the Numpy directory. I can find quite a few people using it, including Numpy themselves (https://github.com/numpy/numpy/blob/605e34577affa99fd49bbb6156843953b81d92b8/numpy/random/_common.pyx#L8) so unless I'm missing something, we may not be in a position to remove it

**Comment by mattip** [comment]
aargh. Sorry, we seem to have missed that: see https://github.com/numpy/numpy/issues/25177. I guess Cython could drop the `__init__.pxd` file for now.

**Comment by mattip** [comment]
CI is passing other than the PyPy trashcan test, skipped in #5832.

**Comment by mattip** [comment]
About `numpy.math.pxd`:

@rgommers [commented on elsewhere](https://github.com/numpy/numpy/pull/25594#issuecomment-1894643868) that perhaps the bettter solution is for cython to drop the file:

> ... [W]hat bothers me the most here is that the selection of functions included makes little sense. How would a user know what's in this namespace without trial and error?

> It may be better for Cython to simply deprecate the numpy.math namespace and tell users to prefer libc.math and that if they have a specific issue to work around libc issues, simply do this in their own code:
  ```
  cdef extern from "numpy/npy_math.h" nogil:
    # replace copysign with the function of interest here
    double copysign "npy_copysign"(double, double)
  ```

**Comment by mattip** [comment]
Is there any indication that `numpy/math.pxd` is in use?

**Comment by da-woods** [comment]
> Is there any indication that `numpy/math.pxd` is in use?

Looks like Scipy and Pandas both use it (just for NaN/INFINITY constants). scikit-learn looks to have used it until 2023 but it's probably been removed. A bunch of smaller projects also look to use it. I suspect not for anything irreplaceable, but I'm reluctant to cause that much disruption deliberately.

**Comment by rgommers** [comment]
The SciPy usage was one very recently introduced line that I missed - I just opened a PR to remove it again. Pandas `main` branch looks clean too, no usages.

I think it would be good to at least approve the deprecation, conditional on code findable with GitHub code search being cleaned up first. Now that Cython 3 is kind of a "fresh" start with many much more disruptive changes than this one, it'd be nice to get rid of this.

**Comment by mattip** [comment]
I think this PR could be merged as-is. The use of `math.pxd` is a separate problem, and a little harder to solve, so separating the concerns and merging this would at least solve the immediate problem of duplicate files in two different repos.

**Comment by da-woods** [comment]
Yeah I think I agree with this conclusion. I'll merge this for 3.1.

I mostly agree that we should drop numpy.math too. I'll make another PR for that but won't merge it unilaterally.

**Pull request merged**
