### PR TITLE
Fix warnings for docs during build procedure

### PR DESCRIPTION
**Pull request by stefanos82**
I read https://www.sphinx-doc.org/en/master/usage/domains/c.html and said to myself `don't tell me it's the whitespace mandatory...!`; seems like it is!

### CODE REVIEW

**Comment by stefanos82** [comment]
@da-woods based on our conversation in #6071 and the original report at #4217 I have fixed the warnings.

Can you double-check that everything is OK so it can get merged?

**Comment by da-woods** [comment]
Thanks - I'll just have a quick look at the generated docs from the CI before merging it to double check.

Does this fix your problems with the code examples or just the warnings? (I'm just curious - I'm happy to merge something for the warnings)

**Comment by stefanos82** [comment]
> Thanks - I'll just have a quick look at the generated docs from the CI before merging it to double check.
> 
> Does this fix your problems with the code examples or just the warnings? (I'm just curious - I'm happy to merge something for the warnings)

It fixes the `make html` build, but not the `make singlehtml`; the problem remains with the aforementioned build option.

Also, I have discovered a number of problems with other build options, such as `make latexpdf`; it produces the full `tutorial.pdf` correctly, but the `reference.pdf` generates only 11 pages for some reason.

Another problem is with `make texinfo`; it produces the necessary files in `build` directory, but when you decide to generate a PDF out of `texinfo` files, the generated PDF is messed up and the images do not respect the margin sizes, they go full sized and go out of margin limitations; also, the links go out of margin dimensions too.

**Comment by da-woods** [comment]
This isn't looking right I'm afraid

image

image

image

image

**Comment by stefanos82** [comment]
OK, let me double-check everything because this indeed looks weird!

**Comment by stefanos82** [comment]
image

In other words, without my changes, it should have worked as expected!

I have no idea why it does not work.

I'm closing this PR as it's completely unnecessary and actually break things.

**Comment by da-woods** [comment]
I cherry-picked the really easy stuff out of this in 7484c0102 (just the orphan files and the length of the underline).

We may as well have those changes. Thanks.

**Comment by stefanos82** [comment]
By the way, https://readthedocs.org/ directs to https://about.readthedocs.com/?ref=readthedocs.org and has a pricing too!

image

Am I missing something here?

**Comment by da-woods** [comment]
I think that's for commercial use - it's free (with ads) or low-cost (without ads) for open source. I don't control Cython's readthedocs account so I don't really know though

**Pull request closed without merging**
