### PR TITLE
Print run time stats in the test runner

### PR DESCRIPTION
**Pull request by scoder**

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Pytest is able to do this, as well as other things that are coded by hand in `runtests.py` (like multiprocessing). Problem is, pytest doesn't support python 2.6. Will there be a drop of Python 2.6 support like Cython dropped python 3.3 in the near future? If yes, I would be willing to do PRs for a progressive migration from Unittests to pytests.

**Comment by scoder** [comment]
I'm well aware that pytest can do the parallelisation and (some of) the reporting. What it can't do is discover and run the tests. :)

The problem is that the tests have three steps: Cython translation, C/C++ compilation and importing/testing (mostly doctests). The test modules and their doctests only become available after compilation, but pytest assumes that it can discover and select all tests before starting them.

I guess we could write our own test discovery, always assume that each test has all three steps, and then mark the non-existant steps as skipped, but I'm not sure that would be better and/or less work than what we have.

**Comment by scoder** [comment]
Since Py2.6 doesn't really pose many problems currently (not more than Py2 in general), and since it still works to test it on travis, I wouldn't remove it right now (knowing that it already had its EoL last year). But as soon as it gets in the way, I'll happily remove it. Could happen right after the next release.

**Comment by gabrieldemarmiesse** [comment]
I see. Thanks for the explanation!

**Pull request merged**
