### PR TITLE
Improve the readability of code in pipeline.py

### PR DESCRIPTION
**Pull request by 0dminnimda**

### CODE REVIEW

**Comment by scoder** [comment]
I'm not sure that I understand what you are intending. To me, this looks like a somewhat arbitrary bunch of changes that spell certain code constructs differently. Removing the whitespace in keyword arguments in something I regularly do  when I touch the respective code (mostly because PEP-8 says so). For the rest, I'm not sure whether they are improvements or just "different".

As I wrote in #4288:
"IF we really start reformatting code, then we should switch to Black and do it once and for all, for the whole code base, so that ignoring a single reformatting commit can be ignored by git blame."

However, I'm not sure if I really want to go there. At least not right now. There are way more important things to do. As long as we maintain a legacy branch (0.29.x) that is already hugely diverging, cuttering the master branch with tons of little changes will basically make any attempt to cherry-pick fixes a costly endeavour.

**Comment by 0dminnimda** [comment]
this PR is result of [this comment](https://github.com/cython/cython/pull/4241#discussion_r663465855)

**Comment by 0dminnimda** [comment]
Well, right now I'm filling like even in separate PR it's not possible to change those lines. (..but of course it's silly to change _only_ those lines in whole PR and not look for other changes in file, so i did just that)

**Comment by scoder** [comment]
I'll close this. It's not the time for arbitrary formatting changes.

**Pull request closed without merging**
