### PR TITLE
convert PyTypeObject struct initialization to C99 designated initializers

### PR DESCRIPTION
**Pull request by mattip**
This requires C99 compliant compilers, but reduces code size and may help future-proof the code.

### CODE REVIEW

**Comment by scoder** [comment]
> This requires C99 compliant compilers

Given that Cython 3.1 is the release where we cut off old tails, I suggest that we also wait with this until then. I think requiring C99 for Cython 3.1 is just fine.

**Comment by mattip** [comment]
Ahh, right. `CYTHON_USE_TYPE_SPECS` is "on" only for the limited API. FWIW, HPY is [exploring converting NumPy to use heap types instead of static types](https://github.com/hpyproject/hpy/wiki/dev-call-20230504) and will be measuring the performance impact.

**Comment by mattip** [comment]
Waiting for 3.1 would further simplify this since dropping older versions of Python mean the legacy `tp_del`, `tp_print` fields would go away.

**Comment by da-woods** [comment]
Designated initializers require c++20 (and even then you need to be careful because they're more restricted than the C version). So I'm not sure we can do this any time soon

**Comment by mattip** [comment]
> Designated initializers require c++20

Is there a set of compilers declared as "supported by cython"? FWIW, I see them in CPython v3.6.0 (released in 2016) but I could not find use of them in 2.7.18 (released 2020).

**Comment by scoder** [comment]
>> Designated initializers require c++20
>
> I see them in CPython v3.6.0 (released in 2016) but I could not find use
> of them in 2.7.18 (released 2020).

CPython requires C99 now but does not need to be compiled itself in C++. It does not use or require recent C/C++ features in its header files.

The code that Cython generates needs to be compilable in both C and C++, and currently targets C89 and some C++ version that "works everywhere".

**Comment by da-woods** [comment]
> currently targets C89 and some C++ version that "works everywhere".

Pretty close to C++98 minimum, with some conditionally compiled bits to use newer features if they're available (mainly `std::move`).

Realistically we could shift that upwards to C++11 (probably after 3.0), but I think C++20 seems too far.

**Comment by scoder** [comment]
Would be nice to have this updated. I'd like to have this integrated into Cython 3.1.

**Comment by mattip** [comment]
Rebased off HEAD, pending CI checks

**Comment by mattip** [comment]
As @da-wood stated above, this requires c++20
```
error C7555: use of designated initializers requires at least '/std:c++20'
```

**Comment by scoder** [comment]
Thanks for the update. Sadly, we cannot require C++20 any time soon, so we'll have to postpone this, which probably means that it will bit rot away under our feet. Sorry, @mattip.

**Comment by mattip** [comment]
Understood. I will close this for now, we can revisit it in a few years.

**Pull request closed without merging**
