### PR TITLE
Experimental support for jedi 0.9.0

### PR DESCRIPTION
**Pull request by tjwei**
Allow jedi-typer to support both jedi 0.8.x and jedi 0.9.0.
It compiled and passed all 4 tests. However, in order to further improve the jedi-typer, some more tests are needed. But add more features and tests might break the original jedi-typer and it is difficult to maintain the code that supports both 0.8.x and 0.9.0 API. 
So this patch only aims for getting jedi-typer works with current jedi 0.9.0 while having similar functionality of current jedi-typer.

### CODE REVIEW

**Comment by scoder** [comment]
Thanks! Since this is an experimental tool anyway, and Jedi 0.9 is intended to improve the integration with external tools, I'd be ok with switching to Jedi 0.9 completely and dropping the 0.8 code.

Any further improvements are welcome.

**Comment by tjwei** [comment]
Thanks. I will add a few more test cases.

**Comment by scoder** [comment]
Any news here? Would be nice to have this in for 0.23.

**Comment by tjwei** [comment]
Not much, but will have time to work on this project next week.

**Comment by tjwei** [comment]
Status update
Clean up the code of jedi-typer for jedi 0.9 and added tests for list, dict, set typing.
It also works for nested function and classes, methods, generators. Will add these tests soon.

There are still something that does not work:
1.  conflicting types. Hopefully will be supported soon.
2. jedi 0.9 does not work for set comprehension. Need to fix this in jedi.

**Comment by scoder** [comment]
Cool! Looks like this is getting somewhere. We might even want to rename it to a proper module name ("jedityper.py") so that it can be imported rather than just executed.

**Comment by scoder** [comment]
Thanks!

**Pull request merged**
