### PR TITLE
Backport to 0.29.x: Add PEP420 namespace support

### PR DESCRIPTION
**Pull request by mkoeppe**
Backport of #2946 and #3905 to 0.29.x

Ref: https://github.com/cython/cython/issues/2918

### CODE REVIEW

**Comment by scoder** [comment]
Thanks, but I think this bears potential for breaking some people's build. I'd like to avoid behavioural changes in 0.29.x as much as possible. It's really a legacy stable release branch.

**Comment by mkoeppe** [comment]
> I think this bears potential for breaking some people's build

Well, I just looked again at #2946 to see if there are any mentions of problems in downstream projects. I only found #3905, which I've now cherry-picked onto the branch.

**Comment by scoder** [comment]
Sorry. No new features in 0.29.x.

**Comment by mkoeppe** [comment]
Each of 0.29.27, 0.29.29, 0.29.31 introduced new features according to https://cython.readthedocs.io/en/latest/src/changes.html

**Comment by scoder** [comment]
> Each of 0.29.27, 0.29.29, 0.29.31 introduced new features

The changes in 27 and 32 have zero impact on existing code and both help integrating with external build systems. The change in 29 fixes warnings and was long tested in the master branch.

Your proposed change fixes no existing bugs, has no advantages for existing code, but risks breaking it, and has long been available as a feature in several 3.0 releases. I consider this enough reasons to reject it.

**Pull request closed without merging**
