### PR TITLE
Fix const-qualified customly fused-typed memoryview parameters for def function

### LINKED ISSUE #5230: [BUG] Compilation crashes when using `const`-qualified customly fused-typed memoryview parameters for `def` function
### Describe the bug

As of Cython 0.29.33, compilation crashes:
 - when defining a `def` function with a memoryview as a parameter
 - when a custom fused type is defined using NumPy types 
 - when using `const`-qualification on a memoryview typed with this custom fused type

### Code to reproduce the behaviour:

This crashes:
```cython
cimport numpy as cnp

ctypedef fused fused_t:
    cnp.float32_t
    cnp.float64_t
    cnp.int32_t
    cnp.int64_t

def _func(
    const fused_t[:] data,
):    
    return
```

with this trace:

```
Error compiling Cython file:
------------------------------------------------------------
...
    cdef __Pyx_memviewslice memslice
    cdef Py_ssize_t itemsize
    cdef bint dtype_signed
    cdef char kind
    itemsize = -1
    cdef bint ___pyx_const int32_t_is_signed
                          ^
------------------------------------------------------------

(tree fragment):16:27: Syntax error in C variable declaration
```

<details>
<summary>Alternatives that compiles</summary>

The following snippets compiles:

```cython
ctypedef fused fused_t:
    float
    double
    int
    long

def _func(
    const fused_t[:] data,
):    
    return
```

```cython
from cython cimport numeric

def _func(
    const numeric[:] data,
):    
    return
```

```cython
cimport numpy as cnp

ctypedef fused fused_t:
    cnp.float32_t
    cnp.float64_t
    cnp.int32_t
    cnp.int64_t

cdef void _func(
    const fused_t[:] data,
):    
    return
```

</details>

### Expected behaviour

This must compile and work.

### Environment

OS: Linux
Python version 3.11.0
Cython version 0.29.33

### Additional context

First observed in https://github.com/scikit-learn/scikit-learn/pull/25041/files#r1087947278 as of https://github.com/scikit-learn/scikit-learn/pull/25041/commits/563fd00a8a729519b3d9be9a433b8df60a0f5ef0.

### PR DESCRIPTION
**Pull request by matusvalo**
Fixes #5230

### CODE REVIEW

**Comment by matusvalo** [comment]
Uhm, just right now I found out that there is already fix pending - #5233. I suppose that #5233 supersedes this PR. @da-woods can I close this PR? Is it going to be fixed in #5233?

**Comment by scoder** [comment]
I think you'll need a bit of escaping here. Otherwise, "long int" and a typedef "long_int" might give a collision.

We already do this in a few other places.

**Comment by matusvalo** [comment]
> I think you'll need a bit of escaping here. Otherwise, "long int" and a typedef "long_int" might give a collision. We already do this in a few other places.

This is already done in #5233 as mentioned above. I am going to close this PR in favor of it.

**Comment by da-woods** [comment]
> Uhm, just right now I found out that there is already fix pending - #5233. I suppose that #5233 supersedes this PR. @da-woods can I close this PR? Is it going to be fixed in #5233?

It looks like substantially the same fix. I think I just tried to handle name collisions a bit (which is almost certainly worthwhile).

> Edit https://github.com/cython/cython/pull/5233 is is backport to 0.29.X branch. Is there another release of 0.29.X Cython? Does it make sense to merge https://github.com/cython/cython/pull/5233 to master instead of 0.29.X branch?

I'm not sure if there will be another 0.29.x release, but I don't think that PR should be targetted to it any more

**Comment by matusvalo** [comment]
> I'm not sure if there will be another 0.29.x release, but I don't think that PR should be targetted to it any more

Hm can we move the PR towards master?

**Comment by da-woods** [comment]
Yes it looks like I can retarget it to master without changing anything else

**Pull request closed without merging**
