### PR TITLE
Use relative path for depfile

### LINKED ISSUE #6291: [BUG]  Cython depfile should use relative paths
### Describe the bug

A little while ago I created an issue in the Meson repo https://github.com/mesonbuild/meson/issues/13212 since when you update some `pxd` in scikit-learn, you would need to build twice to fully build the project. We have a work-around in scikit-learn but it would be great if the underlying issue was fixed because it is quite a confusing behaviour.

Investigation by @rgommers and @eli-schwartz seemed to indicate that potentially using relative files in depfiles would fix the issue see https://github.com/mesonbuild/meson/issues/13212#issuecomment-2137556487

cc @ev-br since I think he is the one who added depfile support in Cython in https://github.com/cython/cython/pull/4563 IIUC and you may have some insights into this. Thanks a lot for this by the way! The more I worked on using Meson in scikit-learn the more I realized all the issues that had been fixed along the way to make it a workable solution for the Scientific Python ecosystem.

### Code to reproduce the behaviour:

repo to reproduce the behaviour: https://github.com/lesteve/meson-partial-build

A quick summary of the behaviour:
```bash
touch package/utils/utils.pxd
# This does not rebuild package/lib/lib shared library
ninja -C build -d explain -v
# The second time this builds package/lib/lib shared library
ninja -C build -d explain -v
```

A more detailed explanation is available in https://github.com/mesonbuild/meson/issues/13212

### Expected behaviour

Calling `ninja` once fully builds the project, calling `ninja` a second time says "No work to do".

### OS

Linux

### Python version

3.12

### Cython version

3.0.10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lesteve**
Close #6291.

This has been tested to work as expected on numpy, scipy and scikit-learn.

Suggestions more than welcome on how to add a test for this!

### CODE REVIEW

**Comment by lesteve** [comment]
cc @da-woods maybe to approve the workflow to run and see whether that breaks any tests?

**Comment by lesteve** [comment]
@da-woods could you trigger the workflow again, I think they are now passing locally on my machine.

**Comment by lesteve** [comment]
cc @ev-br as the original author of https://github.com/cython/cython/pull/4563, in case you want to have a look at the diff.

**Comment by ev-br** [comment]
I don't have anything of value to add, other than saying thank you for implementing this.

**Comment by da-woods** [comment]
Thanks.

**Pull request merged**
