### PR TITLE
enabled the cache-like feature to cyton.py

### PR DESCRIPTION
**Pull request by Blanco10022**
i enabed and documented the cache like feature in the setup.py  since the option.py seem to already have set it to true

### CODE REVIEW

**Comment by scoder** [comment]
This is a weird place to make such a change. What exactly is the intention? What do you want to see covered by this option?

**Comment by Blanco10022** [comment]
The intention behind enabling the cache option is to improve the efficiency of the build process when working with Cython modules. By enabling caching, Cython will reuse previously generated C files if the source files haven't changed since the last compilation. This can significantly reduce build times, especially in large projects or when iterating frequently on code changes.
Enabling the cache option doesn't change the behavior of the generated code or introduce any new features; it simply optimizes the build process by avoiding unnecessary recompilation of unchanged source files. This can be particularly beneficial in continuous integration workflows or when collaborating on projects with multiple developers, where build times can impact productivity.

Futhermore , I added the cache option in the cythonize() function call in the setup.py file. This function handles compiling Cython source files into C extensions during the build process. I chose this spot because it's where we configure Cython compilation settings, making it the logical place to enable caching for better build performance.

Let me know if you need more info or have other suggestions!

**Comment by scoder** [comment]
> I added the cache option in the cythonize() function call in the setup.py file. This function handles compiling Cython source files into C extensions during the build process.

Yes, but only for building Cython itself. It makes no difference for building user code.

**Comment by Blanco10022** [comment]
ok i  understand , i will look over it again and apply modifications

**Comment by Blanco10022** [comment]
i jusst remodified

**Pull request closed without merging**
