### PR TITLE
[Docs] Document show_performance_hints

### PR DESCRIPTION
**Pull request by matusvalo**
Related to #5757

### CODE REVIEW

**Comment by matusvalo** [comment]
I was thinking whether it make sense also to mention how to disable performance hint directly in message. E.g.:

```
performance hint: deleteme.pyx:1:5: Exception check on 'bar' will always require the GIL to be acquired. Possible solutions:
	1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on the function to allow an error code to be returned.
(disable this message by setting show_performance_hints=False)
```
The rationale is that users will struggle how to disable this message (at least this is my suspicion). If there is consensus to add it I can extend this PR with that.

**Comment by da-woods** [comment]
> The rationale is that users will struggle how to disable this message (at least this is my suspicion). If there is consensus to add it I can extend this PR with that.

I think we should probably make it easier.

I wonder if we should make it a file-level "directive" rather than an "option" to make it a bit easier. On the basis that:
1. We do control warnings through directives
2. It's something that can be controlled on the command line already
3. It lets you turn it off for individual files which I think is a useful property.

**Comment by scoder** [comment]
> 2\. It's something that can be controlled on the command line already

There's also precedence for setting `Options.*` attributes from the command line by just listing equivalent option names.

However, I agree that a directive seems more sensible here and provides better granularity.

We can even allow it on functions – which might then lead to the funny (although small) uncertainty if disabling it for a function should apply it to the implementation of that function or to calls of that function. ;-)

**Comment by matusvalo** [comment]
> I wonder if we should make it a file-level "directive" rather than an "option" to make it a bit easier. 

+1 for that

**Pull request closed without merging**
