### PR TITLE
Check sys.path for .pxi files too

### PR DESCRIPTION
**Pull request by jdemeyer**
By analogy with `.pxd` files, Cython should also search `sys.path` for `.pxi` files.

This makes it feasible for packages to install `.pxi` files in `site-packages` which can then be included by other packages.

### CODE REVIEW

**Comment by jdemeyer** [comment]
CC @malb

**Comment by ignatenkobrain** [comment]
ping?

**Comment by isuruf** [comment]
ping

**Comment by jdemeyer** [comment]
Obsolete since `cysignals` no longer needs this.

**Pull request closed without merging**
