### PR TITLE
Format Pipeline.py

### PR DESCRIPTION
**Pull request by 0dminnimda**

### CODE REVIEW

**Comment by scoder** [comment]
No, that doesn't look good. We have a line length limit of 120 (enforced 150) characters. There's no need to go below that.

IF we really start reformatting code, then we should switch to Black and do it once and for all, for the whole code base, so that ignoring a single reformatting commit can be ignored by `git blame`.

**Comment by 0dminnimda** [comment]
> We have a line length limit of 120 (enforced 150) characters. There's no need to go below that.

That wasn't even the point of the PR. but ok, whatever, can you look here #4290, please?

**Comment by scoder** [comment]
> > We have a line length limit of 120 (enforced 150) characters. There's no need to go below that.
> 
> That wasn't even the point of the PR. but ok, whatever, can you look here #4290, please?

… you didn't really say what the point of this PR was. It looked like you wrapped some lines, and it wasn't clear to me why and under which pattern.

**Comment by 0dminnimda** [comment]
> you didn't really say what the point of this PR was. It looked like you wrapped some lines, and it wasn't clear to me why and under which pattern.

my bad

**Pull request closed without merging**
