### PR TITLE
Minimise the size of the code object table.

### PR DESCRIPTION
**Pull request by scoder**
Marking as draft since it currently *increases* the size of the function that builds the code objects. The reason is probably that the table is not static data and the more complex structure might lead to more code overhead in building it.

### CODE REVIEW

**Comment by scoder** [comment]
We really only have strings in the end. Per code object one tuple of argument names, one function name. Those could be stored with integer offsets already, no? We could create the argument name tuple in the creation function, just need a table of variable size argument name indexes then.

**Comment by da-woods** [comment]
> Those could be stored with integer offsets already, no?

Yes true. If you could do that then you could make the table a global constant too.

I decided that the `#define stringname modulestate->stringname` make this needlessly hard to do, but I believe it would actually be possible at the moment.

> We could create the argument name tuple in the creation function, just need a table of variable size argument name indexes then.

True, or just take `offsetoff(ModuleStateStruct, tuple_cname)` and use that. Again, the main thing making this hard is the defines.

**Comment by da-woods** [comment]
> We could create the argument name tuple in the creation function, just need a table of variable size argument name indexes then.

#6048 changes the tuples to a big array, so with that you'd just need an index.

**Comment by scoder** [comment]
Probably superseded by https://github.com/cython/cython/pull/6055

**Pull request closed without merging**
