### PR TITLE
mark extension types as immutable

### PR DESCRIPTION
**Pull request by maxbachmann**
Since https://github.com/python/cpython/pull/25520 types are automatically marked as immutable if they are static.
While we still have the `Py_TPFLAGS_HEAPTYPE` hack in place we need to manually mark our types as immutable.

### CODE REVIEW

**Comment by maxbachmann** [comment]
This leads e.g. to the following issue:
```
Python 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rapidfuzz.distance import Editop
>>> Editop.__name__ = 'test'
Segmentation fault (core dumped)
```

I will add a test for this later today.

**Comment by maxbachmann** [comment]
@da-woods apparently we do rely on the mutability, so I am unsure how we want to fix this.

**Comment by da-woods** [comment]
Ah I probably didn't mean to rely on the mutability. I basically just enabled all the CPython dataclasses tests that seemed to pass. However, Cython dataclasses _aren't_ Python dataclasses so they're allowed to differ in places. I'll revert the specific tests that rely on it.

I wasn't sure if immutability should be considered a feature or a side effect (i.e. whether there was a harm in leave things mutable). However, if you can cause segfaults with it so easily then we should definitely keep it.

**Comment by da-woods** [comment]
The dataclass test is easily disabled. The second failing test is to do with setting `Py_TPFLAGS_SEQUENCE` on the memoryview wrapper class. I think that's well worth doing since it makes it behave like a sequence for pattern matching. It needs a bit of thought about how we do it with immutable classes though since it can't be done after the fact.

I think a `@cython.tp_flags` decorator might be useful (taking either "sequence" or "mapping") - I could imagine users might want to register their own classes like this so it shouldn't just be a utility code hack for memoryview.

I think proceed with this PR because we will want to make these immutable again, but fixing up the cases where we(/I) accidentally used mutability won't be instant.

**Comment by da-woods** [comment]
Link 1 https://github.com/cython/cython/pull/5026

**Comment by da-woods** [comment]
#5030 solves the remaining blocker for this. It is adding a feature though so I'll be patient and let it be reviewed properly.

**Comment by da-woods** [comment]
@scoder I'd quite like to get this in the next release. It's been a bug for a while but it seems like something to fix before people start relying on the wrong behaviour.

It could do with a test - I'll have a go at writing one later today.

It's blocked by https://github.com/cython/cython/pull/5030 (but there's other options if you don't like that - in the short-term just to disable the tests)

**Comment by da-woods** [comment]
Closing/reopening to rerun tests

**Comment by da-woods** [comment]
Thanks @maxbachmann

**Pull request merged**
