### PR TITLE
[0.29] Account for possible extension type struct padding when calculating the itemsize for the "size changed" check

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by scoder** [comment]
Probably a net improvement. Thanks.

**Comment by dalcinl** [comment]
@scoder @hroncok This change leads to regressions when including  `XXX_api.h` headers generated from different Cython versions. Here you the problem in action: https://gitlab.com/petsc/petsc/-/issues/1359#note_1353622160
In that GitLab issues, the OP is building an extension module that includes API headers for both mpi4py and petsc4py. The mpi4py ones come from the sdist tarball, and where generated by Cython 0.29.32, while petsc4py is generating C sources with latest Cython 0.29.34.

IMHO, we have to revert this change for 0.29.x, or find an alternative and backward compatible way to do things.

**Comment by scoder** [comment]
Great. Need to look into this next week, but I guess, if we reverted this now, we'd have the same problem in two directions for released packages that have used the latest Cython 0.29.x.

Yet another reason not to backport changes to 0.29.x any more.

**Comment by hroncok** [comment]
Oh :( Sorry about that.

**Comment by dalcinl** [comment]
After thinking a bit more about it, this problem is beyond the typical backport issue. Cython has changed an external API in a backward incompatible way. A Cython 3 header will no longer interoperate with headers generated from any of the older Cython 0.2x releases. I don't think we want to go that way.

The proper fix is to add a Cython "_{major}_{minor}" version tag in the name to routines that go to generated C headers. For example:
```C
static PyTypeObject *__Pyx_ImportType_3_0( ... );  /*proto*/
```
This way, headers generated from multiple Cython versions can be #included together. If any of these APIs should ever change again, we just bump  the tag with the version numbers of the Cython release making the breaking change, and we are good to go.

PS: To make this right once and for all, we should check the APIs in current master against 0.29.0 (maybe also 0.28.0?) for any changes that we may be missing.

**Comment by da-woods** [comment]
I'd propose going one step further than @dalcinl - don't try to keep track of breaking api changes, just change the function names (`__Pyx_ImportFunction`, `__Pyx_ImportType`), macro names (`__PYX_GET_STRUCT_ALIGNMENT`) and the guard macros (`__PYX_HAVE_RT_ImportFunction`, `__PYX_HAVE_RT_ImportType`) with every single Cython version, by appending the Cython version to them.

That way no intelligence is needed, nobody has to notice that they're making a breaking change, it's just always different.

(Hypothetically we could go one step further still and add a hash of the module that's being compiled to the name, to make them absolutely unique so everything always uses its own copy. But I don't think there's a real need to go that far).

It doesn't fix the past of course but should help with the future.

**Comment by dalcinl** [comment]
@da-woods Great idea! Minor nit: we have to add `__Pyx_ImportVoidPtr` to your list.

**Comment by da-woods** [comment]
> @da-woods Great idea! Minor nit: we have to add `__Pyx_ImportVoidPtr` to your list.

Check the PR ;) https://github.com/cython/cython/pull/5383

**Pull request merged**
