### PR TITLE
provide support for the complex library

### PR DESCRIPTION
**Pull request by kif**
available since C99... may be valid only after Python2 is dropped on
Windows.

### CODE REVIEW

**Comment by scoder** [comment]
Please add a little test anyway. You can add it to the `windows_bugs.txt` file to exclude it in MSVC for now (preferably with a comment why it's excluded).

**Comment by scoder** [comment]
Ping! :)
A test would be helpful to get this merged.

**Comment by kif** [comment]
On Tue, 14 May 2019 12:57:26 -0700
Stefan Behnel <notifications@github.com> wrote:

> Ping! :)
> A test would be helpful to get this merged.

Arg, I forgot enout it.

**Comment by kif** [comment]
There is test that works for me ... not sure it works everywhere. let's wait for Travis' point of view

**Comment by kif** [comment]
Just a question: How do you prevent the test to use the C++ backend ?

**Comment by scoder** [comment]
Sorry for the silence. There is a tag `no-cpp` for this (had to look it up myself, found it in `runtests.py`).

**Comment by leofang** [comment]
Can this PR be merged? Having access to complex is helpful to scientific computing!

**Comment by kif** [comment]
That was my original idea ...

**Comment by robertwb** [comment]
This looks fine to me--doesn't change the default behavior and lets the user cimport rather than declare all of these methods, and the test looks fine as well. Thanks.

**Pull request merged**
