### PR TITLE
Add utility code macro "EMPTY(bytes|tuple|...)"

### PR DESCRIPTION
**Pull request by scoder**
Suggested here: https://github.com/cython/cython/pull/5323#issuecomment-2303922556

### CODE REVIEW

**Comment by scoder** [comment]
CI is green, ready for review.

**Comment by da-woods** [comment]
Looks good to me.

It's a bit of a shame that it ends up "module specific" given how commonly it's used. I think we could probably avoid that since the module state structure always starts in exactly the same way with these types. I think that's something that would be better fixed later rather than in this PR though.

**Comment by scoder** [comment]
> It's a bit of a shame that it ends up "module specific"

That was a conservative measure. It's not *really* module specific, given that it (currently) has a deterministic C code representation that does not change across modules. We could mark it as generic, thus leading to more shareable headers.

**Comment by scoder** [comment]
That gets the number of shared include files in the `common_include_dir` test up to 44. Seems worth doing.

**Pull request merged**
