### PR TITLE
More complete cpdef enums.

### PR DESCRIPTION
**Pull request by robertwb**
For example

    cpdef enum Eggs
        SOFT
        HARD
        SCRAMBLED

produces three constants with int values that print as strings,
and a type Eggs with attributes Eggs.SOFT, etc. and list(Eggs)
giving the set of all enum values.  Instantiating Eggs with a
numeric or string value will return the appropriate constant.

### CODE REVIEW

**Comment by scoder** [comment]
Really nice feature overall. Worth documenting.

**Comment by scoder** [comment]
How does this relate to PEP 435 enums, BTW? Would it be possible to use those instead? Or at least inherit from them somehow?

**Comment by robertwb** [comment]
Oh, I hadn't seen those. I'll make it compatible, looking into actual
inheritance for Python >= 3.4. (I think our cdef enums still need to be
IntEnums...)

**Comment by scoder** [comment]
Looks good to me overall and can be merged. github says it's conflicting, but that might just be the changelog entry.

**Pull request merged**
