### PR TITLE
fix `Py_None` references

### PR DESCRIPTION
**Pull request by ukabuer**

### CODE REVIEW

**Comment by da-woods** [comment]
Thanks. Will merge once the tests have passed. This looks like something that should go into 0.29.x too (no need for you to do anything there though...)

**Comment by scoder** [comment]
We're not actually returning references from this function, just NULL for errors or None in the end. Not sure (and cannot check right now) if there is a reason to incref the None, or to return a reference at all.

**Comment by da-woods** [comment]
On closer look, (as @scoder says) we're not doing anything with the reference so an incref would be wrong.

We should probably just return an int for the function (0 for success; -1 for failure as usual). That'd be a lot clearer about the actual intent.

I'll close this PR, but a tidy up of the return type would be welcome.

**Comment by ukabuer** [comment]
I fixed a crash problem in my application caused by incorrect `PyNone` references (not related with cython), and then a global search found this in my codespace.
Haven't check the usage of the function, but it is some kind of misleading here so change the return type would be nice.
I do not have the testing envrionment for cython itself so wish some other people would help with this :)

**Pull request closed without merging**
