### PR TITLE
fixed typo in type-indexing functions

### LINKED ISSUE #6472: Cython documentation for fused types
### Describe your issue

In 
The last example of https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html#indexing
looks like this:
```python
ctypedef fused my_fused_type:
    int[:, ::1]
    float[:, ::1]

def func(my_fused_type array):
    print("func called:", cython.typeof(array))

my_fused_type[cython.int[:, ::1]](myarray)
```
But...
Shouldn't this be:
```python
ctypedef fused my_fused_type:
    int[:, ::1]
    float[:, ::1]

def func(my_fused_type array):
    print("func called:", cython.typeof(array))

func[int[:, ::1]](myarray)
```
And the same for the `Pure Python` mode.

I would be happy to make a PR, if needed (very small change), but I would like a confirmation first!

### PR DESCRIPTION
**Pull request by zerothi**
Also removed unnecessary cython. in the interface choice

This fixes #6472.

### CODE REVIEW

**Comment by da-woods** [comment]
So the slight issue is that neither seem to work unfortunately.

You're definitely right with spotting the big mistake (that `func` is missing). But `cython.int`/`int` isn't appropriately subscriptable so that doesn't work. And `func[my_fused_type[cython.int[:, ::1]]](myarray)` also doesn't work.

Right now I'm not sure what the right fix for this is.

**Comment by da-woods** [comment]
(Should probably have spotted this earlier)

**Comment by zerothi** [comment]
@da-woods could we still merge this, since the current documentation is misleading.

I agree the other thing is a problem, but then it should just be removed! :)

**Comment by da-woods** [comment]
@zerothi Agree it's misleading. I think I'd rather remove it all together rather than updating it to something that also doesn't work. See #6540 - I've put that as "co-authored by" since you did point it out. But let me know what you think.

**Comment by da-woods** [comment]
> > I think I'd rather remove it all together rather than updating it to something that also doesn't work.
> 
> There is version that works but it is tricky. Maybe this is a reason not to delete it. I will create a alternative PR with examples testted by CI/CD...

That would be better than removing it...

**Comment by da-woods** [comment]
Thanks for pointing this out. Closed in favour of #6541

**Comment by zerothi** [comment]
Thanks for fixing all these things! I am very happy with this!

Thanks for the co-author ;)

**Pull request closed without merging**
