### PR TITLE
Ignore `.dev` and `.post` segments in `build_hex_version()`

### LINKED ISSUE #5207: [BUG] `pip install git+https://github.com/cython/cython@master` fails
### Describe the bug

`pip install git+https://github.com/cython/cython@master` raises ValueError at 

```
File "Cython/Utils.py", line 624, in build_hex_version 
  digits.append(int(digit))
ValueError: invalid literal for int() with base 10: 'dev0'
```

### Code to reproduce the behaviour:

pip install git+https://github.com/cython/cython@master

### Expected behaviour

[...]
 Compiling /private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Parsing.py because it changed.
      [1/1] Cythonizing /private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Parsing.py
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/setup.py", line 317, in <module>
          run_build()
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/setup.py", line 245, in run_build
          setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Build/Dependencies.py", line 1280, in cythonize_one
          result = compile_single(pyx_file, options, full_module_name=full_module_name)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Main.py", line 604, in compile_single
          return run_pipeline(source, options, full_module_name)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Main.py", line 528, in run_pipeline
          err, enddata = Pipeline.run_pipeline(pipeline, source)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 397, in run_pipeline
          data = run(phase, data)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 374, in run
          return phase(data)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
          module_node.process_implementation(options, result)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 206, in process_implementation
          self.generate_c_code(env, options, result)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 475, in generate_c_code
          self.generate_module_preamble(env, options, modules, result.embedded_metadata, h_code)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 783, in generate_module_preamble
          code.putln('#define CYTHON_HEX_VERSION %s' % build_hex_version(__version__))
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Utils.py", line 624, in build_hex_version
          digits.append(int(digit))
      ValueError: invalid literal for int() with base 10: 'dev0'

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0dminnimda**
Fixes #5207 and covers the #5205

### CODE REVIEW

**Comment by 0dminnimda** [comment]
I missed when the "automatic killing of the previous running CI when the new one for this PR is running" was added, but I appreciate it. It makes a lot of sense and saves the computational power

**Comment by scoder** [comment]
Looks like we tried fixing this at the same time. Your last version was good, too.

**Comment by 0dminnimda** [comment]
@scoder why not double down and ignore `.post` as well? It's not too hard and will remove the possibility of such event happening again

**Comment by scoder** [comment]
Fair enough. I added that in https://github.com/cython/cython/commit/069794816423948a3dd7cc3365cf969d44fc9326

**Comment by 0dminnimda** [comment]
Sometimes our tonge is our enemy ;)

**Pull request closed without merging**
