### PR TITLE
Update numpy_tutorial.rst

### PR DESCRIPTION
**Pull request by loisaidasam**
Typo

### CODE REVIEW

**Comment by scoder** [comment]
Looks correct to me as it is.

**Comment by da-woods** [comment]
I think the proposed change is probably right. I think it has to match "take" (i.e. if it's "take"-"turn"; "takes"-"turns").

I can't really justify exactly what grammar rule this is though...

**Comment by loisaidasam** [comment]
Consider these two snippets:

> it doesn't "turn it into C"

vs. 

> it doesn't "turns it into C"

The first one is correct.

**Comment by scoder** [comment]
Ok. I'm not a native speaker, so I'll have to rely on your judgement here.

The way I was reading it is "it doesn't take your program and (then) turns it into C", which feels correct to me. If that's not how it works for you, then I'll be happy to merge this.

**Comment by scoder** [comment]
In any case, "turn" makes it clear that it still refers to "doesn't". Let's change it.

Thanks @loisaidasam and to the others for commenting.

**Comment by loisaidasam** [comment]
Thanks @scoder , I appreciate you 🙏 

Hopefully I didn't waste too many people on the internet's time with this, I was reading through the docs this morning and was honestly just trying to help

**Comment by scoder** [comment]
> I was reading through the docs this morning and was honestly just trying to help

Most people just read over mistakes and leave them for others to fix. So, thanks for taking the time to send a PR, even if the decision took a bit longer.

**Pull request merged**
