### PR TITLE
Allow PyPy users to define use_type_specs

### PR DESCRIPTION
**Pull request by da-woods**
It stands a decent chance of working because it's just a different implementation rather than access to internals (but is currently untested), so I don't see a reason to be hugely prescriptive.

### CODE REVIEW

**Comment by da-woods** [comment]
@mattip You were trying to use this the other week on some of your testing for PyPy (but ineffectively because we ignore it). For this flag I don't see the need to stop you from choosing your own implementation. But equally I haven't actual checked if it works. So if some PyPy tests where you've defined it suddenly break, this is why!

**Comment by mattip** [comment]
Thanks.

**Comment by mattip** [comment]
Yup, there is something off with [datetime unpickling](https://github.com/pypy/binary-testing/actions/runs/5914858784/job/16040562493#step:7:8939). PyPy uses the pure-python datetime.py and the pure-python pickle.py from CPython, I wonder where the name changes. There are errors of the form
```
pickle.PicklingError: Can't pickle \
    <cyfunction __pyx_unpickle_R_TestCase_test_dataclasses_pickleable at 0x1e57f180>: \
    it's not found as \
    _cython_3_0_0.__pyx_unpickle_R_TestCase_test_dataclasses_pickleable

```

**Comment by da-woods** [comment]
It's getting the module name wrong I think - that module name is the global shared module where `CyFunction` lives, rather than where the specific function lives.

I don't think that's got anything obvious to do with datetimes though

**Comment by da-woods** [comment]
You can demonstrate the issue with

```
# somefile.pyx
def f():
    pass
```

`CFLAGS="-DCYTHON_USE_TYPE_SPECS=1" pypy3 cythonize.py -if somefile.pyx`

then

```
>>>> import somefile
>>>> somefile.f.__module__
_cython_3_0_0
```

while it doesn't in CPython, or in PyPy without typespecs.

I suspect it's ignoring
https://github.com/cython/cython/blob/8541f4e7b3ea919fa4c50f5efa0a6220c2503034/Cython/Utility/CythonFunction.c#L525-L527
for some reason, but I'm not sure I'd know how to diagnose why

**Comment by da-woods** [comment]
Looks like you already created an issue - linked for reference https://foss.heptapod.net/pypy/pypy/-/issues/3993

**Pull request merged**
