### PR TITLE
Partial remove usages of deprecated Numpy API

### PR DESCRIPTION
**Pull request by jbrockmendel**
@mattif ref #2498

The remaining problem is that the `ndarray` class that numpy exposes doesn't have most of the attributes that it used to.  So for example I got rid of `descr` and replaced the one usage of `self.descr` with `PyArray_DESCR(self)`.  But there are other attributes that aren't as easy to replace.

When I install this branch and try to build pandas with it, I get errors of the form:
```
pandas/_libs/algos.c:19128:36: error: no member named 'dimensions' in 'struct tagPyArrayObject'
  __pyx_v_length = (__pyx_v_index->dimensions[0]);

pandas/_libs/algos.c:71747:34: error: no member named 'strides' in 'struct tagPyArrayObject'
  __pyx_t_9 = (((__pyx_v_values->strides[1]) == (__pyx_v_out.strides[1])) != 0);
```

Frankly I think the fewer-attributes version is a pain, since it means in downstream code I won't be able to use e.g. `arr.shape`, but se la vie.

Could we fake the `shape` attribute as e.g. a property defined in the pxd file?

### CODE REVIEW

**Comment by robertwb** [comment]
I'd rather not special case this, but it may be preferable to fixing all the code out there using these attributes (that, I suppose, use the deprecated API). The switch from attribute access to a macro (?) to access these is less natural in Python than in C.

**Comment by mattip** [comment]
I think putting the deprecated fields into a 
```
#if !defined(NPY_NO_DEPRECATED_API) || \
    (NPY_NO_DEPRECATED_API < NPY_1_7_API_VERSION)
.... direct declarations here
#endif
```
would cause direct field access to fail only for people who define `NPY_NO_DEPRECATED_API >= NPY_1_7_API_VERSION`. Not defining that constant will continue to print out warnings. Hopefully that will annoy them enough to define it to the latest version and fix their code.

Then we could try cython tests with `CFLAGS=-DNPY_NO_DEPRECATED_API=NPY_1_14_API_VERSION` and without in order to see the warnings dissapear.

At least that is the [theory](http://www.numpy.org/devdocs/reference/c-api.deprecations.html), if I understand it correctly.

@robertwb The whole goal is to move "all the code out there" to using the newer API.

**Comment by robertwb** [comment]
I think it makes a lot of sense to fix everything but the direct field
access soon. For that, I see a couple of options:

(1) Force all Cython users to stop using attribute access, at least without
setting a (C-level) macro,
(2) Special case these attributes in the numpy.ndarray class, or
(3) Support @property (or similar) annotations in extern classes to define
setters and getters directly in the pxd.

**Comment by robertwb** [comment]
Oh, yes, I like that option. I still think it's an unfortunate regression
to have to go from using .shape in particular to a "method" call when
moving from pure Python to Cythonized code; not sure if it's bad enough to
warrant an exception (or if we should just push MemoryViews more, if
performance and everything else has been brought up to parity).

**Comment by jbrockmendel** [comment]
I'd like to make a pitch for keeping `ndim` and `shape` etc attributes available.  Besides the annoyance-downstream issue, discussion in #2498 suggests numpy folks may be amenable to bringing back the attributes that were deprecated so that authors can continue having their code Just Work.

> (or if we should just push MemoryViews more, if
performance and everything else has been brought up to parity)

Side Note FWIW: I've been transitioning a bunch of pandas code to use memoryviews recently.  The main things slowing that transition are:
  - for some functions we need to use `np.ndarray.searchsorted` (which is a python call, but se la vie)
  - I'm not aware of a memoryview-only equivalent of `np.ones(n, dtype=np.int64)` (i.e. I know I can do `cdef int64_t[:] arr = np.ones(n, dtype=np.int64)` but I'd like to do this without a call into python-land)
  - PR reviewers are very picky about anything that impacts perf, and it isn't obvious whether the relevant uses cases see improvements and by how much.

**Comment by scoder** [comment]
I applied most of this PR manually in 222334c0b91eae41de2af2692daec6183cdaf243 to avoid backwards incompatible breakage. Specifically, I did not remove the existing declarations, just removed their usage and added the new declarations.

**Comment by scoder** [comment]
Closing this PR since we have #2498 to track the general issues.

**Pull request closed without merging**
