### PR TITLE
backport: Implement PEP-563, annotations as strings

### PR DESCRIPTION
**Pull request by dalcinl**
Backport of #3285 to branch 0.29.x.

### CODE REVIEW

**Comment by dalcinl** [comment]
@da-woods Would you be willing to help me with this one? 

I run `git cherry-pick` on your commit 3dc2b9dfc23638fbef2558d619709b5235d5df08. With this, I'm able to cythonize the mpi4py codebase (in branch `update/cython-3`) with Cython from either 0.29.x or master. Therefore, I expect this backport to help users to migrate smoothly to Cython 3.

However, there are a bunch of changes to tests that are probably wrong, not to mention some other backward-compatibility issues that I may be missing. As you are the author of the original commit, it you are in the best position to comment. I'll not be available during the next few days, but please drop your comments at your convenience, I'll address them once I'm back online.

**Comment by da-woods** [comment]
I think this is going to be a fairly dramatic change to backport to 0.29.x so I'd be pretty reluctant to approve this. It seems like it'd bring a potential incompatibility forward rather than help people to migrate.

I'm also less sure about what we want to do about PEP-563: it doesn't look like the way that Python is actually going in the future (although I haven't seen much sign of a decision being taken for anything else). And it does seem to cause periodic confusion because very few people actually use or know of it. I suspect we will adopt it for Cython 3. But I wonder if it might be short-lived.

With all this said, it looks like the PR broadly works.

**Comment by dalcinl** [comment]
@da-woods Sorry, but I do not understand the your reluctance.

* Right now, unevaluated annotations work in Cython 3, but they are not the default, users have to explicitly opt-in using `from __future__ import annotations`.
* At the same time, annotations in Cython 2 works in a weird way, depending on whether the `binding` option is true or not. In Cython 2, If you ask `binding=true` then annotations are evaluated, and trying to use `from __future__ import annotations` fails with compiler error (future feature not available).

In mpi4py, I need unevaluated annotations, mostly because of documentation purposes. Sphinx advice users to use `from __future__ import annotations` to keep annotations unevaluated and that way rendering nicer function signatures as generated by Sphinx's autodoc extension.

It is a bit hard to keep a codebase working with both Cython 2 and Cython 3. I would not care too much about Cython 2 if it were not by the fact that there is no release of Cython 3 just yet. Beside that, we should try to offer users as much of a smooth transition as possible. This PR is a step in that direction. As the feature is opt-in, and without this PR Cython 2 cannot cope with `from __future__ import annotations`, I believe this is a win-win.

**Comment by da-woods** [comment]
> Right now, unevaluated annotations work in Cython 3, but they are not the default, users have to explicitly opt-in using `from __future__ import annotations`.

No - they are the default in Cython 3. `from __future__ import annotations` doesn't do anything in Cython 3 and it isn't possible to turn off unevaluated annotations. Hence it's a fairly significant change because it affects all annotations.

**Comment by scoder** [comment]
> At the same time, annotations in Cython 2 works in a weird way, depending on whether the `binding` option is true or not. In Cython 2, If you ask `binding=true` then annotations are evaluated, and trying to use `from __future__ import annotations` fails with compiler error (future feature not available).

That sounds like a bug. Could you explain a bit more in detail what you mean here? The `binding` directive shouldn't have any effect on annotations.

That said, I agree with @da-woods that this would be a rather heavy behavioural change for the legacy 0.x release series and I'd need a very compelling reason to take the risk of breaking existing user code (or existing Cython builds in one way or another) with this.

**Comment by dalcinl** [comment]
> [@da-woods] No - they are the default in Cython 3. from __future__ import annotations doesn't do anything in Cython 3 and it isn't possible to turn off unevaluated annotations. Hence it's a fairly significant change because it affects all annotations.

> [@scoder] That sounds like a bug. Could you explain a bit more in detail what you mean here? The binding directive shouldn't have any effect on annotations.

Sorry, guys, I'm most likely confusing things and then making a mess. To my defense, I'm most likely being bitten by a bug.

I'm using Cython latest release 0.29.32. See the following reproducer. 
```cython
#cython: language_level=3
#cython: binding=True

#from __future__ import annotations

cimport cython

cdef Optional

def bar(arg: Optional[int]):
    pass
```
Note I'm setting `language_level=3` and `binding=True` with the latest 0.x release. I believe I've misnomered this setup as "Cython 2", sorry for the confusion.
Then I use the following to test the snippet:
```python
import pyximport
pyximport.install()
import foo
```
and it does not work at runtime:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 343, in load_dynamic
    return _load(spec)
  File "foo.pyx", line 10, in init foo
    def bar(arg: Optional[int]):
TypeError: 'NoneType' object is not subscriptable
```
because the `Optional[int]` annotation is being evaluated. 
The runtime error disappears if you set `binding=False`.

Another two issues probably related issues:
* If you uncomment the `from __future__ ...` line, Cython 0.x fails to compile.
* But then, if you comment out the `cdef Optional` line, Cython also fails to compile.
and these two issues combined make the Cython code incompatible with Python 3. These two issues seems to trigger no matter what the value of `binding` is.

This PR is a lame attempt to fix the problems I described above. Any clue what could be going on? I'm totally fine with declining this PR and follow a different fix path for the 0.x legacy releases, but I really need some pointers in the right direction.

**Comment by da-woods** [comment]
So Cython 0.29.x doesn't support `from __future__ import annotations` because it doesn't know what to do with it. Cython 3.0 supports it (but always turns it on anyway).

> The binding directive shouldn't have any effect on annotations.

The `binding` directive creates CyFunctions with an accessible `__annotations__` attribute, which means that it must be possible to evaluate the annotations (on Cython 0.29.x). So I would expect this to have an effect.

I wonder if there's a less drastic change we could do. How about just letting Cython 0.29.x understand `from __future__ import annotations` but just treat it as "don't generate the `__annotations__` attribute" rather than backporting all the string stuff. I haven't given this a lot of thought though.

**Comment by dalcinl** [comment]
I'm still failing to the the backward compatibility issues both of you are worried about.
Can you think of any example I can try that would trigger such issues?
Is your worry actually about `language_level=2`, or rather the behavior under the 0.x series?

> How about just letting Cython 0.29.x understand `from __future__ import annotations` but just treat it as "don't generate the `__annotations__` attribute" rather than backporting all the string stuff. I haven't given this a lot of thought though.
Do you think it would be really difficult to do the string stuff only if the future import is done, and if not, keep the current 0.29.x behavior ? IMHO, There should be no backward compatibility concerns, simply because the future import is simply not working right now under 0.29.x. Am I missing something?

**Comment by da-woods** [comment]
> I'm still failing to the the backward compatibility issues both of you are worried about.

There's a number of issues where people are using introspection on annotations and are confused by the changing behaviour.

https://github.com/cython/cython/issues/4491
https://github.com/cython/cython/issues/5010
https://github.com/cython/cython/issues/3438

Not all of these will apply to Cython 0.29.x (some relate to class annotations which just aren't supported at all there). But I'd be very surprised if this didn't cause some issues.

> Do you think it would be really difficult to do the string stuff only if the future import is done, and if not, keep the current 0.29.x behavior ? IMHO, There should be no backward compatibility concerns, simply because the future import is simply not working right now under 0.29.x. Am I missing something?

I have a provisional PR that does this on master (https://github.com/cython/cython/pull/4463) which I'm keeping kind of up-to-date in case Python does come to a decision about the future behaviour of annotations. So it isn't impossible. but it isn't that clean or well-tested.

**Comment by dalcinl** [comment]
> I have a provisional PR that does this on master (#4463) which I'm keeping kind of up-to-date in case Python does come to a decision about the future behaviour of annotations.

Sorry about being so insistent, but I still don't fully get the concerns. Up until today, under Python 3.7.+, coder authors have a per-module choice: a) without the future import, annotations are evaluated. b) with the future import (opt-in, the code author has to write the import statement explicitly) annotations are kept unevaluated as strings. 

Why can't Cython just follow these rules to maximize compatibility with Python semantics?
Moreover, in case of doubt and to future-proof about changes in semantics (e.g. PEP 649), perhaps we could use a `# cython: ...` compiler directive to explicitly let users decide how to exactly treat annotations?

**Comment by da-woods** [comment]
> but I still don't fully get the concerns

The main thing I'm opposed to is backporting what we currently have in master. That forces a change in behaviour and will almost certainly break some code that introspects annotations or function signatures. That's probably OK in Cython 3, but not OK in a 0.29.x release.

--------------------------------------------

> Up until today, under Python 3.7.+, coder authors have a per-module choice: a) without the future import, annotations are evaluated. b) with the future import (opt-in, the code author has to write the import statement explicitly) annotations are kept unevaluated as strings.

> Why can't Cython just follow these rules to maximize compatibility with Python semantics?

This is arguing for changing what we do in Cython (i.e. not a simple backport). I actually (weakly) agree with this. PEP-563 does not look like the real future behaviour so it might be a mistake to pick it. #4463 does this but would need proper review - I'm not going to merge it unilaterally.

If we made then change in Cython 3 then we could consider backporting it since it looks like it solves some real problems. But I don't think we should add something more complicated to 0.29.x first.

**Comment by scoder** [comment]
> I'm still failing to the the backward compatibility issues both of you are worried about.

I'm more generally worried about changing anything major in future Cython 0.29.x releases at all. As it stands, it does what it was designed to do, most of our users still rely on it doing exactly that, and each time (at least twice) we've any recently backported a behavioural change to 0.29.x, we ended up reverting it because it unnecessarily broke some people's code.

Cython 0.29.x is really a legacy stable branch that should be retired as soon as possible and not take any risk at all of receiving incompatible changes. Cython 3.0 is for those.

I'll close this PR because I don't see us do this backport.

**Pull request closed without merging**
