### PR TITLE
Make limited API object==float work

### LINKED ISSUE #6093: [BUG] Bug with limited API support in trivial program involving float literal
### Describe the bug

Float literals in equality comparison operators in limited API mode trigger some unsupported code path. Oddly, the compile error comes extremely early, in the include of Python.h itself, which made me slightly suspect a potential error in CPython's own limited API support. However, other operators (e.g. inequality comparisons) do not trigger the error, and neither do integer comparisons, which makes me think that it's more likely that the cause is something Cython itself is doing to generate invalid code that somehow triggers this path. Unfortunately, I can't quite pin down what it is.

I'll note that I also see different failure modes depending on whether I compile the Cython module as C or C++. When compiling in C++, I see this:
```
/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -fPIC -DPy_LIMITED_API=0x030B0000 -DCYTHON_LIMITED_API -I/home/coder/.conda/envs/rapids/include/python3.11 -c test.cpp -o build/temp.linux-x86_64-cpython-311/test.o
In file included from /home/coder/.conda/envs/rapids/include/python3.11/Python.h:55,
                 from test.cpp:41:
/home/coder/.conda/envs/rapids/include/python3.11/floatobject.h: In function 'PyObject* __Pyx_PyFloat_EqObjC(PyObject*, PyObject*, double, int, int)':
/home/coder/.conda/envs/rapids/include/python3.11/floatobject.h:14:26: error: 'PyFloat_Type' has incomplete type
   14 | PyAPI_DATA(PyTypeObject) PyFloat_Type;
      |                          ^~~~~~~~~~~~
In file included from /home/coder/.conda/envs/rapids/include/python3.11/Python.h:42,
                 from test.cpp:41:
/home/coder/.conda/envs/rapids/include/python3.11/pytypedefs.h:20:16: note: forward declaration of 'PyTypeObject' {aka 'struct _typeobject'}
   20 | typedef struct _typeobject PyTypeObject;
```

When compiling in C, I instead see this:
```
/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -fPIC -DPy_LIMITED_API=0x030B0000 -DCYTHON_LIMITED_API -I/home/coder/.conda/envs/rapids/include/python3.11 -c test.c -o build/temp.linux-x86_64-cpython-311/test.o
test.c: In function '__Pyx_PyFloat_EqObjC':
test.c:6745:37: error: invalid use of incomplete typedef 'PyTypeObject' {aka 'struct _typeobject'}
 6745 |                         PyFloat_Type.tp_richcompare(op2, op1, Py_EQ));
```

### Code to reproduce the behaviour:

```cython
# test.pyx
x = 1
# x = 1.0  # This is also fine

x == 1.0  # This will raise an error regardless of which line is used above
# x < 1.0  # This will not raise an error
# x == 1  # This will not raise an error

# setup.py
from setuptools import Extension, setup
from Cython.Build import cythonize

extensions = [
    Extension(
        "test", ["test.pyx"],
        define_macros=[("Py_LIMITED_API", "0x030B0000"), ("CYTHON_LIMITED_API", None)],
        language="c++",  # This changes the error
    )
]

setup(
    name='test',
    ext_modules=cythonize(extensions),
)
```

### Expected behaviour

This code should compile

### OS

Linux

### Python version

3.11.8

### Cython version

Merge of #6061 and the limited API branch from #6082

### Additional context

There is also a separate limited API issue with `PyList_GET_ITEM` that I observe in the above MWE, but I've fixed that in #6061.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #6093

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
I can confirm that this fixed the case where I originally ran into the issue.

**Comment by vyasr** [comment]
I think this PR ought to be safe to merge? Just noticed that it wasn't when updating some of my testing to use the latest limited API preview branch.

**Comment by scoder** [comment]
We should add a test case with something else than an integer. It seems reasonable to add a special case implementation for them, and then we'd lose the actual test by accident. Any other type will do for a non-eq test case.

**Comment by da-woods** [comment]
> We should add a test case with something else than an integer.

Done. I haven't been too thorough with the limited API testing because long-term it should mostly be covered by the "real" tests when we can enable them. But this is easy to add.

**Pull request merged**
