### PR TITLE
Bug 4096 (Using CFLAGS for compiler defines)

### PR DESCRIPTION
**Pull request by vorfol**
Creating global CDEFS for holding compiler definitions. Then pass it to the distutils.

Also add .vscode folder to .gitignore

Fixes https://github.com/cython/cython/issues/4096

### CODE REVIEW

**Comment by robertwb** [comment]
The change looks reasonable to me, but travis isn't very happy with it.

**Comment by da-woods** [comment]
I think the failures are just because it's based on a slightly old version of master. It might be worth merging the latest master into this and seeing if that improves it.

**Comment by scoder** [comment]
Travis always merges the PR branch into the target branch first.

**Comment by scoder** [comment]
Thanks

**Pull request merged**
