### PR TITLE
Fix 3564 in 0.29

### LINKED ISSUE #4637: [BUG] Generated C/C++ source compiles with maybe-uninitialized warning with CYTHON_TRACE_NOGIL set
**Describe the bug**

Code generated from the following Cython source, when compiled with `-DCYTHON_TRACE_NOGIL=1` generates compilation warning ``warning: ‘__pyx_gilstate_save’ may be used uninitialized in this function``.

```
gcc -pthread -B ~/miniconda3/envs/gh767/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem ~/miniconda3/envs/gh767/include -fPIC -O2 -isystem ~/miniconda3/envs/gh767/include -fPIC -DCYTHON_TRACE_NOGIL=1 -DCYTHON_TRACE=1 -I~/miniconda3/envs/gh767/include/python3.10 -c gh767/_ext.c -o build/temp.linux-x86_64-3.10/gh767/_ext.o
gh767/_ext.c: In function ‘__pyx_pw_5gh767_4_ext_1handler’:
gh767/_ext.c:898:34: warning: ‘__pyx_gilstate_save’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  898 | #define __Pyx_PyGILState_Release PyGILState_Release
      |                                  ^~~~~~~~~~~~~~~~~~
gh767/_ext.c:1906:20: note: ‘__pyx_gilstate_save’ was declared here
 1906 |   PyGILState_STATE __pyx_gilstate_save;
      |                    ^~~~~~~~~~~~~~~~~~~
creating build/lib.linux-x86_64-3.10
```

The warning is observed for both C and C++ generated languages. The warning goes away if `CYTHON_TRACE_NOGIL` is unset (even if `CYTHON_TRACE` is set).

**To Reproduce**

Use the following cython source, or clone [reproducing project](https://github.com/oleksandr-pavlyk/compiler-warning-cython-generated-source-reproducer) and execute `python setup.py build`.

```cython
# cython: language_level=3
# cython: linetrace=True

cdef class MyError(Exception):
    """
    An  exception is raised when operation submission
    or execution encounters an error.
    """

cdef void foo(int err) nogil except *:
    with gil:
        raise MyError(err)

def handler(int err):
    if (err % 2):
        with nogil:
            foo(err)
    else:
        print("All good")
```

**Expected behavior**

Generated code should compile cleanly using cython=0.29.* as it already does using Cython=3.0.0a10.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: all
 - Cython version reproduced with versions 0.29.24-0.29.27

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes #4637.

This change set was obtained using 
```
git checkout 0.29.x
git cherry-pick 7d99b0f085bb254e9a9b4a9fe50aefe133837a81 01085d2ad588bf41e2d17cff6aa96d0507087ce3 
```

and conflicts in `Cython/Compiler/Nodes.py` manually resolved, as well as removed `tests/run/with_gil_automatic.pyx` as it was failing.

#4703 only contained the first commit there. 

I checked that scikit-image could be built with this change-set. Local test has 1 error: `ERROR: test_embed (__main__.EmbedTest)`, but this time (unlike #4744) it is likely due to missing env. variables.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@scoder This is my latest attempt to backport the fix to 0.29.x. Perhaps since I used the same branch name the CI did not kick in. Please review at your convenience.

**Comment by scoder** [comment]
> removed `tests/run/with_gil_automatic.pyx` as it was failing.

That's … unfortunate, because that file contains the test suite for this change. If that fails, there's probably a reason. Maybe we only need parts of that test file? Do you have a log of the tests in there that failed? (And their output.)

**Comment by scoder** [comment]
Sorry, forget my last comment. That test file is related to the changes you accidentally had in your previous PR, but no to the bug we're trying to resolve here.

**Comment by scoder** [comment]
Closing and reopening to see if that triggers a CI build.

**Comment by oleksandr-pavlyk** [comment]
The error in cpp py2.7 says:

```
Errors from shard 6:
======================================================================
FAIL: runTest (__main__.EndToEndTest)
[6] End-to-end line_profile_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1772, in runTest
    self.assertEqual(0, res, "non-zero exit status")
AssertionError: non-zero exit status
```

Is it a known flake?

**Comment by da-woods** [comment]
> The error in cpp py2.7 says:
> 
> ```
> Errors from shard 6:
> ======================================================================
> FAIL: runTest (__main__.EndToEndTest)
> [6] End-to-end line_profile_test
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "runtests.py", line 1772, in runTest
>     self.assertEqual(0, res, "non-zero exit status")
> AssertionError: non-zero exit status
> ```
> 
> Is it a known flake?

I think so (in 0.29.x)

**Comment by scoder** [comment]
Thanks @oleksandr-pavlyk.

The description of https://github.com/cython/cython/issues/4637 has a reproducer for the compilation issue. Could you please add that as an additional test into a new file `tests/run/trace_nogil.pyx` and then add a doctest to the `handler()` function that calls the function and exercises both cases for `err`?

**Comment by oleksandr-pavlyk** [comment]
I am not sure what I am doing wrong with the doctest. In the interest of saving CI resource, please advise.

**Comment by da-woods** [comment]
You can run the doctest locally with `python3 runtests.py trace_nogil`. That should let you investigate without rerunning the whole CI

**Comment by oleksandr-pavlyk** [comment]
One issue I am running into with doctest is that exception typesets as `trace_nogil.MyError` in some configs, but as `MyError` in others (and this does not match against expected `trace_nogil.MyError`.

I there going to deviate from the example in #4637 and use built-in exception rather than my own. I checked that the compiler warnings get generated even if the original example changed that way.

**Comment by da-woods** [comment]
That seems reasonable - I don't think the type of the exception is particularly important for the test. (You could probably also have used doctest's ellipsis feature, but using a builtin exception is the much simpler solution)

**Comment by scoder** [comment]
Reverted in 0.29.30 due to #4796.

**Pull request merged**
