### PR TITLE
Update preprocessing warning to be compatible with MSVC

### PR DESCRIPTION
**Pull request by molinav**
Solves #4825.

I am not sure about the standard (if any) for indenting code blocks in the generated C source code, so I wrote the 4-space indentation the naive way.

### CODE REVIEW

**Comment by da-woods** [comment]
> I am not sure about the standard (if any) for indenting code blocks in the generated C source code, so I wrote the 4-space indentation the naive way.

It auto-indents braces itself. I don't think it handles `#prepocessor` stuff. If the non-generated .c files we look to use a mixture of 2- or 0-space indents. Personally I'd probably use 0-space here

**Comment by molinav** [comment]
Thanks for the feedback. I saw this autoindentation when adding braces with `code.begin_block()` and `code.end_block()`, but I discarded to use them here because the braces were not used in other parts for the preprocessing blocks.

I am fine with any indentation, so I will just go for the 0-space version if this is being used for most of the other preprocessing blocks.

**Comment by da-woods** [comment]
Thanks

**Comment by molinav** [comment]
To have this bug also fixed in the "stable" 0.29.x versions (since they are also affected), how shall I proceed? Should I create another PR from the same fork into the `0.29.x` branch?

**Comment by molinav** [comment]
@da-woods Sorry, you are right. I must have ended up with some corrupt environment while switching back and forth from Cython 3.0.0a10 to Cython 0.29.30 for testing. I was also surprised.

**Comment by molinav** [comment]
@da-woods Do you know if it is planned to have a release 3.0.0a11 soon? It would be great to be able to build abi3 wheels also on Windows with a Cython fetched from PyPI.

**Comment by da-woods** [comment]
I don't know. Doing a release is definitely outside what I know how to do/want to do. My impression is that we were possibly going to fix some if the typing/dataclasses first. But I'm not completely sure

**Pull request merged**
