### PR TITLE
use faster __Pyx_PyObject_GetAttrStr() implementation and avoid stati…

### PR DESCRIPTION
**Pull request by scoder**
…c Python string reference in AddTraceback() helper

### CODE REVIEW

**Comment by scoder** [comment]
Hmm, ok, I just noticed that this prevents the `AddTraceback()` helper from being added to the shared header files (`common_include_dir`). Not sure if this is acceptable...

**Comment by jdemeyer** [comment]
Would you agree to support something like
```C
static int __Pyx_CLineForTraceback(int c_line) {
#ifdef CYTHON_CLINE_IN_TRACEBACK
    if (CYTHON_CLINE_IN_TRACEBACK)
        return c_line;
    else
        return 0;
#else
    /* existing code */
#endif
}
```
for those who want `cline_in_traceback` to be a compile-time constant and who want to avoid the runtime stuff completely?

**Comment by scoder** [comment]
Happily so. I'll update my pull request.

**Comment by robertwb** [comment]
Can you confirm that the runtime overhead is still significant? (Or is there another reason a package author would want to enforce this on downstream dependencies?)

**Comment by scoder** [comment]
I think it's reasonable to allow explicitly and globally compiling out or in this feature. Note that this can be done via CFLAGS for a virtualenv or in an application setting. It's not only packagers who can make use of this.

**Comment by robertwb** [comment]
The downside is that folks will wonder why they can't turn the tracebacks on or off (and tracebacks often span multiple packages resulting in clines in only some of part of the traceback, which is why I made this a runtime parameter in the first place). Most users install pre-compiled binaries via pip or conda as well. I also don't want people to manually compile this in or out in the name of performance when if it really doesn't matter. (If performance is significantly different, or there's a no-performance reason to do this, that's different.)

**Comment by scoder** [comment]
I understand that argument. OTOH, if people install a package via pip, they probably don't care about C source lines, or even how that package is implemented in the first place. In that case it's really up to the package distributors to decide if they want to have it on, e.g. to get more information on bug reports (in which case they might really want to leave it as a runtime setting), or to switch it off completely in order to avoid confusing their users.

Note that users could always disable this feature in the past. We're just moving this from translation time to C compile time, while making the (absolutely reasonable) default a runtime setting.

Should we improve the documentation here to explain when people should care about the setting?

**Comment by jdemeyer** [comment]
> The downside is that folks will wonder why they can't turn the tracebacks on or off

As I said before, I don't understand the point of this "feature" in the first place. I think it never hurts to put non-intrusive additional information in a traceback. I haven't heard anybody ever complain about that (say, on the Cython or Sage mailing lists). And the C line number has helped me before to better understand a traceback (I'll keep an eye on this in the future, in which cases the C line number was genuinely useful: it might help you to produce better exceptions).

So, the way I see it, if we look at the costs and benefits of this "cline in traceback" feature:
- Benefits: None
- Costs: a 10% speed reduction, less useful tracebacks by default

**Comment by jdemeyer** [comment]
Let me also add that the target audience for the C line numbers might not be the users, but the developers of a package. If some user sends me a bug report, I want all the information that I can get. So, for every Cython package that I'm authoring, I would always want the C line numbers to be enabled.

**Pull request merged**
