### PR TITLE
Improve libcpp.unordered_map API

### PR DESCRIPTION
**Pull request by vallsv**
Hi.

This PR improve the API provided by `libcpp unordered_map`.

I only add `reserve` and `bucket_count` to the  API cause it was needed on my side. But there is other missing functions. Let me know if you prefer a patch with the exhaustive API.

### CODE REVIEW

**Comment by scoder** [comment]
Well, adding more than you strictly need at a given time would be nice towards a) the Cython project and b) others who want to use the features in the future.

**Comment by scoder** [comment]
Also note that tests would help to assure that this does not get broken by future changes. See the existing test files in `tests/run/` and start the test runner with `runtests.py cpp_stl`.

**Comment by scoder** [comment]
Any update? Would be nice to get this in.

**Comment by vallsv** [comment]
I have to work on it. This week or the next one.
But i will not have time to add unittests.

**Comment by scoder** [comment]
> But i will not have time to add unittests.

Interesting attitude. You expect _us_ to spend our time on maintaining the entire non-trivial tool that you use, but the maximum time that you are willing to spend on adding the features that _you_ need is the time to drop them on us in the least maintainable way.

**Comment by vallsv** [comment]
You kiding me? I expect nothing, I only propose a patch cause i think it could be useful for the community.
I anyway can't use the Cython master cause i have to use the version 0.21.1, then i have no interest in this merge. I inserted custom definitions on my own source files.

I don't have the infrastructure to test all the combination of compilators with C++98, C++11, C++16... plus my compilator which is supposed to support C++11, do not support all the signatures. Then i know it is a difficult task and i know i don't have the skill and the knowledge to do it. I am sorry, as most of people, I don't have an infinite amount of time, i just explain to you what i can do and when.

Thanks anyway for the merge.

**Pull request merged**
