### PR TITLE
Call fix

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This is a simplified version of the patch from the discussion at https://mail.python.org/pipermail/cython-devel/2015-February/004328.html along with a corresponding test case. I marked the first commit as from the original person who posted the patch on the mailing list.

### CODE REVIEW

**Comment by ulido** [comment]
Thanks for putting in a PR for this!

**Comment by insertinterestingnamehere** [comment]
Any news on this one?

**Comment by robertwb** [comment]
Thanks. I had to tweak it a bit to still allow overloading, but it should still work.

**Comment by insertinterestingnamehere** [comment]
@robertwb Fantastic, thanks! Would you like me to add some tests for that case?

**Comment by robertwb** [comment]
That'd be great.

**Comment by insertinterestingnamehere** [comment]
Okay, will do. I'll be away from my development machine for a few days, but I'll get a PR up for that early next week.

**Pull request merged**
