### PR TITLE
Fix named expression tests windows

### LINKED ISSUE #5172: [Bug] Fix Windows assignment expression tests
The assignment expression tests for syntax errors are run using `cython.compile`, and then the test output is matched against the desired test output. On Windows it doesn't seem to be capturing the test output so the comparison doesn't work.

On some of the Windows CI runs this is the only remaining failure, so it'd be good to have a proper look into it and then we could at least remove "allow-failures" from those particular runs.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes named expression tests on Windows (I forgot that Windows filenames could contain ":")

Turns off allowed_failures on as many of the windows builds as possible

Fixes #5172

### CODE REVIEW

**Comment by da-woods** [comment]
https://github.com/cython/cython/pull/5040#issuecomment-1356392033 - looks like there's still an issue with one C++ test

**Comment by da-woods** [comment]
Hmmm... we're down to "sometimes Cython itself fails to build with a link error, but it's inconsistent..."

**Comment by mattip** [comment]
The error is 
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1158

That error code seems to be 
```
ERROR_NO_MORE_USER_HANDLES

    1158 (0x486)

    The current process has used all of its system allowance
of handles for Window Manager objects.
```

That doesn't seem to make sense to me. Are you running a number of builds in parallel?

**Comment by da-woods** [comment]
There's some other options for what it means I think:
https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1158?view=msvc-170
https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158

It might be missing a needed executable on the path. But none of that is hugely clear why, why it's intermittent, or how we fix it on the CI

**Comment by da-woods** [comment]
To be honest, I could just remove the "require Windows to pass" part of this PR for the moment

**Comment by mattip** [comment]
There are two different errors code reporting systems. `LNK1158` can come from the linker, but that is not the error reported. The linker actually almost succeeds. It creates the   export lib, but then fails later on (creating the dll? closing files? finalizing something?) and exits with errno 1158 as an OS errorcode, not a linker error code.

**Comment by da-woods** [comment]
Fair enough - I'll defer to your judgement here @mattip.

I'm currently thinking "I'm don't know how to fix this, but it's easy to rerun individual CI runs if we're getting intermittent failures, so maybe we should just accept it as-is for now". And also "might be worth turning off parallel builds on Windows? It might help"

**Comment by mattip** [comment]
> And also "might be worth turning off parallel builds on Windows"

The windows and linux machines are [documented with 2 cores](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). I see the "Tests in shard 1/7" in the log output for linux but not windows, so maybe they are only run in one process?

It is frustrating to try to debug this kind of stuff.

**Comment by da-woods** [comment]
That's*probably* different to how setup.py is called I think.

https://github.com/cython/cython/blob/b2cad768499cf5763251fe757491e9fc24a1f583/Tools/ci-run.sh#L157

I might have a go at tweaking that if I get time

**Comment by da-woods** [comment]
The Windows tests still seem slightly fragile, but I think it's a net benefit to enable them as failures (so merging this)

**Pull request merged**
