### PR TITLE
Add code object to LambdaNode; fix for gen. expr.

### PR DESCRIPTION
**Pull request by naatje80**
Added code object to LambdaNode. This is an update for pull request  #4810. The code object was still failing when it was created for a generated expression. This is now skipped.

### CODE REVIEW

**Comment by da-woods** [comment]
At least one of the tests that's failing in lambda_T195 is:

```
    return f(1, lambda a, *args, **kwargs : ((a*10 + args[0])*10 + args[1])*10 + kwargs['b'])
```

The issue seems to be that the argument and keyword argument aren't added to `def_node.args`.

I suspect the place to fix it is when the `def_node` is created in ParseTreeTransforms `PostParse.visit_LambdaNode`. Although I could be wrong.

**Comment by naatje80** [comment]
I indeed received an email related to the failed checks verification. I need to verify how to fix this. Thank you for your suggestions.

**Comment by scoder** [comment]
It turns out that the code object needs to be created later, so that args and kwargs were added to the local variable list already. I moved it to `analyse_expressions()`, which seems to work better.

See https://github.com/cython/cython/pull/6144, specifically https://github.com/cython/cython/pull/6144/commits/a9a280e531988d0705573920b5cc9e3acc7aabb0

**Comment by scoder** [comment]
I reworked much of this in https://github.com/scoder/cython/commit/29039bcd5ead39b5afda3cfece2e7650b44e7e83, so I'll close this PR. Thanks for bringing it up.

**Pull request closed without merging**
