### PR TITLE
Don't remove const for reverse iteration

### PR DESCRIPTION
**Pull request by isuruf**
And use the same hack from forward iteration.

### CODE REVIEW

**Comment by da-woods** [comment]
I suspect you should change `multimap`, `unordered_map` and `unordered_multimap` too. But this is probably as good a way to do it as any

**Comment by isuruf** [comment]
Fixed `multimap`. There are no reverse iterators for `unordered_map` and `unordered_multimap`.

**Comment by da-woods** [comment]
Thanks. I think this is the more robust way of doing it than trying to correctly guess which consts to remove within Cython itself.

I'd like to leave this a few days, partly for more comments, and partly so I can have a more detailed think to try to avoid unintended consequences.

@garychia - since you wrote the code that this is removing, do you have any thoughts? Is there anything you're aware of that will break if we do this.

**Comment by isuruf** [comment]
Btw, I don't know if you noticed or not, this hack has been there for forward iteration for a long time and I don't think any issues have come up before.

**Comment by da-woods** [comment]
I did notice. I'm fairly happy with the hack - it actually doesn't seem too hacky to me. It's just saying "Cython should treat the return value as if it's the non-const type". To me that's fairly explicit and barely a hack.

The main thing I want to give a bit more thought is "was anything else enabled by `remove_const` that will now get broken (and be unfixable by using the same hack)?".

**Comment by garychia** [comment]
As far as I know, `remove_const` was only used for reversed iterators when I wrote the code. I'm happy with this solution as it makes the code simpler.

**Comment by da-woods** [comment]
Thanks for the confirmation. I haven't been able to think of any other significant problems so I'll go with this.

Thanks @isuruf

**Pull request merged**
