### PR TITLE
fix nullary constructor libcpp set/map 

### PR DESCRIPTION
**Pull request by fried**
fix for bug #4657

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Since you seem to have found this in previously working code, could you add a test, to make sure it keeps working in the future? There are test in `tests/run/cpp_stl_*.pyx`.

**Comment by da-woods** [comment]
In the interests of getting this merged I added some tests in https://github.com/cython/cython/commit/cb035e34955649c93bc1808e3fec854f498925db (which can hopefully be picked over to here)

**Comment by jjerphan** [comment]
Hi @fried, do you still have time to work on this PR?

If it's not the case, I am interested in pursuing your work.

**Comment by da-woods** [comment]
@jjerphan I think I'd already proposed a commit with the necessary tests, so i don't think there's anything to do.

**Comment by maxbachmann** [comment]
This is fixed in #4528 as well along with a couple of other issues of the current iterator implementation. However at least the test of @da-woods should be added.

**Comment by da-woods** [comment]
@maxbachmann feel free to just copy-paste my tests if you want - they aren't the sort of thing that needs credit preserving through git history or anything like that.

**Comment by da-woods** [comment]
Closing because it was fixed elsewhere (https://github.com/cython/cython/commit/169876872f3cb6198971a1db07e5b8a9d12b3dac) - thanks for submitting the PR anyway

**Pull request closed without merging**
