### PR TITLE
Complete min/max operations in libcpp.algorithms

### PR DESCRIPTION
**Pull request by n-elie**
Add min, max, minmax, min_element, max_element, minmax_element and clamp to libcpp.algorithms

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Could you please also add a bit of usage to the `cpp_*` tests to make sure the function declarations are working as they are?

**Comment by scoder** [comment]
Friendly ping. :)

**Comment by scoder** [comment]
re-ping :)

**Comment by n-elie** [comment]
I can't even run the tests:
```python runtests.py cpp_stl_algo_modifying_sequence_ops -vv```
[Ouput](https://github.com/cython/cython/files/6499269/test.txt)

**Comment by scoder** [comment]
Hmm. I've never seen this before. Are you running this from the base directory of a clean checkout of your branch? Or did you install Cython before running the tests? Maybe it's interfering with an installed Cython in your conda and picking up the `Includes` directory from there? Could you create a fresh and empty conda-env and try it with that?

**Comment by n-elie** [comment]
I tried with a fresh conda environment (list of installed package below) on Windows 7. I also tried it on Ubuntu 21.04 with the same results.
The procedure I followed is create a fresh conda environment, clone my branch and run the test script from the base directory.

```beniget                   0.3.0              pyh9f0ad1d_0    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
clang                     12.0.0               h57928b3_1    conda-forge
clang-12                  12.0.0          default_h5c34c98_1    conda-forge
clangxx                   12.0.0          default_h5c34c98_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
liblapack                 3.9.0                     9_mkl    conda-forge
mkl                       2021.2.0           hb70f87d_389    conda-forge
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
numpy                     1.20.2           py38h09042cb_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
python                    3.8.0                hc9e8b01_5    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pythran                   0.9.10           py38h43734a8_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h8ffe710_0    conda-forge
tbb                       2021.2.0             h2d74725_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge```

**Comment by scoder** [comment]
Maybe you can just add some tests blindly and let CI go over them?

**Comment by scoder** [comment]
Seems obsolete after #4448

**Pull request closed without merging**
