### PR TITLE
Remove ban on assignment to reference

### PR DESCRIPTION
**Pull request by da-woods**
Fixes https://github.com/cython/cython/issues/1863

### CODE REVIEW

**Comment by lorentzenchr** [comment]
@da-woods Thank you for this PR. This would be very nice to have.

**Comment by datdinhquok** [comment]
I'm converting Python types to C types and changing values of passed-by-ref params is a must, oh god, why is it not allowed in Cython?

**Comment by scoder** [comment]
Triggering a fresh CI build.

**Comment by scoder** [comment]
Ok, let's get this in, finally.

**Pull request merged**
