### PR TITLE
Drop Python 3.7, require Python 3.8+

### PR DESCRIPTION
**Pull request by EwoutH**
Python 3.7 is over a year end-of-life (June 27th 2023), so it might be a good time to start requiring Python 3.8 for future Cython version. It allows cleaning up significant parts of the codebase and CI configurations.

Of course this doesn't affect already released versions or the 3.0.x maintenance branch, and will only have effect on Cython 3.1 and higher.

### CODE REVIEW

**Comment by da-woods** [comment]
I think we did discuss this when picking the targets for Cython 3.1, and although it was EOL it seemed to have relatively high usage, so was worthwhile to keep. Personally I'd be inclined to stick with this decision for Cython 3.1, but probably drop it for Cython 3.2.

There's definitely some ugly vectorcall compatibility code that it'd be good to lose with Python 3.7. (Although in principle we could drop that without dropping Python 3.7 entirely).

For the moment, I think I'd like to leave the minimum limited API version as 3.7 too.

**Comment by EwoutH** [comment]
Sounds good, I will leave this open to be merged after the 3.1 branch cutoff.

**Comment by jakirkham** [comment]
FWIW Python 3.8 just went EOL

ref: https://devguide.python.org/versions/

**Comment by scoder** [comment]
I looked up the Python versions in RHEL and it apparently uses Py3.6 (RHEL-8) and Py3.8 (RHEL-9) by default.
https://access.redhat.com/support/policy/updates/errata/

Ubuntu 20.04-LTS uses Py3.8 as well.
https://packages.ubuntu.com/focal/python3

Debian Buster had Python 3.7 but became EOL this summer.
https://wiki.debian.org/LTS

Thus, I don't see much value left in keeping up support for Py3.7 in Cython 3.1.
Opinions?

**Comment by da-woods** [comment]
My view would be:

I don't see a huge value in keeping it/testing it/building wheel for it.

Assuming 3.1 is fairly close (which I hope it is), I wouldn't go beyond this PR - I wouldn't start actively stripping out 3.7 code.

**Comment by scoder** [comment]
> I wouldn't start actively stripping out 3.7 code.

That would mean less value for us. The only advantage is slightly lower CI turnover times (and a few minutes really won't matter), but we'd still have the Py3.7 code in our code base. For stability reasons, I'd then also keep the code in for the lifetime of Cython 3.1 and only remove it for 3.2.

If we decide to remove support in 3.1, then I'd rather also remove the corresponding Py3.7 code. If we stop testing it even before the release, we'll probably break it within a few maintenance releases without noticing, but without getting it out of our way.

**Comment by da-woods** [comment]
I don't care too much (I've got no great attachment to 3.7). And I'm definitely not arguing for "remove explicit Python 3.7 support but hope it keeps working".  I'm just a bit sceptical of a large change touching little bits of pretty much everything when 3.1 hopefully isn't too far away.

The only 3.7 code that I think is particularly nasty and it'd be nice to get rid of is `PyFunctionFastCall` and `CYTHON_BACKPORT_VECTORCALL`. Most of the rest doesn't feel like a huge maintenance burden.

------------------------------------------------------------------------------------------------------------

There's also a question if: "minimum supported limited API version" wants to diverge from "minimum support version".  In principle it could. I think we'd regret trying to do this though so it probably isn't worth real consideration.

**Comment by scoder** [comment]
Let's do this for Cython 3.1 already.

**Pull request merged**
