### PR TITLE
Fixed assorted crashes with fused types

### PR DESCRIPTION
**Pull request by da-woods**
Fixes https://github.com/cython/cython/issues/3820 (and probably some other bugs too)

Originally part of https://github.com/cython/cython/pull/3845.

-----------

It's pretty hard to test if a fused type specializes expect by doing it. For example, the specialization may go through a chain of const and pointer types. The I've changed the exception that this produces to make it more identifiable (rather than a generic Python KeyError). I've applied this to `cdef fused_type var`, `var: fused_type = something` and `sizeof(fused_type)` as well as a fused return type. All of these previously caused compiler crashes.

### CODE REVIEW

**Review by scoder — COMMENTED** [review]
I don't think this is a good idea. On the one hand, it's great and explicit to raise these errors in the right spots.
On the other hand, this is C/Go-ish error handling, which is annoying and easy to get wrong by forgetting to check for the error after calling `.specialise()`. I looked through a couple of the recursive usages and the usual pattern is "call specialise(), check if the result changed, if so, create a new type for it". For the `error_type`, the result did change, but not in the expected way.

If an exception is what you want almost all of the time, then an exception might simply be the right interface.

**Comment by da-woods** [comment]
> I don't think this is a good idea. On the one hand, it's great and explicit to raise these errors in the right spots.
> On the other hand, this is C/Go-ish error handling, which is annoying and easy to get wrong by forgetting to check for the error after calling `.specialise()`. I looked through a couple of the recursive usages and the usual pattern is "call specialise(), check if the result changed, if so, create a new type for it". For the `error_type`, the result did change, but not in the expected way.
> 
> If an exception is what you want almost all of the time, then an exception might simply be the right interface.

Fair enough. The options seem to be:

1. Have `specialize` raise an exception if if it fails. It might be worth making this a `TypeSpecializationException` rather than a `KeyError` just to be a bit more specific about exactly what's being caught.

2. Have `specialize` call `error` when it fails (this'd involve changing the interface to have a `pos` argument) and then returning `self` (or possibly `error_type`). The error messages would probably be less informative since it'd have to be a generic "type couldn't be specialized" error, but there wouldn't need to check return types.

3. Have specialize return `self` when it fails and check against that. (Although this is little better than `error_type`).

4. Add a `can_specialize` function (that in practice works by calling `specialize` and wrapping whatever error handling there is).

It sounds like 1 is probably the best option.

**Comment by scoder** [comment]
Yes, I agree that 1) sounds best, and double-yes for a better exception name. `TypeSpecializationException` is fairly long and takes a while to decypher. What about `TypeUnknown` or `CannotSpecialize` ? Something that reads well after `except`. :)

**Comment by scoder** [comment]
Yeah, I think that's helpful. Thanks!

**Pull request merged**
