### PR TITLE
Simplify slice handling in Pythran

### PR DESCRIPTION
**Pull request by serge-sans-paille**
And make it more flexible in terms of API change.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@scoder this commit is backward compatible with current and former pythran version, and forward compatible with upcoming version.

**Comment by scoder** [comment]
Thanks. So, this is probably something that could be backported to a 0.29.x release, right?

**Comment by scoder** [comment]
Cherry-picked as a275799a872651864a015937a6641901ecca2257

**Comment by serge-sans-paille** [comment]
yes!

**Pull request merged**
