### PR TITLE
Backport fixes for PyPy (GH-5429)

### PR DESCRIPTION
**Pull request by mattip**
Backported from #5429

- Use `_PyEval_GetAsyncGenFinalizer`, `_PyEval_GetAsyncGenFirstiter` on PyPy instead of probing inside the `PyThreadState` struct

- Require a nightly PyPy build for Py3.9 to support async iteration and finalisation.

- Avoid `PyIter_Next()` and call `tp_iternext()` instead where possible because `PyIter_Next()` swallows `StopIteration` exceptions and thus looses the return value.

See https://foss.heptapod.net/pypy/pypy/-/issues/3280
See https://foss.heptapod.net/pypy/pypy/-/issues/3935

### CODE REVIEW

**Comment by mattip** [comment]
It seems [skbuild is failing on macOS 2.7](https://github.com/cython/cython/actions/runs/5167651449/jobs/9308674993#step:5:127). 
```
File "<path>/python2.7/site-packages/skbuild/constants.py", line 41, in _default_skbuild_plat_name
       major_macos, minor_macos = release.split(".")[:2]
   ValueError: need more than 1 value to unpack
```

This is the old scikit-build as required by [line-profiler v3.1.0](https://github.com/pyutils/line_profiler) (which tag? hmm, maybe the [fix_310_wheel](https://github.com/pyutils/line_profiler/tree/dev/fix_310_wheel) branch), which is the last version to support python2.7, in its [requirements/build.txt](https://github.com/pyutils/line_profiler/blob/dev/fix_310_wheel/requirements/build.txt) and not the newer scikit-build-core.

They [released 4 days ago](https://github.com/scikit-build/scikit-build), maybe something is broken? But when I look at [that file](https://github.com/scikit-build/scikit-build/blob/4eef05f0e45746ff1a715c014793d049a66d70b3/skbuild/constants.py#L41) line 41 is different and this code appears on line 66.  @henryiii any thoughts?

**Comment by henryiii** [comment]
It's also an old scikit-build, 0.15, as 0.16 and 0.17 don't support 2.7.

How does release not have a .? macOS should always report at least the minor version.

**Comment by henryiii** [comment]
There's no line profiler with that number on PyPI. I think they deleted that release? I'm going to guess it never had wheels. Maybe try again?

I can release fixed to 0.15 if I know that needs fixing.

**Comment by mattip** [comment]
> There's no line profiler with that number on PyPI

I see line-proviler 3.1.0 [here](https://pypi.org/project/line-profiler/3.1.0/). It has wheels only for manylinux1 and manylinux2010.

But back to the problem at hand: at scikit-build version 1.5, [consts.py:41](https://github.com/scikit-build/scikit-build/blob/06c57c7019e8aff5f781afb2639d6be5594aadb0/skbuild/constants.py#LL40C31-L40C55) has this code:
```
release = os.environ.get("MACOSX_DEPLOYMENT_TARGET", release)
```

And indeed, in the [CI actions file](https://github.com/cython/cython/blob/54b92e3d4f75225c55609076afd2d901be8326d2/.github/workflows/ci.yml#L126), there is
```
MACOSX_DEPLOYMENT_TARGET: "11"
```

On [master](https://github.com/cython/cython/blob/8892b021a3ceee623abccc0bfe1c705952c125f1/.github/workflows/ci.yml#L220) it is "10.15"

**Comment by mattip** [comment]
This was changed in https://github.com/cython/cython/commit/ba82c22200d6f72f6e05e2ebebc39727892c4f09 for both 3.0.0b3 and 0.29.x. I will try 11.0

**Comment by mattip** [comment]
CI is passing now (there are some timeouts after 40 minutes).

**Comment by henryiii** [comment]
I think we should probably allow settings like "11", I think that's supported when compiling; from (rather old) macOS source code, it looks like default values were injected if they were missing.

Not sure why 11 is being targeted, though, 10.14 is enough for full C++ support, otherwise 10.9 or 10.10 is fine. Seeing it set to 11 when moving to macOS 11 looks suspicious.

**Comment by scoder** [comment]
I used target 11 (ok, probably should have used 11.0) to support Arm64. Isn't that needed?

**Comment by henryiii** [comment]
Oh, is it only setting 11 targeting ARM? Yes, 11 is the first supporting ARM, though IIRC it ignores a lower setting so that you can make Universal binaries that support 10.x too. Could be wrong there, but I know we don't have built in fuse support for cibuildwheel yet, so it has support something like this.

Is this distributing binaries or just for testing?

**Comment by scoder** [comment]
This is in the CI workflow, not the wheel build. The macOS CI build in 0.29.x has generally been unhappy for a while now, but 0.29.x is in boring legacy maintenance mode, so the macOS build setup isn't hugely important any more (to me, that is). If it's easy to fix, fine. If not, that's probably fine, too.

**Comment by henryiii** [comment]
"11.0" should be just fine then. I'll see if I can match the behavior for single digit values better (more permissive or better error message, whichever is closer).

**Comment by mattip** [comment]
> "11.0" should be just fine then. 

Cool. That is what I did in this PR.

**Comment by mattip** [comment]
Does this need anything more?

**Comment by da-woods** [comment]
Thank @mattip

**Pull request merged**
