### PR TITLE
Allow slicing of C arrays without GIL

### LINKED ISSUE #1662: Cannot copy C arrays in nogil functions
This code:

```
cdef void foo() nogil:
    cdef double[16] x
    cdef double[16] y
    y[:] = x[:]
    y = x
```

throws the compile time error "Slicing Python object not allowed without gil" for both assignments. However, the generated code in both cases is a simple memcpy and doesn't require the GIL.

### PR DESCRIPTION
**Pull request by c-f-h**
Fixes #1662.

### CODE REVIEW

**Comment by robertwb** [comment]
Thanks. Don't we need to check the index-calculating code for no-gil compliance as well?

**Comment by scoder** [comment]
Yes, we do, which also shows that there are clearly tests missing for this use case.

**Comment by c-f-h** [comment]
@robertwb Sorry, I'm not too familiar with the Cython codebase yet, but I thought the gil-checking pipeline stage would automatically visit all child nodes and check those for no-gil compliance automatically?

I guess you are thinking about the case where the slice is not `:`, but something which depends on Python objects?

**Comment by c-f-h** [comment]
For now, I added the original bug report as a "compile" test. Please advice on what further tests to add.

**Comment by robertwb** [comment]
Yes, I was thinking of where one did something like `y[py_obj:] = x`. This is actually checked.

**Comment by robertwb** [comment]
However, I had to unmerge this, as I just noticed that the size check is raises an exception and which cannot be done without the GIL. For example, in your test x and y could be declared as arrays of different size. (Possibly with some sophistication we could recognize the case of constant, equal sizes.)

**Comment by c-f-h** [comment]
Ah, I see. Isn't it possible to reacquire the GIL in case of an error?

**Comment by robertwb** [comment]
But we wouldn't be able to propagate it without the error. Perhaps we could disable this check with boundscheck(False) though.

**Comment by c-f-h** [comment]
> However, I had to unmerge this, as I just noticed that the size check is raises an exception and which cannot be done without the GIL. For example, in your test x and y could be declared as arrays of different size. (Possibly with some sophistication we could recognize the case of constant, equal sizes.)

Sadly this is still not merged because of this issue. I discovered another case where an error is silently ignored: while passing a buffer from a `nogil` into another `nogil` function where the buffer does not satisfy the requirements (e.g., C- or F-contiguity). Again, there seems to be no way to propagate this error as a Python exception object.

So it seems there are simply cases where it's not possible to generate Python exceptions (C++ exceptions are out of the question since Cython does not require C++). Maybe a lower-level error reporting method should be used in those cases? Like writing to stderr and calling the C function `abort()`.

**Comment by da-woods** [comment]
This may have changed since whenever this PR, but I think it is possible to raise and propagate exceptions from the nogil blocks and functions. For example

```
cdef int f() nogil except -1:
    raise RuntimeError("Hello")

def test():
    with nogil:
        i = f()
    print(i)
```

running `test()` will report the expected exception (and of course re-acquire the GIL to raise it).

(If I remove the `except -1` then I get `Exception ignored in: 'nogilprop.f'` which is again expected Cython behaviour)

----------

It might be worth revisiting this PR with this in mind? And @c-f-h - can you check if your buffer example is still a bug with `except` set (and if so report the bug!)?

**Comment by scoder** [comment]
> this PR would definitely need more checks including failure cases.

Yes, definitely. It's not the error raising that blocks this PR but the lack of test coverage, which does not even expose the (problematic?) error raising. A compile test really is not enough.

Instead, I suggest creating a new test file `tests/run/carray_slicing_nogil.pyx` and collecting runnable tests there that do actual slicing of arrays under `nogil` conditions, including runtime error cases, as well as adding compile time error tests to the `tests/errors/e_arrayassign.pyx` test file.

**Comment by c-f-h** [comment]
> It's not the error raising that blocks this PR but the lack of test coverage

That wasn't clear to me. I read the earlier comment as the error raising being the blocker:

> However, I had to unmerge this, as I just noticed that the size check is raises an exception and which cannot be done without the GIL.

I don't have the capacity right now to research how to write tests which check for particular error conditions (I can barely figure out the test runner as it is). I would be grateful if a core maintainer could step in here.

**Comment by scoder** [comment]
> I can barely figure out the test runner as it is

Does the documentation help?
https://github.com/cython/cython/blob/master/docs/CONTRIBUTING.rst
Specifically:
https://github.com/cython/cython/wiki/HackerGuide#the-test-suite

**Pull request merged**
