### PR TITLE
Port pyximport to importlib machinery

### LINKED ISSUE #4560: [BUG] pyximport uses deprecated "imp" module
Replace it with `importlib` or whatever seems appropriate and modern.

### PR DESCRIPTION
**Pull request by matusvalo**
pyximport is splited into python3 (importlib) and python2 (imp) implementations.

Fixes #4560

### CODE REVIEW

**Comment by matusvalo** [comment]
Created based on comments in #4612

**Comment by scoder** [comment]
Still looks like the git history was lost for the two copied files. `git blame` tells me that they are all new.

**Comment by scoder** [comment]
This supposedly works: https://stackoverflow.com/a/46484848

**Comment by da-woods** [comment]
This feels like the git history is likely to get mangled when the commit is squashed anyway.

Would it be easier to duplicate the files now in the master branch, and then rebase this PR on that?

**Comment by matusvalo** [comment]
> This supposedly works: https://stackoverflow.com/a/46484848

Implemented in #4625

**Pull request closed without merging**
