### PR TITLE
Rewrite the C property feature

### PR DESCRIPTION
**Pull request by scoder**
Rewrites #2640 and #3095 based on `inline` methods.

### CODE REVIEW

**Comment by mattip** [comment]
This is much nicer than the code in the previous PRs. Perhaps this is a chance to enhance some of the [design documents](https://github.com/cython/cython/wiki/HackerGuide#how-to-add-a-new-attribute-to-an-ast-node) to describe what goes into adding a new Node type?

**Comment by scoder** [comment]
> what goes into adding a new Node type

I think most of that is still accurately documented in the comments of the `Node` class. I think the issue is more to know what a node should do and what compiler stages it needs to interact with (and possibly also in which it would best originate). And that is _inherently_ node specific.

**Comment by mattip** [comment]
Is there a description of what is expected from each compiler stage somewhere? For instance searching for [`analyse_declarations`](https://github.com/cython/cython/search?q=analyse_declarations&unscoped_q=analyse_declarations) does not help me understand what it is meant to do. I seem to remember a document describing the compiler pipeline somewhere but cannot find it now.

**Comment by scoder** [comment]
Wrong place to discuss this, but you might have meant this document:
https://web.archive.org/web/20170511222231/https://wstein.org/wiki/attachments/2008(2f)sageseminar(2f)kantor/slides.pdf
(Linked from the [HackerGuide](https://github.com/cython/cython/wiki/HackerGuide#getting-started).)

Does [this](https://github.com/cython/cython/blob/5e846d51b0066b0d7bd3eb45c18e576c9fc18cc9/Cython/Compiler/Nodes.py#L211-L230) help regarding `analyse_declarations`?

**Pull request merged**
