### PR TITLE
Fix memoryview memory leak

### PR DESCRIPTION
**Pull request by stefanmh**
See https://github.com/cython/cython/issues/1638

### CODE REVIEW

**Comment by scoder** [comment]
Sorry if I'm a suspicious about this fix, but `PyBuffer_Release()` in CPython does this:
```
void PyBuffer_Release(Py_buffer *view)
{
    PyObject *obj = view->obj;
    PyBufferProcs *pb;
    if (obj == NULL)
        return;
    pb = Py_TYPE(obj)->tp_as_buffer;
    if (pb && pb->bf_releasebuffer)
        pb->bf_releasebuffer(obj, view);
    view->obj = NULL;
    Py_DECREF(obj);
}
```
Note the `Py_DECREF(obj)` at the end. I'd like to avoid replacing a memory leak with a reference leak here, even if it's only about `None`.

**Comment by scoder** [comment]
But thanks for pointing me at the right spot to keep searching. I'll commit a fix shortly.

**Comment by stefanmh** [comment]
I'm not sure `PyBuffer_Release` gets called, though

**Comment by scoder** [comment]
In Py3, yes. In Py2, Cython has its own implementation, which is where the bug was actually hiding.

**Pull request closed without merging**
