### PR TITLE
Further Assignment Operator Fixes

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Somehow I missed this in https://github.com/cython/cython/pull/399. This allows assignment from a different type if the corresponding operator= is available.

### CODE REVIEW

**Comment by scoder** [comment]
This change seems too broad to me. Coercion doesn't only happen on assignment, so applying this in `coerce_to()` could lead to allowing invalid coercions. One example where the "=" operator is not involved would be function argument passing.

I think this needs to go somewhere into the assignment nodes.

**Comment by insertinterestingnamehere** [comment]
Hmmm. Yes, that makes sense. I'll take a look at the code for the assignment nodes and see if I can avoid calling the coercion method in the assignment nodes. This issue appears to apply to single, cascaded, and parallel assignment. Is that a more sensible course of action?

**Comment by insertinterestingnamehere** [comment]
@scoder Okay, I've pushed a more restricted solution. Fixes for cascaded assignment pending.

**Comment by insertinterestingnamehere** [comment]
Okay, cascaded assignment is working too. I ended up having to add an extra keyword argument to the generate_assignment_code methods of ExprNode subclasses to properly trigger an assignment that takes place without a typecast.

**Comment by insertinterestingnamehere** [comment]
This one is finished. It would be nice to get it in some time soon so I can get exception handling for overloaded assignments working in https://github.com/cython/cython/pull/408.

**Comment by scoder** [comment]
Thanks!

**Pull request merged**
