### PR TITLE
Replace old build_ext with new cythonize(...) version.

### PR DESCRIPTION
**Pull request by robertwb**
Rather than redirect everyone to the one in Cython.Build, simply upgrade the Cython.Distutils version. In particular, this is the version picked up by setuptools. 

Notably, however, the new one takes far fewer options (this configuration primarily moved into in-file directives). The old one is kept as Cython.Distutils.old_build_ext to ease migration; we should consider which, if any, additional options should be moved to the new one.

### CODE REVIEW

**Comment by scoder** [comment]
We'll need an extended test cycle for the 0.25 release anyway, so let's get this in and fix it in master.

**Comment by jdemeyer** [comment]
This breaks https://github.com/zeromq/pyzmq

**Comment by jdemeyer** [comment]
In order for this to be a viable replacement to `cythonize()`, it should support passing keywords to `cythonize`. For example, Sage passes the keywords `nthreads`, `build_dir`, `force`, `aliases`, `compiler_directives`.

**Comment by robertwb** [comment]
I agree that this is not a replacement for calling a customized `cythonize()`, but should be a step forward. For better or for worse, the distutils way to customize thing is to subclass (e.g. to specifying the build_ext, it expects a class, not an instance).

**Comment by robertwb** [comment]
And I'd want to think long and hard about what command line options to add, given that they're even harder to change.

**Comment by jdemeyer** [comment]
> I agree that this is not a replacement for calling a customized cythonize(), but should be a step forward.

And it serves as nice "documentation" on how to customize the `build_ext` command.

**Comment by messense** [comment]
breaks pyyaml. See #1498

**Pull request merged**
