### PR TITLE
Enable "binding" directive by default

### PR DESCRIPTION
**Pull request by scoder**
Closes GH-2564 (eventually).

Failing tests to investigate and fix:

- [x] `quickstart`: `cpdef` `CyFunction` does not support `nogil`
- [x] `embedsignatures`: incorrect re-analysis of coercion nodes in default arguments
- [x] `bufaccess`: ?
- [x] `memslice`: reference counting of arguments differs
- [x] `memoryview`: reference counting of arguments differs
- [x] `w_undeclared`: incorrect warning about implicit declaration of `__reduce_cython__`
- [ ] `pstats_profile_test`: `cpdef` wrapper is not profiled
- [x] `cdef_multiple_inheritance`: crash, `def/cpdef` methods are added before the class is created
- [x] `cdef_multiple_inheritance_nodict`: crash (probably same reason as above)
- [x] `staticmethod`: `TypeError` on call
- [ ] #1658

These failures most likely hint at real problems and not just wrong tests.

### CODE REVIEW

**Comment by jdemeyer** [comment]
See also #1658 for one more binding bug.

**Comment by mattip** [comment]
I would like to take a shot at helping move this forward, it would be nice to get 3.0 released. Where would be an easy place to start?

**Comment by jdemeyer** [comment]
@scoder: could you rebase the branch to latest master to see the latest Travis CI results?

**Comment by scoder** [comment]
@mattip
- The reference counting failures are probably best fixed in the tests, not in the code for now. 
- `w_undeclared` is a know bug, I think (but I can't find the ticket right now). That's not critical for this feature and could possibly be worked around somehow.
- The crashes need a bit of investigation, they might not be difficult to fix. Maybe just code generation issues.
- `staticmethod` – see if that's fixed after the rebase.
- The profiling failure could just be a missing profiling setup in the generated Python wrapper function, but I can't say what else is missing there.

Generally, any further investigation on the failing tests might help.

**Comment by mattip** [comment]
The `cdef_multiple_inheritance` test is causing a segfault.

<details>

`__pyx_ptype_25cdef_multiple_inheritance_Both` is NULL in this fragment

```
  /* "cdef_multiple_inheritance.pyx":30
 *     cdef c_method(self):
 *         return "Both"
 *     cpdef cp_method(self):             # <<<<<<<<<<<<<<
 *         return "Both"
 *     def call_c_method(self):
 */
  /* __pyx_t_1 allocated (Python object) */
  __pyx_t_1 = __Pyx_CyFunction_NewEx(&__pyx_mdef_25cdef_multiple_inheritance_4Both_1cp_method, __Pyx_CYFUNCTION_CCLASS, __pyx_n_s_Both_cp_method, NULL, __pyx_n_s_cdef_multiple_inheritance, __pyx_d, ((PyObject *)__pyx_codeobj__11)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 30, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  if (PyDict_SetItem((PyObject *)__pyx_ptype_25cdef_multiple_inheritance_Both->tp_dict, __pyx_n_s_cp_method, __pyx_t_1) < 0) __PYX_ERR(0, 30, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  /* __pyx_t_1 released */
  PyType_Modified(__pyx_ptype_25cdef_multiple_inheritance_Both);
```

**Comment by mattip** [comment]
The failing tests (after scoder/cython#1 to fix the refcount changes):

[ ] - `cdef_multiple_inheritance` and `cdef_multiple_inheritance_nodict` segfault
[ ] - `test_cython3_pgo` has a gcc compilation error
[ ] - `w_undeclared` has extra warnings about implicit declaration of `__reduce_cython__` and `__setstate_cython__`. I couldn't find any issue or PR relating to that.
[ ] - `extstarargs.Silly` fails doctests where `test_no_copy_args` returns `False`
[ ] - `pstats_profile_test` fails, see gh-3138
[ ] - `bufaccess`, `embedsignatures` cause a crash in `AnalyseExpressionsTransform`

Some of these may be connected?

**Comment by da-woods** [comment]
I think I've got to the bottom of `staticmethod` - see https://github.com/cython/cython/pull/3159. enable binding correctly reproduces Python behaviour and it was just the test that was wrong. I've updated the tests so that they demonstrate that.

**Comment by mattip** [comment]
The crash in `cdef_multiple_inheritance` seems to be due to a lack of calling `__Pyx_Py3ClassCreate` for the multiple-inheritance [`Base`](https://github.com/cython/cython/blob/0.29.13/tests/run/cdef_multiple_inheritance.pyx#L12) class (comparing the code to the single-inheritance [`PyBase`](https://github.com/cython/cython/blob/0.29.13/tests/run/cdef_multiple_inheritance.pyx#L8) class).

**Comment by mattip** [comment]
I think the crash has to do with a change in the method assignment. In the old version, the code 
```
cdef class Both(CBase, PyBase):
    cdef dict __dict__
    cdef c_method(self):
        return "Both"
    cpdef cp_method(self):
        return "Both"
    def call_c_method(self):
        return self.c_method()
```

would assign `cp_method` and `call_c_method` to a `PyMethodDef` struct. In the new code only `call_c_method` is assigned in the `PyMethodDef` struct, but both are assigned to the `__pyx_ptype...Both->tp_dict` inside `__Pyx_Init_Globals` which happens while `__pyx_ptype...Both` is still NULL. The assignment `__pyx_ptype...Both = &__pyx_type...Both` happens in the next fragment, a few lines down.
This diff
```
diff --git a/Cython/Compiler/Nodes.py b/Cython/Compiler/Nodes.py
index 677044f3c..07c05d726 100644
--- a/Cython/Compiler/Nodes.py
+++ b/Cython/Compiler/Nodes.py
@@ -5070,8 +5070,6 @@ class CClassDefNode(ClassDefNode):
         # This is needed to generate evaluation code for
         # default values of method arguments.
         code.mark_pos(self.pos)
-        if self.body:
-            self.body.generate_execution_code(code)
         if not self.entry.type.early_init:
             if self.type_init_args:
                 self.type_init_args.generate_evaluation_code(code)
@@ -5099,6 +5097,8 @@ class CClassDefNode(ClassDefNode):
                 self.type_init_args.free_temps(code)
 
             self.generate_type_ready_code(self.entry, code, True)
+        if self.body:
+            self.body.generate_execution_code(code)
 
     # Also called from ModuleNode for early init types.
     @staticmethod

```
reorders the fragments so that `__pyx_type...Both` is set up before the method assignments and does not seem to cause any new test failures. Should I issue a PR? Against master or scoder/gh2564_enable_binding?

**Comment by da-woods** [comment]
> Against master or scoder/gh2564_enable_binding?

@mattip I've been making pull requests for this on cython/gh2564_enable_binding - I'd guess it's better to keep the history under the main repository. I'm not claiming this is the only right answer but it makes sense to me...

**Comment by mattip** [comment]
Could someone update this from master so we can see what still needs fixing?

**Comment by mattip** [comment]
It would be nice to review/merge  gh-3163, gh-3164 and rebase/merge with master to see what else needs doing here

**Comment by da-woods** [comment]
For whenever is next looked at: a reminder that https://github.com/cython/cython/commit/3dc2b9dfc23638fbef2558d619709b5235d5df08 (now in master) should fix the `embedsignatures` test so should be merged into this branch.

**Comment by mattip** [comment]
This could use a rebase off master so we can see what is still missing

**Comment by da-woods** [comment]
The failures of `extstarargs` look to have been introduced by https://github.com/cython/cython/pull/3086, and I think are unavoidable since PyCFunction messes around with the arguments tuple to pass it with self, then to separate self and the rest (this is also the source of the reference counting changes) https://github.com/cython/cython/blob/c75ed142e54351596a6de2359295730c5fab5ec6/Cython/Utility/CythonFunction.c#L679 I'd probably add `binding=False` to those specific tests.

I'm a bit puzzled by the failure of one of the `bufaccess` reference counting tests in Python 3.8, but don't have Python 3.8 right now so can't easily look into what's changed.

**Comment by da-woods** [comment]
@scoder Since you were updating the list of broken tests in this issue: I'm pretty sure I fixed "embedsignatures" in https://github.com/cython/cython/pull/3284 and MattiP fixed "cdef_mutliple_inheritance" and "cdef_mutliple_inheritance_nodict" in https://github.com/cython/cython/pull/3166.

**Comment by mattip** [comment]
Ping. This is green, does that mean it is done?

**Comment by da-woods** [comment]
@mattip Don't think so - I think all the issues that are currently tested for are fixed, but there's a couple of known issues that aren't tested yet.

Don't think https://github.com/cython/cython/issues/1658 is currently tested for.
I think https://github.com/cython/cython/pull/3138 adds some specific tests (I'm not sure exactly what the status of that).

**Comment by scoder** [comment]
I think, the fact that the tests are currently green, and the intention to make this a major part of the Cython 3.0 release, justify a merge at this point.

What do you think?

**Comment by mattip** [comment]
if you were asking me, I think it is mergable. There may still be more to do, but merging it will hopefully enable flushing out the corner cases before the release

**Comment by da-woods** [comment]
I think I agree with @mattip. If things break then users can always use `@binding(False)` until it's fixed so they're no worse than what they were.

**Comment by mattip** [comment]
tests are green again

**Pull request merged**
