### PR TITLE
Don’t crash when a C class isn’t defined in the pxd

### PR DESCRIPTION
**Pull request by linkmauve**
Fixes #279.

### CODE REVIEW

**Comment by robertwb** [comment]
Tests seem to be failing.

**Comment by linkmauve** [comment]
Fixed, sorry for the delay.
I also added an error test.

**Comment by robertwb** [comment]
I agree the error could be clearer, but it seems that declaring but not defining the class in a pxd would lead to other issues (e.g. if it's cimported elsehwere). Is there a good usecase for this?

**Comment by robertwb** [comment]
For some reason I missed that it turns a crash into an error. Thanks.

**Comment by linkmauve** [comment]
You should also close the bug report: http://trac.cython.org/ticket/279

Or are you waiting for that commit to make it into a stable release?

**Pull request merged**
