### PR TITLE
Use NULL as default exception value for ptrs

### LINKED ISSUE #5592: [ENH] Functions returning pointers does not propagate exception via NULL pointer by default
### Is your feature request related to a problem? Please describe.

In the cython3 we have changed the default logic to propagate exceptions by default. Consider following code:

```cython
from libc.stdlib cimport malloc

cdef void *safe_alloc(size_t size):
    mem =  malloc(size)
    if mem is NULL:
        raise MemoryError
    return mem

def main():
    cdef void *mem = NULL
    try:
        mem = safe_alloc(5)
    except MemoryError:
        print('Allocation of the memory failed.')
```

Calling `safe_alloc()` is by default causing calling `PyErr_Occurred()` after every call - see generated C code:
```c
__pyx_t_4 = __pyx_f_9exception_safe_alloc(5); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 12, __pyx_L3_error)
```
This can be dangerous when used together with `nogil` keyword - see notes in [1]

### Describe the solution you'd like.

To avoid unnecessary overhead we can propagate the exception via `NULL` value (same as `except? NULL`) when the function returns the pointer - the same is done when python object is returned - see notes in [1].

### Describe alternatives you've considered.

We can leave it as it is but I think it is unnecessary complication for the users.

### Additional context

[1] https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values

### PR DESCRIPTION
**Pull request by da-woods**
And add tests.

Fixes #5592

### CODE REVIEW

**Review by matusvalo — APPROVED** [review]
LGTM for me

**Comment by matusvalo** [comment]
Maybe one point. I think we should update the documentation but this can be done in separate PR I think.

**Comment by da-woods** [comment]
> Maybe one point. I think we should update the documentation but this can be done in separate PR I think.

Do you have a view on where in the documentation? I couldn't find this documented anywhere even for ints?

I think we should have this documented, but it's the kind of implementation detail I'd rather hide a little to avoid overwhelming users. `except? NULL` vs `except *` is really just an optimization and they could treat it as `except *`.

**Comment by da-woods** [comment]
> Is that correct?

Yes.

I hadn't considered the "what does a Cython 3.0.0 function return" issue, but it is 0 (as the "default_value").

I had considered the narrowing of the exception specification from `except *` to `except NULL` which as you say is just an optimization.

**Comment by matusvalo** [comment]
> Do you have a view on where in the documentation? I couldn't find this documented anywhere even for ints?

This is partially documented/mentioned in final notes of error return values [1]:
> cdef functions that are not extern are implicitly declared with a suitable exception specification for the return type (e.g. except * or @cython.exceptval(check=True) for a void return type, except? -1 or @cython.exceptval(-1, check=True) for an int return type).

> You don’t need to (and shouldn’t) declare exception values for functions which return Python objects. Remember that a function with no declared return type implicitly returns a Python object. (Exceptions on such functions are implicitly propagated by returning NULL.)

But having another thought about it, I think that if we want to have it documented we should rewrite documentation (e.g. put it in some kind of table etc...) in separate PR.

[1] https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values

**Pull request merged**
