### PR TITLE
Partial #3354 - build manylinux2010

### PR DESCRIPTION
**Pull request by penguinolog**
Use `manylinx2010` images to build `manylinux1` and `manylinux2010` at the same time.

### CODE REVIEW

**Comment by McSinyx** [comment]
Just curius, how is that possible with such simple change?  I'm currently using cibuildwheel for my personal project but want to know how things work.

**Comment by penguinolog** [comment]
Manylinux2010 is not so far from manylinux1, so manylinux2010 for compatibility reasons also making manylinux1 wheels.
Manylinux2014 is different: it Centos 7 based and have different versions of system libraries, so it not able to build wheels for old systems.

**Comment by scoder** [comment]
Works for me, but doesn't seem to have a benefit for now. It just doubles the number of generated "manylinux" wheels.

**Comment by penguinolog** [comment]
technically manylinux2010 uses newer libraries (centos6 instead of centos5), old name is served for old pip compatibility reasons

**Comment by scoder** [comment]
Thanks for bringing this in. I think it's good to make the switch to at least the somewhat newer 2010 wheels.

**Pull request merged**
