### PR TITLE
Mark new GitHub releases as pre-releases depending on the tag name

### PR DESCRIPTION
**Pull request by SpecLad**
Related to #5012.

### CODE REVIEW

**Comment by da-woods** [comment]
I think this looks reasonable but I haven't done much with Github actions myself.

@lithomas1 I think you originally set up this wheels.yml file so just pinging you to see if you have any comment...

**Comment by lithomas1** [comment]
Looks fine to me.

**Comment by da-woods** [comment]
Thanks @lithomas1 - just wanted a sanity check

**Comment by da-woods** [comment]
Thanks @SpecLad

**Pull request merged**
