### PR TITLE
Remove patch utility code in Coroutine.c

### PR DESCRIPTION
**Pull request by matusvalo**
A try to remove patch utility code which seems not needed anymore.

~This is experiment PR just to see the CI results.~

### CODE REVIEW

**Comment by matusvalo** [comment]
There are several other functions marked to be removed in `Cython/Utility/Coroutine.c` but I am not sure whether they are needed or not.

**Comment by matusvalo** [comment]
CI seems turning green so I am marking this PR as ready for review. There is still question whether the code in the end of Coroutine.c should be removed or not...

**Comment by da-woods** [comment]
Looks good to me I think - it looks like all the abc classes are tested and continue to work without this code

**Comment by matusvalo** [comment]
Let's merge it since other PRs are waiting for it. Thanks @da-woods for review.

**Pull request merged**
