### PR TITLE
Avoid spurious noexcept warnings

### PR DESCRIPTION
**Pull request by da-woods**
This re-adds #6343, removes one line which seems to be the source of the spurious warnings, and add a bunch of tests to make sure we don't get the spurious warnings.

Goes into 3.0.x

Fixes https://github.com/cython/cython/issues/6428

### CODE REVIEW

**Comment by tornaria** [comment]
I see now this causes some issues when on `legacy_implicit_noexcept` mode. I'll try to figure out another way.

This all has to do with what happens when there are two declarations (one in .py/.pyx , another in .pxd).

**Comment by tornaria** [comment]
This seems a better fix:
```diff
--- a/Cython/Compiler/Nodes.py
+++ b/Cython/Compiler/Nodes.py
@@ -3126,6 +3126,8 @@ class DefNode(FuncDefNode):
             if scope is None:
                 scope = cfunc.scope
             cfunc_type = cfunc.type
+            if cfunc_type.exception_check:
+                has_explicit_exc_clause=True
             if len(self.args) != len(cfunc_type.args) or cfunc_type.has_varargs:
                 error(self.pos, "wrong number of arguments")
                 error(cfunc.pos, "previous declaration here")
```

**Comment by da-woods** [comment]
Do you have a quick example of some code that you addition fixes?

I'm just trying to make this as tested as possible

**Comment by tornaria** [comment]
> Do you have a quick example of some code that you addition fixes?
> 
> I'm just trying to make this as tested as possible

It's already tested in `legacy_implicit_noexcept_build`.

**Pull request merged**
