### PR TITLE
Initial support for Python 3.11

### PR DESCRIPTION
**Pull request by da-woods**
1. Fixes https://github.com/cython/cython/issues/4158 and https://github.com/cython/cython/issues/4365 (although a better implementation is probably desirable long-term)
2. Conditionally excludes some code that was used to emulate vectorcall on older versions that I think is no longer needed (and which is broken on 3.11)
3. Tries to add 3.11 to the CI

I can split this up into 3 PRs if needed, but testing all 3 at once seemed like the most useful thing to start with

### CODE REVIEW

**Comment by da-woods** [comment]
So the current status is:
* there's a few segmentation faults (related to profiling and generator/coroutine frames). For the "frames" issue I think we know where they're coming from but I don't personally know how to fix it.
* There's a bunch of test failures due to changed exception error messages - this is easily fixed later.
* There's a few other test failures that also need investigating.

I'm inclined to leave this PR here - it fixes the main issues with Python 3.11 and is probably be sufficient for most people to start testing their code. At this early stage I don't think support needs to be perfect.

**Comment by ericsnowcurrently** [comment]
Hmm, this is also broken on 0.29.x.  I'm not sure what Cython's workflow is regarding what goes into earlier releases, but I do see that a different fix for 3.11 went into 0.29.x: #4428.  I'd be glad to help out if needed.

**Comment by da-woods** [comment]
It looks like you can't quite cherry-pick it, but the conflicts looks fairly small. I think the intent is that things like this should go into 0.29.x (at least while Cython 3.0 is still an alpha) Probably the main issue is that the CI is broken on 0.29.x at the moment so it's quite hard to know if something's working at all...

I think it should be combined with https://github.com/cython/cython/commit/3f56484704742c1af33c9737642125c55b0634d5 - that was a fix that it took a little bit longer for me to figure out, but should really have been part of this PR.

So yeah - a PR to getting this in the 0.29.x branch would be helpful I think.

**Comment by da-woods** [comment]
@ericsnowcurrently I ended up doing the backport myself https://github.com/cython/cython/pull/4465 (I figured if it was easy you'd probably have done it by now). Hopefully that lets you (+others) proceed with testing cython dependencies on 3.11

**Comment by ericsnowcurrently** [comment]
Thanks, @da-woods!  Hopefully that wasn't much work.  I hadn't gotten a chance yet to give it a shot.  So thanks for doing it!

**Pull request merged**
