### PR TITLE
Add 'except' values for various function types

### PR DESCRIPTION
**Pull request by jdemeyer**

### CODE REVIEW

**Comment by scoder** [comment]
Hmm, is this documented anywhere? I mean, it looks reasonable, but I wouldn't be so sure that there are no exceptions from these rules. Should we maybe use `except?`, just for safety? The difference isn't big in practice.

**Comment by jdemeyer** [comment]
The fields in the `PyTypeObject*` structure do not explicitly document exception values. See for example [tp_as_mapping->mp_length](https://docs.python.org/3.6/c-api/typeobj.html#c.PyMappingMethods.mp_length) which does not mention exception handling. It does say that it has the same signature as ` PyMapping_Length()` and [PyMapping_Length](https://docs.python.org/3/c-api/mapping.html#c.PyMapping_Length) does document that -1 signals an exception.

If you look in the sources for `PyMapping_Length`, you will see that it just calls `tp_as_mapping->mp_length` without any special exception handling: exceptions are just passed through.

Not sure whether you consider that sufficient or not...

**Comment by scoder** [comment]
I'm more concerned about people using these `typedef`-ed names outside of the `PyTypeObject` struct, if only because "they are there". I mean, the chances of people using them for something that does not do any error handling at all probably aren't very high, but there is always a risk of breaking someone's code out there.

The problem is really that you are changing the typedefs here, and not the `PyTypeObject` struct.

**Comment by jdemeyer** [comment]
> there is always a risk of breaking someone's code out there.

Suppose we add an `except` value to these types, that would break compilation for those people (since the `except` value is part of the function signature, right?). So they will need to change their code anyway.

> I mean, the chances of people using them for something that does not do any error handling at all probably aren't very high

Indeed, that doesn't seem very likely. First of all, you already need to know that those function types exist at all.

**Comment by scoder** [comment]
You got me convinced that it fixes more than it might break. Thanks for your contribution(s), I appreciate it.

**Pull request merged**
