### PR TITLE
Default-enable two build options for the nogil build

### PR DESCRIPTION
**Pull request by ngoldbaum**
Follows the suggestion in https://github.com/cython/cython/pull/6147#issuecomment-2065068588.

I don't see any new errors or failures running the cython tests with the nogil build.

I tried also turning on `CYTHON_AVOID_BORROWED_REFS` as suggested in https://github.com/Quansight-Labs/free-threaded-compatibility/issues/4#issuecomment-2070536777, but that leads to a segfault running the `append.append_unused_retval` cython test, so I'll come back to enabling that option later.

### CODE REVIEW

**Comment by da-woods** [comment]
> I tried also turning on `CYTHON_AVOID_BORROWED_REFS` as suggested in [Quansight-Labs/free-threaded-compatibility#4 (comment)](https://github.com/Quansight-Labs/free-threaded-compatibility/issues/4#issuecomment-2070536777), but that leads to a segfault running the `append.append_unused_retval` cython test, so I'll come back to enabling that option later.

I should look into that - `CYTHON_AVOID_BORROWED_REFS` is only really used for PyPy and hasn't really been tested independently so may well have some of its logic mixed in with other similar options (likely `CYTHON_ASSUME_SAFE_MACROS`). I still think it's likely a good idea for the nogil build long-term but there's probably a bit of work getting it right first.

**Comment by da-woods** [comment]
Thanks.

**Comment by ngoldbaum** [comment]
> Probably should be

Adding a `METH_FASTCALL` there does fix the seg fault in the append test, thanks! However there's another test failure this leads to:

```
Compiler output for module r_extstarargs:
r_extstarargs.cpp:2296:18: error: cannot take the address of an rvalue of type 'PyObject *' (aka '_object *')
  __pyx_v_args = __Pyx_ArgsSlice_VARARGS(__pyx_args, 2, __pyx_nargs);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
r_extstarargs.cpp:1372:76: note: expanded from macro '__Pyx_ArgsSlice_VARARGS'
#define __Pyx_ArgsSlice_VARARGS(args, start, stop) __Pyx_PyTuple_FromArray(&__Pyx_Arg_VARARGS(args, start), stop - start)
                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And indeed it's not correct to pass the address of the new reference returned by `PySequence_GetItem` (which is `__Pyx_Arg_VARARGS` if `CYTHON_AVOID_BORROWED_REFS` is set) in the same way as the macro `PyTuple_GET_ITEM` to another function.

I think the fix here is to refactor the `ArgsSlice` macros to ensure the reference stays valid while `__Pyx_PyTuple_FromArray` runs.

Does that sound like the right fix for you? This would be my first time touching the logic in the cythin compiler so I want a sanity check before diving in.

**Comment by da-woods** [comment]
How about if the `METH_FASTCALL` check only applies to `__Pyx_ArgsSlice_FASTCALL`?

**Pull request merged**
