### PR TITLE
Fix "NoneType object is not callable" exception when using a tracing …

### PR DESCRIPTION
**Pull request by traff**
…function that returns None (#1769)

CPython uses the return value of tracing function to assign it to frame.f_trace field and then it uses it for the frame instead of tstate.c_tracefunc. If it is None, the context shouldn't be traced line by line.

### CODE REVIEW

**Comment by scoder** [comment]
Thanks, but I'm not sure that this is the right fix. CPython doesn't do it this way, at least not at the C level. 

I think the right place to handle this case is probably `__Pyx_TraceSetupAndCall()`, which (I guess) should return 0 for this case in order to disable line tracing for the current function. Could you come up with a test case for it? It should go into `tests/run/line_trace.pyx`. We only use the C level tracing interface in it so far, not the API of Python's `sys` module.

**Comment by traff** [comment]
Thanks for the quick response! I was definitely going to add a test case but first wanted to ask where is the best place to add it.

**Comment by traff** [comment]
I don't think that __Pyx_TraceSetupAndCall is the right place for this check, because it is called only from __Pyx_TraceCall, while the tracing can be disabled in the __Pyx_TraceLine as well.

CPython does it this way: in the trampolin function for the tracing function it makes the following check

  if (what == PyTrace_CALL)
        callback = self;
    else
        callback = frame->f_trace;
    if (callback == NULL)
        return 0;

So from the first glance it looks like if we add the check of frame->f_trace to the __Pyx_TraceLine function will do basically the same, because other events (CALL and RETURN) aren't affected by frame->f_trace anyway.

**Comment by scoder** [comment]
The change seems reasonable to me now, but it breaks some tests in `line_trace.pyx`.
I'd still prefer keeping the `tstate->c_tracefunc` check in addition, just as a safety measure. Could you please 1) add that check back, 2) see if you can fix up the failing tests (just ask if anything is unclear in there) and 3) add a new test for the case that's failing for you?

You can run that test file with
`python runtests.py -vv --debug line_trace`
The `--debug` flag will (amongst other things) keep the generated files (in `TEST_TMP/run/`) after the test run, so you can look into them. You can also disable the C++ repetition of the test run with `--backend=c`, although the stricter C++ compiler checks are sometimes helpful.

**Comment by scoder** [comment]
Nice! :)
But now the test is failing under Py2.6. Somehow the line numbers for return events differ, e.g.:
```
File "cython/TEST_TMP/3/run/c/line_trace/line_trace.so", line ?, in line_trace.__test__.run_trace (line 109)
Failed example:
    run_trace(cy_add, 1, 2)
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    [('call', 0), ('line', 1), ('line', 2), ('return', 0)]
```
I can't find any special casing for Py2.6 in Cython here, so it's probably either a bug or an otherwise functional difference in Py2.6 compared to 2.7.
Any idea?

**Comment by traff** [comment]
Ughh... I have no idea... And it's strange that it started to fail now after my changes, which shouldn't
 be changing this particular behavior. Probably some Python 2.6 issues. I will take a deeper look at that.

**Comment by scoder** [comment]
I've resolved the recent merge conflicts. Any update on this? If it's a real difference in CPython behaviour, I'd be ok with disabling the failing parts in Py2.6, but it might still hide an actual bug in Cython's implementation.

**Comment by traff** [comment]
Hi! Thanks for bringing that up. I didn't forget about that, just couldn't find the right moment to debug it properly.
I think that isn't Cython bug, but a difference in CPython behavior.
I dove inside a bit today and observed that on Python 2.6 frame->f_lineno, although is being set in Cython code to the correct value in the TraceLine call, is reverted to the first line number for some reason before the TraceReturn (I didn't go deeper to CPython 2.6 code to understand why that happens).
The only thing that could be fixed on the Cython side is passing the actual line number to the TraceReturn function as an argument as it is done for TraceLine.
Or we can just disable the test on Python 2.6 given that it is quite an obsolete version and differs from other for no obvious reason.

**Comment by traff** [comment]
The exact moment where the frame->f_lineno is reverted is after the call to __Pyx_PyObject_SetAttrStr which corresponds to frame.f_trace = result in trace_trampoline:48
So I guess this change to f_trace field affects f_lineno field somehow, which definitely not the expected behavior of PyFrameObject.

**Comment by scoder** [comment]
In Py2.6, the setter is implemented like this:
```
static int
frame_settrace(PyFrameObject *f, PyObject* v, void *closure)
{
    /* We rely on f_lineno being accurate when f_trace is set. */

    PyObject* old_value = f->f_trace;
    Py_XINCREF(v);
    f->f_trace = v;

    if (v != NULL)
        f->f_lineno = PyCode_Addr2Line(f->f_code, f->f_lasti);

    Py_XDECREF(old_value);
    return 0;
}
```
Note how it calls `PyCode_Addr2Line()` with `f_lasti` as argument. Cython functions do not have byte code, so this miscalculates the line number. This has been changed in Py2.7 to actually rely on `f_lineno` being correct when `f_trace` is set, as the comment already suggested before. ;)

I would guess that directly assigning to the `f_trace` member instead of going through the getter should fix it.

**Comment by traff** [comment]
What is the best way to assign it directly in Cython? I can imagine only calling a C function from the Cython code.

**Comment by scoder** [comment]
I'll just see that I get Py2.6 fixed up here.

Thanks for your contribution.

**Comment by scoder** [comment]
... and now I found that this breaks [line_profiler](https://pypi.python.org/pypi/line_profiler). There is a test `line_profile_test.srctree` that is enabled when it's installed. When I remove the `None` checks again, then the test passes.

**Comment by scoder** [comment]
I've reworked the tests in 71c1ad42e869f100787d40e7d0b76ae8c26e869f. Turns out that checking for `None` is not the right thing to do, but a `NULL` check is. I also couldn't find the functionality that you described for disabling the tracing in between lines. All I could find in the CPython code was that it can be disabled on function entry, i.e. `CALL`.

**Comment by traff** [comment]
Hi, yes you are right tracing isn't disabled on the LINE events. I tried to reproduce it and it didn't work as I expected. My expectations that it should were based on this description in the Python documentation:
`
The local trace function should return a reference to itself (or to another function for further tracing in that scope), or None to turn off tracing in that scope.


[5:46] 
https://docs.python.org/3/library/sys.html#sys.settrace
`

**Pull request merged**
