### PR TITLE
Fix the cdiv() and cmod() definitions in Shadow.py

### LINKED ISSUE #2643: cdiv and cmod incorrect?
I was looking at the definitions of `cdiv` and `cmod` in Shadow.py. These seem to give incorrect results for some operands. For example, in C99:

```
4 / -4 == -1    4 % -4 == 0
4 / -2 == -2    4 % -2 == 0
4 / -1 == -4    4 % -1 == 0
```

But these functions would return:

```
cdiv(4, -4) == 0    cmod(4, -4) == 4
cdiv(4, -2) == -1    cmod(4, -2) == 2
cdiv(4, -1) == -3    cmod(4, -1) == 1
```

That's based on just running those definitions in the Python interpreter. Perhaps Cython handles them specially, and doesn't in fact give the incorrect results above. Still, why not include correct Python code? The following would work:

```
def cdiv(a, b):
    if a < 0:
        a = -a
        b = -b
    if b < 0:
        return (a + b + 1) // b
    return a // b

def cmod(a, b):
    r = a % b
    if (a*b) < 0 and r: r -= b
    return r
```

Sorry if this is just me misunderstanding some magic behind the scenes stuff.

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Closes #2643.

### CODE REVIEW

**Comment by McSinyx** [comment]
Is backward compatibility considered?  I mean if someone relies on the C-like division behavior?

**Comment by scoder** [comment]
Thanks

**Comment by scoder** [comment]
@McSinyx, users would normally rely on the compiled behaviour rather than the implementation in `Shadow.py` here, because that's what they aim for in the first place. Any discrepancy between the two should just be fixed in `Shadow.py` and follow the compiled behaviour (well, assuming that is correct, but you get the idea).

**Comment by McSinyx** [comment]
@scoder:  Thank you for the insight.

**Pull request merged**
