### PR TITLE
Build and keep wheels in Github Actions.

### PR DESCRIPTION
**Pull request by scoder**

### CODE REVIEW

**Comment by mattip** [comment]
Nice. There are 22 artifacts for the 41 jobs (excluding coverage). Is that the intention?

**Comment by scoder** [comment]
> Nice. There are 22 artifacts for the 41 jobs (excluding coverage). Is that the intention?

Difficult to say. :) I'm still experimenting.

Most jobs won't contribute a wheel, e.g. C++ vs. C, or the limited API jobs.
In the end, I'm mostly interested in the macos wheels.

**Comment by 0dminnimda** [comment]
Are there any plans to add checks for windows?

**Comment by scoder** [comment]
> Are there any plans to add checks for windows?

"Plans" sounds exaggerated, but if you can make it work, I'd be happy to receive a PR.

**Comment by 0dminnimda** [comment]
> if you can make it work, I'd be happy to receive a PR.

Among the tests, it seems very likely to find those that will not work on Windows.
The question is: If I manage to get it to work, then in the same PR I will have to fix all these failures associated with working on Windows?

**Comment by 0dminnimda** [comment]
I'll be more direct, I don't want to fix them, can we somehow organize so that I just make the tests work, I don't have to fix anything? `:3`

**Comment by da-woods** [comment]
There is a "windows_bugs" file (https://github.com/cython/cython/blob/master/tests/windows_bugs.txt) that causes tests to be skipped on Windows.

If there isn't an obvious fix then it's fine to add the test to that file instead.

**Pull request merged**
