### PR TITLE
Use Development release segment in public version identifiers

### PR DESCRIPTION
**Pull request by jjerphan**
Fixes https://github.com/cython/cython/issues/5204

As specified by PEP 440: https://peps.python.org/pep-0440/#public-version-identifiers

### CODE REVIEW

**Comment by scoder** [comment]
Seems helpful. Thanks.

**Comment by jjerphan** [comment]
Thanks for your reactivity!

**Comment by lesteve** [comment]
This broke installing Cython from the `master` branch e.g. with:
```
pip install https://github.com/cython/cython/archive/master.zip
```

I think similar errors can be seen in the CI.

It does not look like Cython knows what to do with `dev0`

Full traceback:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/tmp/pip-req-build-nw3q1z65/setup.py", line 317, in <module>
    run_build()
  File "/tmp/pip-req-build-nw3q1z65/setup.py", line 245, in run_build
    setup(
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/lesteve/miniconda3/envs/scratch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
  File "/tmp/pip-req-build-nw3q1z65/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Build/Dependencies.py", line 1280, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/Main.py", line 604, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/Main.py", line 528, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/Pipeline.py", line 397, in run_pipeline
    data = run(phase, data)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/Pipeline.py", line 374, in run
    return phase(data)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/ModuleNode.py", line 206, in process_implementation
    self.generate_c_code(env, options, result)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/ModuleNode.py", line 475, in generate_c_code
    self.generate_module_preamble(env, options, modules, result.embedded_metadata, h_code)
  File "/tmp/pip-req-build-nw3q1z65/Cython/Compiler/ModuleNode.py", line 783, in generate_module_preamble
    code.putln('#define CYTHON_HEX_VERSION %s' % build_hex_version(__version__))
  File "/tmp/pip-req-build-nw3q1z65/Cython/Utils.py", line 624, in build_hex_version
    digits.append(int(digit))
ValueError: invalid literal for int() with base 10: 'dev0'
```

**Comment by scoder** [comment]
Fixed in https://github.com/cython/cython/commit/d798d65557d4926db70232b482cb41daec4c8250

**Pull request merged**
