### PR TITLE
Error if Cython enum is used outside a typed context

### LINKED ISSUE #5638: [BUG] enum class initializer throws NameError
### Describe the bug

In C++ initialization of an enum class should value initialize (at least in the case of an empty initializer list, I haven't dug too deeply into what should happen if given a real value). Cython compiles such code but then throws a NameError at runtime.

### Code to reproduce the behaviour:

```cython
# distutils: language = c++


cdef enum class my_enum(int):
    a = 1
    b = 2


def f():
    my_enum()
```

This code compiles correctly, but at runtime I get:
```
(main) dt08% python -c 'import definitions; definitions.f()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "definitions.pyx", line 10, in definitions.f
    my_enum()
NameError: name 'my_enum' is not defined
```

### Expected behaviour

 I think throwing an error during compilation would be an acceptable outcome here, if normal value initialization is not possible (especially if the non-empty initializer list case is actually UB; I haven't looked deeply enough yet to say either way).

### OS

Linux

### Python version

3.11.4

### Cython version

3.0.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vyasr**
Without a cpdef to generate a corresponding Python enum, cdef enums (and enum classes) are not valid in pure Python context and should be detected accordingly.

I'm not sure if this is the best approach here and would appreciate some feedback, thanks!

Resolves #5638

### CODE REVIEW

**Comment by shwina** [comment]
Note; this closes https://github.com/cython/cython/issues/5638

**Comment by scoder** [comment]
Seems reasonable. Not sure whether it's an error or warning, but I agree that there's probably not much sense in such code. That speaks for an error.

In any case, I'll postpone this until after 3.0.2, which urgently fixes major regressions in the 3.0.1 release.

**Comment by vyasr** [comment]
> Seems reasonable. Not sure whether it's an error or warning, but I agree that there's probably not much sense in such code. That speaks for an error.
> 
> In any case, I'll postpone this until after 3.0.2, which urgently fixes major regressions in the 3.0.1 release.

Agreed, I think error probably makes the most sense here. It's not like an unused variable or something similar harmless, it's trying to create an object in a context where it shouldn't be possible.

**Comment by vyasr** [comment]
@scoder do you think this is mergeable, or do you want to see a different approach?

**Comment by da-woods** [comment]
I think this is fine but just got lost under some more serious bug fixes. I'll merge it to 3.1 now and let @scoder decide whether to backport to 3.0.6.

Thanks for the fix.

**Pull request merged**
