### PR TITLE
Made the readme pretty for github.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
I changed the readme to fit the markdown style of github. Also added some links and installation instructions.

You can see the result [there](https://github.com/gabrieldemarmiesse/cython/tree/readme)

### CODE REVIEW

**Comment by scoder** [comment]
Hmm, since we're using ReST for all other docs files, I'd prefer using it here, too. I.e. change it to ReST format and rename it to `README.rst`. github can handle that, too.

**Comment by gabrieldemarmiesse** [comment]
Sure thing!

**Comment by gabrieldemarmiesse** [comment]
Should be good now.

**Comment by scoder** [comment]
Perfect, thanks!

**Pull request merged**
