### PR TITLE
Fix cleanup of non-py-object constants on module close

### PR DESCRIPTION
**Pull request by da-woods**
Another thing uncovered by https://github.com/cython/cython/pull/5261

Not all `py_constants` are actually `py_constants` so they need to be checked before generating clean-up code.

In this case integer function argument defaults look to be being added to `py_constants`.

This possibly isn't the right place to fix it though, so I'm open to other suggestions

### CODE REVIEW

**Comment by scoder** [comment]
> This possibly isn't the right place to fix it though, so I'm open to other suggestions

Yes, it seems surprising to keep non-Python constants in `py_constants`, and leads to broken code like this. I'm fine with using this as a quick-fix, but you're right, this is worth cleaning up.

**Comment by scoder** [comment]
Hmm, was this actually a complete fix? The related tests in https://github.com/cython/cython/pull/5261 still seem to fail.

**Comment by scoder** [comment]
You were probably referring to this, right?
```
typeddefaultargT373.c: In function ‘__pyx_m_clear’:
/opt/hostedtoolcache/Python/3.6.15/x64/include/python3.6m/object.h:834:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         PyObject *_py_tmp = (PyObject *)(op);   \
                             ^
typeddefaultargT373.c:2118:3: note: in expansion of macro ‘Py_CLEAR’
   Py_CLEAR(clear_module_state->__pyx_k_);
   ^~~~~~~~
/opt/hostedtoolcache/Python/3.6.15/x64/include/python3.6m/object.h:836:18: warning: assignment to ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
             (op) = NULL;                        \
                  ^
typeddefaultargT373.c:2118:3: note: in expansion of macro ‘Py_CLEAR’
   Py_CLEAR(clear_module_state->__pyx_k_);
   ^~~~~~~~
In file included from /opt/hostedtoolcache/Python/3.6.15/x64/include/python3.6m/Python.h:81,
                 from typeddefaultargT373.c:16:
typeddefaultargT373.c: In function ‘__pyx_m_traverse’:
/opt/hostedtoolcache/Python/3.6.15/x64/include/python3.6m/objimpl.h:354:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             int vret = visit((PyObject *)(op), arg);                    \
                              ^
typeddefaultargT373.c:2189:3: note: in expansion of macro ‘Py_VISIT’
   Py_VISIT(traverse_module_state->__pyx_k_);
   ^~~~~~~~
```

**Comment by da-woods** [comment]
> Hmm, was this actually a complete fix? The related tests in #5261 still seem to fail.

I'll check later, but I don't think I pushed this commit to #5261. So it could just be that.

> You were probably referring to this, right?

Yes.

There's a remaining bug I'm aware of to do with access to module state on interpreter shutdown when cleaning up these modules. But I don't think that's fixable in 3.0 (just because it's a big changes)

**Pull request merged**
