### PR TITLE
Add exception handling for `libcpp::stack::push`

### PR DESCRIPTION
**Pull request by jjerphan**
This adds a simple exception handling to `stack::pop`.

Tests are to be added, if needed.

### CODE REVIEW

**Comment by da-woods** [comment]
I wonder if this should be applied to basically all stack functions? As far as I can tell they can all potentially throw exceptions (since it doesn't make assumptions about what the underlying container might do). But `push` is probably the most likely to throw I think.

**Comment by jjerphan** [comment]
Yes, I am first trying to understand [some of the CI failures](https://github.com/cython/cython/runs/5784822002?check_suite_focus=true#step:5:16739) which do not seem to be related to the changes here.

```
-- stderr:/Users/runner/hostedtoolcache/Python/3.9.11/x64/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
```

**Comment by da-woods** [comment]
Closing and reopening to retrigger the CI - I can't see any way that the failures are related.

**Comment by jjerphan** [comment]
Indeed, they are gone, now.

Should I add tests? :smile:

**Comment by jjerphan** [comment]
Indeed, they are gone, now.

Must I add tests?

**Comment by da-woods** [comment]
We've accepted similar PRs without tests before (https://github.com/cython/cython/pull/4079) so I don't think they're really necessary here.

**Pull request merged**
