### PR TITLE
Fix (most) unused variable warnings about clineno

### PR DESCRIPTION
**Pull request by da-woods**
It's still unused even if we don't set it, so take it out of the bit that sets it conditionally.

### CODE REVIEW

**Review by matusvalo — APPROVED** [review]
When compiling large .pyx file all warnings are gone and the file size has same reduced size when `c_line_in_traceback=False`

**Comment by matusvalo** [comment]
I am feeling adventurous so let's have it in next sub-minor release. I hope there is no opposition.

**Comment by da-woods** [comment]
> I am feeling adventurous so let's have it in next sub-minor release. I hope there is no opposition.

I think we usually count c warnings as defects and so would consider this a bugfix. It's also pretty obviously low impact.

**Comment by rgommers** [comment]
Thanks! This indeed fixes all the warnings I was seeing in SciPy.

**Comment by da-woods** [comment]
3.0.x commit ead1ac694

**Pull request merged**
