### PR TITLE
Add `tp_methods` to `PyTypeObject`

### PR DESCRIPTION
**Pull request by jakirkham**
Includes [`tp_methods`]( https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_methods ) in the `PyTypeObject` `extern` definition. Should allow Cython code to access this field and inspect its contents.

### CODE REVIEW

**Comment by jakirkham** [comment]
There seems to be an issue with Sphinx in [one of the CI jobs]( https://github.com/cython/cython/runs/5725374563?check_suite_focus=true#step:5:344 ), but it doesn't seem related to this change. All other tests pass

<details>

```python
sphinx-build -b html -d build/doctrees -D latex_paper_size=a4  . build/html
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2'
```

</details>

**Comment by da-woods** [comment]
Yeah - Sphinx is known and being fixed in a different PR

**Comment by jakirkham** [comment]
Thanks for clarifying. Now see PR ( https://github.com/cython/cython/pull/4700 )

**Comment by jakirkham** [comment]
Looks like that doc PR went in. Merging with the latest changes here to get that fix and restart CI.

**Comment by jakirkham** [comment]
CI now passes! 🎉 Please let me know if anything else is needed here 🙂

**Comment by scoder** [comment]
Thanks

**Comment by jakirkham** [comment]
Thank you! 😄

**Pull request merged**
