### PR TITLE
Use appveyor to build windows wheels

### PR DESCRIPTION
**Pull request by aebrahim**
These wheels can then be uploaded to pypi to make installation simple for Windows users.

An example of a built wheel is available here:

https://ci.appveyor.com/project/aebrahim/cython/build/1.0.1/job/0opg995oyo05c4y8/artifacts

Procedure taken from https://packaging.python.org/en/latest/appveyor.html

### CODE REVIEW

**Comment by dalcinl** [comment]
The Python versions are outdated.

**Comment by aebrahim** [comment]
OK I updated the minor versions to be the most recent ones.

(Also, that environmental variable is just used for downloading a python release from the FTP site in case Appveyor does not have it installed, so it wasn't actually used in the building process).

**Comment by dalcinl** [comment]
I'm still in doubt about a detail. Some of the code in the YAML file and the PowerShell script use  the POSIX ``/`` path separator instead of the Windows ``\`` one. I'm doing this setup right now for one of my projects, and I did have issues related to these paths. The thing is that I actually ran the ``install.ps1`` script in a clean virtual machine, then I think I exercised more code paths and eventually hit the issue.

Even in the case these paths do work, shouldn't we do it the Windows one, at last to be consistent?

PS: And of course, we should be careful with the path separator for URLs.

**Comment by aebrahim** [comment]
OK done.

Do you want me to rebase it into a single commit?

**Comment by dalcinl** [comment]
Yes, I think that for this kind of commit a rebase makes sense.

**Comment by aebrahim** [comment]
OK rebased.

**Comment by dalcinl** [comment]
@robertwb @scoder Folks, if you have no objections, I'll merge this one.

**Comment by robertwb** [comment]
I'm not familiar with Windows build setups, but I'm happy with the general idea and if it looks good to you let's merge.

**Comment by dalcinl** [comment]
@aebrahim What about merging this one to branch 0.22.x ? BTW, any idea why the Travis CI build failed? Did you just generate a single commit ? Or did you rebase to an updated master also?

**Comment by aebrahim** [comment]
Rebased to a single commit on top of the updated master.

I didn't modify anything that should affect the Travis build so I don't
know why it failed.

**Comment by scoder** [comment]
master was broken over night due to some changes for PEP 448, sorry. I'm currently fixing it up.

**Comment by aebrahim** [comment]
Rebased on top of the newest master. Looks like everything worked on both travis and [appveyor](https://ci.appveyor.com/project/aebrahim/cython/build/1.0.6).

**Comment by aebrahim** [comment]
Oh, I just saw your comment about the other branch. Now that this is just one commit, it might be easiest if you just cherry-pick it onto whichever branch you prefer.

**Comment by dalcinl** [comment]
@aebrahim Well, as you already have setup the project in AppVeyor, I think it would be quicker if you rebase your branch to 0.22.x, update this PR (is it possible to change the target merge branch in GitHub PRs?), then we are 100% sure everything is working. Sorry, I know you already worked a lot to get this done, but I feel a bit nervous about merging this to 0.22.x without a confirmation that is indeed working as  expected.

**Comment by aebrahim** [comment]
I don't know of a way to change the merge target.

I've created PR #389 targeting the 0.22.x branch.

**Pull request closed without merging**
