### PR TITLE
Split up module init function

### PR DESCRIPTION
**Pull request by da-woods**
This is an attempt at testing something - I'd be interested in feedback on the general idea, but the way I've implemented is a fairly messy hack (and I'm aware of this...). If we actually want to follow this up then it probably needs a rewrite.

My belief is that the size of the module init function is often slowing down the C compiler because it's simply too big for it to keep track of. This change generates a separate C function per stat, and the module init function just calls them in sequence.

On my laptop it seemed to knock about 15% from the compilation-time of ExprNodes.py. But it's a fairly old laptop and there's probably a lot of thermal throttling involved. Therefore I'd like to see on the CI (I'm particularly interested in the `-all` tests, which are constantly pumping up against the 30 minute limit)

### CODE REVIEW

**Comment by da-woods** [comment]
I still think there might be something in it, but I don't think my approach to implementing it is realistically going to work (I think really it needs to be done at the code generation stage rather than by creating new nodes). So I'll close this and possibly have another go some other time.

**Comment by da-woods** [comment]
This is slightly inconclusive - the "Py 2.7 -all" tests do all finish and relatively quickly (which is fairly unusual, but not unheard of). But most of the timings are broadly within the usual margin of error. I think I need to come up with a better way of profiling it.

I definitely don't think anyone wants to use this implementation. But it's still unclear whether the approach is worthwhile - I think it might be but it doesn't look to be a dramatic difference.

**Comment by da-woods** [comment]
So based on some timings on my PC: for most modules this makes no difference. For large modules (e.g. `Nodes.py` and `ExprNodes.py` it seems to make a consistent measurable difference). Using `time` on linux and selecting user time:

|                | setup.py | Nodes.py | ExprNodes.py |
|-------------|-------------|---------------|--------------------|
| master   |  1m9.667s | 2m39.361s | 4m11.199s |
| this branch | 1m10.814s | 2m19.935s | 3m37.413s |

I'm not sure exactly what the cutoff is but it might be around the point that GCC emits

```
note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
430274 | static CYTHON_SMALL_CODE int __pyx_pymod_exec_ExprNodes(PyObject *__pyx_pyinit_module)
```

A possible alternative approach that might be less intrusive than this could be to include "no-var-tracking-assignments" in `CYTHON_SMALL_CODE` (somehow)

**Comment by scoder** [comment]
> `note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without`

Yes, that's an issue. All of the boiler plate code that we add to the module init function, e.g. the function creation, is already extracted, so what's left is really just the module level user code.

A separate `ModuleStatListNode` subclass could make your current design cleaner. But then there's still the function creation.

Maybe we could focus on the statement-local temp variables and put those into a new scope, rather than creating entirely new functions? Can't say for sure if that helps the C compiler, but it might simplify the assignment tracking already, and if so, by a margin. Just an idea, in case you want to continue investigating this.

**Comment by da-woods** [comment]
> Maybe we could focus on the statement-local temp variables and put those into a new scope, rather than creating entirely new functions? Can't say for sure if that helps the C compiler, but it might simplify the assignment tracking already, and if so, by a margin. Just an idea, in case you want to continue investigating this.

I actually tried that a little while ago (https://github.com/da-woods/cython/tree/morelocaltemps) and it seems to make no measurable difference, unfortunately. Which is a shame because it'd have been much less intrusive.

I'll leave this for the moment just because I think it's too messy for the fairly small benefit it brings (it's a real benefit, but only to absolutely huge modules). I may come back to it at some point if I can find a more natural design for it.

**Comment by scoder** [comment]
> > Maybe we could focus on the statement-local temp variables and put those into a new scope, rather than creating entirely new functions? Can't say for sure if that helps the C compiler, but it might simplify the assignment tracking already, and if so, by a margin. Just an idea, in case you want to continue investigating this.
> 
> I actually tried that a little while ago (https://github.com/da-woods/cython/tree/morelocaltemps) and it seems to make no measurable difference, unfortunately. Which is a shame because it'd have been much less intrusive.

When you say that there was no "measurable" difference, do you mean a speed difference in the C compiler run, or did you still see the "variable tracking size limit" warning occur despite the scoping? Because if this allowed us to get rid of that warning, I would consider it a relevant improvement.

**Comment by da-woods** [comment]
> When you say that there was no "measurable" difference, do you mean a speed difference in the C compiler run, or did you still see the "variable tracking size limit" warning occur despite the scoping? Because if this allowed us to get rid of that warning, I would consider it a relevant improvement.

Both. There's no difference in speed and the warning is still there.

**Pull request closed without merging**
