### PR TITLE
Created a glossary and added one new entry

### PR DESCRIPTION
**Pull request by tashachin**

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. Since this is (hopefully) going to grow at some point, could you move it to a separate file, so that it doesn't fill up the main index file of that chapter?

**Comment by tashachin** [comment]
@scoder Of course. Ready for another review.

**Comment by scoder** [comment]
I think it should go to the very end. The intention is to link terms to it, not to make it overly visible all by itself.

**Comment by tashachin** [comment]
LGTM, sorry for all the back-and-forth!

**Comment by scoder** [comment]
Thanks

**Pull request merged**
