### PR TITLE
Use appveyor to build windows wheels

### PR DESCRIPTION
**Pull request by aebrahim**
Use the appveyor continuous integration service to build wheels for
windows. This procedure was adapted from this guide:

https://packaging.python.org/en/latest/appveyor.html

This is the same as #388 but against the 0.22.x branch instead of master.

### CODE REVIEW

**Comment by aebrahim** [comment]
Appveyor status is here: https://ci.appveyor.com/project/aebrahim/cython/build/1.0.7

**Comment by dalcinl** [comment]
OK, so I'll merge this one and decline #388 

A final comment/question: In the YAML file, for Python 64 bits, ``WINDOWS_SDK_VERSION`` is defined in the matrix environment. However, in the ``run_with_compiler.cmd``, the setting is ignored and the environment var is redefined (to the same value). Does it make sense to remove the definitions from the YAML file?

**Comment by aebrahim** [comment]
Now that this works, is there any possibility that binary wheels will also be posted on https://pypi.python.org/pypi/Cython/?

(On an unrelated note, I think that the macosx_10_6_intel tag will now install on later macosx versions and also work with homebrew, making the extra tags redundant)

**Comment by hickford** [comment]
I think one of us needs to create an appveyor account for the Cython organisation. Follow http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

**Comment by aebrahim** [comment]
If that ends up happening, may I request that Cython windows wheels also be
hosted on pypi? That would be quite helpful.

**Comment by hickford** [comment]
Thanks Ali for your work. I too would like wheels on PyPI https://mail.python.org/pipermail/cython-devel/2015-September/004541.html

**Comment by dalcinl** [comment]
https://ci.appveyor.com/project/cython/cython

**Pull request merged**
