### PR TITLE
Fixes test of the fstrings support that fails on narrow builds of Python

### PR DESCRIPTION
**Pull request by embray**
This fixes an error in the tests that occurs on older versions of Python (< 3.3) built with narrow unicode strings (common on Windows):

```
======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running fstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./runtests.py", line 1057, in run
    ext_so_path = self.runCompileTest()
  File "./runtests.py", line 751, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "./runtests.py", line 950, in compile
    self.run_cython(test_directory, module, workdir, incdir, annotate)
  File "./runtests.py", line 856, in run_cython
    full_module_name=module)
  File "/home/embray/src/cython/Cython/Compiler/Main.py", line 684, in compile
    return compile_single(source, options, full_module_name)
  File "/home/embray/src/cython/Cython/Compiler/Main.py", line 634, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/embray/src/cython/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/embray/src/cython/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/home/embray/src/cython/Cython/Compiler/Pipeline.py", line 35, in parse
    tree = context.parse(source_desc, scope, pxd = 0, full_module_name = full_module_name)
  File "/home/embray/src/cython/Cython/Compiler/Main.py", line 353, in parse
    tree = Parsing.p_module(s, pxd, full_module_name)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 3579, in p_module
    body = p_statement_list(s, ctx(level=level), first_statement = 1)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2283, in p_statement_list
    stat = p_statement(s, ctx, first_statement = first_statement)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2233, in p_statement
    return p_def_statement(s, decorators)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 3308, in p_def_statement
    doc, body = p_suite_with_docstring(s, Ctx(level='function'))
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2308, in p_suite_with_docstring
    body = p_statement_list(s, ctx)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2283, in p_statement_list
    stat = p_statement(s, ctx, first_statement = first_statement)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2275, in p_statement
    return p_simple_statement_list(s, ctx, first_statement=first_statement)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2104, in p_simple_statement_list
    stat = p_simple_statement(s, first_statement = first_statement)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 2098, in p_simple_statement
    node = p_expression_or_assignment(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 1461, in p_expression_or_assignment
    expr_list = [p_testlist_star_expr(s)]
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 1407, in p_testlist_star_expr
    expr = p_test_or_starred_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 207, in p_test_or_starred_expr
    return p_test(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 139, in p_test
    expr = p_or_test(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 160, in p_or_test
    return p_rassoc_binop_expr(s, ('or',), p_and_test)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 163, in p_rassoc_binop_expr
    n1 = p_subexpr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 176, in p_and_test
    return p_rassoc_binop_expr(s, ('and',), p_not_test)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 163, in p_rassoc_binop_expr
    n1 = p_subexpr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 186, in p_not_test
    return p_comparison(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 192, in p_comparison
    n1 = p_starred_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 216, in p_starred_expr
    expr = p_bit_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 258, in p_bit_expr
    return p_binop_expr(s, ('|',), p_xor_expr)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 263, in p_xor_expr
    return p_binop_expr(s, ('^',), p_and_expr)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 268, in p_and_expr
    return p_binop_expr(s, ('&',), p_shift_expr)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 273, in p_shift_expr
    return p_binop_expr(s, ('<<', '>>'), p_arith_expr)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 278, in p_arith_expr
    return p_binop_expr(s, ('+', '-'), p_term)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 283, in p_term
    return p_binop_expr(s, ('*', '@', '/', '%', '//'), p_factor)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 94, in p_binop_expr
    n1 = p_sub_expr(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 289, in p_factor
    return _p_factor(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 308, in _p_factor
    return p_power(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 416, in p_power
    n1 = p_atom(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 690, in p_atom
    kind, bytes_value, unicode_value = p_cat_string_literal(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 798, in p_cat_string_literal
    kind, bytes_value, unicode_value = p_string_literal(s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 930, in p_string_literal
    _append_escape_sequence(kind, chars, systr, s)
  File "/home/embray/src/cython/Cython/Compiler/Parsing.py", line 978, in _append_escape_sequence
    chrval = ord(lookup_unicodechar(escape_sequence[3:-1]))
TypeError: ord() expected a character, but string of length 2 found

```

### CODE REVIEW

**Comment by scoder** [comment]
Thanks. However, Cython has its own internal implementation of `ord()` (look for `__Pyx_PyObject_Ord()` and `__Pyx_PyUnicode_AsPy_UCS4()`) which should normally be used here. I wonder why it's not working on your side. Could you investigate that?

**Comment by embray** [comment]
I'm not sure what you mean--this is a bug in Cython itself, not in Cython-generated code.

**Comment by scoder** [comment]
"this is a bug in Cython itself, not in Cython-generated code." - ah, yes, sorry. You are not using a compiled version of Cython but the plain Python code. Cython's own adaptations do not apply in that case. Obviously, both versions must work and produce the same results.

**Comment by scoder** [comment]
I rewrote your implementation a bit. Could you please check if it still works for you?

**Pull request closed without merging**
