### PR TITLE
Optimize Travis build time

### PR DESCRIPTION
**Pull request by thedrow**
This should make the build a lot faster...

### CODE REVIEW

**Comment by thedrow** [comment]
As I suspected, it looks like nothing is cached.
I think it's because we specified Python as the language instead of C/C++.
I'll try to workaround it.

**Comment by thedrow** [comment]
With 4 cores on OSX the `python setup.py build` time is reduced from:
real	1m20.209s
user	1m13.033s
sys	0m2.593s
to:
real	1m3.327s
user	0m57.692s
sys	0m1.634s

**Comment by thedrow** [comment]
So after specifying the cache path directly ccache is working.
This is ready to be merged.

**Comment by scoder** [comment]
Thanks! I selected most of your changes in 16e9de640bed1667fbb8a68846c930c8f0596a46.
I'm not sure I want to go the "monkey-patch into distutils" path. These things tend to break at some point. Let's see what the other changes give. Running the tests is always the slowest part.

**Pull request closed without merging**
