### PR TITLE
Converted files to rst for easier navigation in the github repo.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
Once it's merged, I'll add some more links in the README.

### CODE REVIEW

**Comment by scoder** [comment]
Hmm, this probably has an impact on package maintainers, e.g. of Debian packages etc.

**Comment by gabrieldemarmiesse** [comment]
Could you develop on this? What should I look out for? I'm not familiar with making debían packages.

**Comment by scoder** [comment]
Sorry, I wasn't very clear. I was considering that some packagers special case the top-level doc files (e.g. Debian usually installs license and readme files into a docs directory). They would thus have to adapt their packaging setup for the next version. I'm not sure our gain here is worth making them do that.

**Comment by gabrieldemarmiesse** [comment]
Would this work?

**Comment by scoder** [comment]
Sorry, Gabriel, I hope you don't mind if I reject this change. While it's an improvement for us, I just don't want to burden packagers with fixing up their setup for such a small change.

**Comment by gabrieldemarmiesse** [comment]
Sure, I understand. I trust your judgment on this.

**Pull request closed without merging**
