### PR TITLE
Fix importing of namespace packages. Add in a regtest for the same.

### PR DESCRIPTION
**Pull request by newt0311**
Python 3.3 added in support for namespace packages which are essentially directories with no `__init__.py` file. This pull request adds in support for these into pyximport.

On python2 trying to import a pyx module in a namespace package is still an error (which matches normal python behavior). 

Note that the regtest only works on python3. Not sure how to adjust it for python2 but happy to update this pr if somebody can point me in the right direction...

-- PG

### CODE REVIEW

**Comment by scoder** [comment]
You can exclude the test in `runtests.py`, look for `VER_DEP_MODULES`.

**Comment by tcwalther** [comment]
This is a fantastic PR, thanks so much. Any estimation on when this will be released on PyPI, either as a bugfix release for 0.28 or as part of 0.29?

**Comment by scoder** [comment]
Probably a couple of weeks still, in 0.29.

**Comment by tcwalther** [comment]
Good to know, thanks for the information.

**Pull request merged**
