### PR TITLE
Bug fix for deque and vector random-access iterators

### PR DESCRIPTION
**Pull request by Alexhuszagh**
As mentioned in issue #1867:

1. Added deque support for random-access iterators
2. Changed various `reverse_iterator` methods to return `reverse_iterator` rather than `iterator`.
3. Added `difference_type operator-(iterator)` for all random-access iterators.

### CODE REVIEW

**Comment by scoder** [comment]
The `libcpp_all` test (which just cimports what's there) now fails:
```
9:12: 'difference_type' is not a type identifier
22:12: 'difference_type' is not a type identifier
```
It would be good to have at least one additional test for each of the classes that you touched, to make sure that these declarations actually work when used. Look through the `cpp_*.pyx` files in `tests/run/`, there should be some where you can add this. The are driven by Python code in doctests, but the test files themselves are compiled.

**Comment by Alexhuszagh** [comment]
Let me amend my git commit history to fix these issues and then add a separate commit with the tests. I'm missing a ctypedef, so this should be trivial.

**Comment by Alexhuszagh** [comment]
@scoder, I've updated the patch to include the tests you mentioned, and fix the bugs with the original patch. The new version now ensures `operator-()` and `operator+()` functionality for both vector and deque iterators.

**Comment by Alexhuszagh** [comment]
@scoder Any other issues with my PR? Sorry for the massive delay on my end.

**Comment by scoder** [comment]
Sorry, must have missed your message. Looks good to me, thanks!

**Pull request merged**
