### PR TITLE
Avoid error if type doesn't have __getstate__

### LINKED ISSUE #4738: [BUG] Looking up object.__getstate__ seems to have broken PyPy
**Describe the bug**
The CI on PyPy is reporting a lot of `xxx has not attribute __getstate__`.

**Environment (please complete the following information):**
 - Python version PyPy
 - Cython version 0.29.x and 3.0

**Additional context**
Almost certainly introduced in https://github.com/cython/cython/commit/ae4ade8daeae206db68583f2f4b9c1cbce9cba75. PyPy probably doesn't use CYTHON_USE_PYTYPE_LOOKUP so will go through a slightly different code path

### PR DESCRIPTION
**Pull request by da-woods**
Fixes bug introduced by https://github.com/cython/cython/commit/ae4ade8daeae206db68583f2f4b9c1cbce9cba75 for PyPy (hopefully)

Fixes #4738

### CODE REVIEW

**Comment by mattip** [comment]
Ahh, thanks. I was just getting ready to report this breakage.

**Comment by mattip** [comment]
The limited API sets CYTHON_USE_PYTYPE_LOOKUP=0. If it passes with the limited API then it is a PyPy bug, no?

**Comment by da-woods** [comment]
> The limited API sets CYTHON_USE_PYTYPE_LOOKUP=0. If it passes with the limited API then it is a PyPy bug, no?

Don't think so. PyPy is tested _much_ more thoroughly than the limited API. I don't believe anything in tests/run is currently run for the limited API (it's still a bit segfaulty...).

The fix makes sense to me - without the fix the CPython path looked up `tp.__getstate__` and just proceeded while the PyPy code raised an attribute error is `tp.__getstate__` didn't exist. (Whether PyPy defines `object.__getstate__` or not is PyPy's decision, but currently it only exists in CPython 3.11 alpha so Cython certainly isn't requiring it!)

**Comment by scoder** [comment]
Note that `__Pyx_PyObject_GetAttrStrNoError()` does not guarantee that there will be no exception raised. It only guarantees that an `AttributeError` returns `NULL` without an exception set. If other exceptions occur during the lookup, we still need to handle them in one way or another. That's somewhat implicitly hidden in the control flow of `__Pyx_setup_reduce()`.

**Pull request merged**
