### PR TITLE
Limit Python conversion on attribute access.

### PR DESCRIPTION
**Pull request by robertwb**
In particular, this limits errors caused by mutating implicit temporary
objects, e.g.

  cdef vector[int] v = ...
  v.pop()

See also github issue #1521.

### CODE REVIEW

**Comment by scoder** [comment]
Good intention, but there seem to be legitimate use cases for this as well that the change would break. I'm not entirely convinced that this should be done, especially without deprecation or preceding warning.

**Comment by robertwb** [comment]
This seems similar in spirit to our disallowing of conversion of likely temporaries to char*. 

Good point about a deprecation period. Do you have in mind legitimate use cases for this (that's common enough that an explicit cast to object would not be OK)? For stl containers, there are (for example) containment methods, but one would probably want to use the C++ variants rather than accidentally cause a Python conversion of the entire container.

**Comment by scoder** [comment]
An explicit cast to <object> would obviously fix the code by making it explicit, but it also means that we break existing user code, even if it's not as efficient as it could be. Our intuition seems to say that the current state does the wrong thing in most cases. The good thing about Python's containers is that mutation methods have no return values, which reduces the chance of false positives. Let's see what we change here.

- Methods and attributes of integers and floats are extremely rarely used and thus do not count. Plus, these objects are immutable and calling the methods always returns a result, so they are never useless or dangerous.
- Mutation methods of containers (clear(), append(), extend(), reverse(), sort(), ...) are always inefficient and often dangerous. Same for in-place operators like "+=" and "*=" (not sure if those even work currently).
- Sequence methods like index(), count() or find() are most likely too inefficient for reasonable use, as is copy() which would just copy a freshly created container.
- String mutation methods can be inefficient sometimes but their usage can also be perfectly ok. Strings are immutable and thus methods like encode(), lower(), format(), join() etc. always return a new and modified string anyway. The up-front conversion is often a reasonable price to pay for convenience.
- For sequences, there are more traps than attribute access, e.g. slicing, in-tests and generally all usages of Python operators, but also of builtins like len() or max(). It's difficult to distinguish between legitimate and purely inefficient conversions here. Concatenation of converted lists might be ok, for example, if the result is then kept in a Python list. Same for string operations and many set operations.
- Iteration over container method results such as dict.items() is usually optimised and, while more inefficient than direct C++ iteration, might be a legitimate convenience if the overhead is acceptable for the user. My guess is that this would be impacted by this change as well.

So, ISTM that the result is mixed. The majority of cases seem inefficient but there are legitimate use cases, even amongst the inefficient ones. Especially conversions to immutable Python types (definitely strings) seem quite reasonable in many cases.

What do you think about limiting the hard errors to lists and dicts as Python target types? We could still issue an inefficiency warning about others in some cases, but I wouldn't even do that generally.

**Comment by robertwb** [comment]
I think I'm going to go ahead and merge this, the hard errors are, as you also suggest, limited to (methods, not operators, of) container types.

**Comment by scoder** [comment]
Your call.

**Pull request merged**
