### PR TITLE
Use __Pyx_SET_SIZE() and __Pyx_SET_REFCNT()

### PR DESCRIPTION
**Pull request by vstinner**
Don't access directly PyObject.ob_refcnt and PyVarObject.ob_size.

### CODE REVIEW

**Comment by vstinner** [comment]
Change related to https://bugs.python.org/issue39573

See also:

* PR #3932
* https://github.com/pythoncapi/pythoncapi_compat
* https://www.python.org/dev/peps/pep-0620/

**Comment by vstinner** [comment]
See also https://github.com/cython/cython/issues/3934 "[ENH] Use pythoncapi_compat.h in Cython?" (not directly related).

**Comment by da-woods** [comment]
Does this want to get merged into master too? It looked like it most of the things it applied to were unchanged.

**Comment by robertwb** [comment]
Yes, we should do that.

**Comment by vstinner** [comment]
> Does this want to get merged into master too? It looked like it most of the things it applied to were unchanged.

Sure. I created PR #3937 for that. I recreated the PR from script using the upgrade_pythoncapi.py tool.

**Pull request merged**
