### PR TITLE
Improve C++11 containers

### PR DESCRIPTION
**Pull request by vallsv**
Hi,

As promised, here is some improvement for the C++11 containers.

Unfortunately it is not an exhaustive work, as the changes are subtle and it's much more work to check everything. But it can be already very useful.

For `insert` with begin/end iterators, i use an iterator class instead of an `InputIterator` (as it is defined in C++). I guess it avoid a lot of things, but it's better than before cause it allow at least to insert elements from an equivalent container. Let me know if there is better solutions.

I did unittests as the project allow to update and use it very easily. I really appreciate it.

### CODE REVIEW

**Comment by vallsv** [comment]
BTW, is iterators are real mapped object to C++ or just helper for cython?

For example, could we replace these without problem?
```
        cppclass iterator:
            pair[const T, U]& operator*()
            const_iterator operator++()
            const_iterator operator--()
            bint operator==(const_iterator)
            bint operator!=(const_iterator)
        cppclass const_iterator(iterator):
            pass
```
per
```
        cppclass const_iterator:
            pair[const T, U]& operator*()
            const_iterator operator++()
            const_iterator operator--()
            bint operator==(const_iterator)
            bint operator!=(const_iterator)
        cppclass iterator(const_iterator):
            pass
```
It looks to match better the sementic.

For example you could write:
```
cdef set[int].const_iterator a
cdef set[int].iterator b
a = b
#b = a # should be illegal
```

But i can be wrong.

**Comment by scoder** [comment]
The problem I see is this:
> pair[const T, U]& operator*()

Here, T is const for the `const_iterator`, but it shouldn't be for the `iterator`. This would need to be taken care of in the inheritance case.

**Comment by Alexhuszagh** [comment]
I like the idea of revamping all STL containers like this, since many functions take a `const_iterator` argument, but since Cython does not allow automatic conversion of an `iterator` to `const_iterator` yet, these functions signatures use `iterator` currently.

**Comment by scoder** [comment]
I think it's an improvement as it is. Thanks!

**Pull request merged**
