### PR TITLE
Default argument is mutable

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by sieben** [comment]
@scoder fixed

**Comment by scoder** [comment]
what is fixed? where?

**Comment by sieben** [comment]
I've removed the unwelcomed comparaison with None :

https://github.com/sieben/cython/commit/da14b724f04483a6496834d51fa31c6ecc638e21#commitcomment-14282497

2015-11-14 14:23 GMT+01:00 scoder <notifications@github.com>:

**Comment by scoder** [comment]
Thanks, but I reimplemented it to distinguish between None and empty containers.
https://github.com/cython/cython/commit/d6aa0e99e5ff37a114e9d3ebe4e096d6afefb543

**Pull request closed without merging**
