### PR TITLE
Fix #2749 - Cython 0.29 broke support for C++ enum classes.

### LINKED ISSUE #2749: Cython 0.29 broke support for C++ enum classes
Before https://github.com/cython/cython/commit/be4ca1d685e8d703f2285183147f8587da56fe6d (a fix for #2186), on this input:
```Cython
cpdef enum E "E":
    A
```
Cython was generating this:
```C
/* CIntToPy */
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__E(enum E value) {
    const enum E neg_one = (enum E) -1, const_zero = (enum E) 0;
```

Since https://github.com/cython/cython/commit/6079a5b0b0936feb2ec339a1f31d7d708ae6d3a3 it is generating this:
```C
/* CIntToPy */
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__E(enum E value) {
    const enum E neg_one = (enum E) ((enum E) 0 - (enum E) 1), const_zero = (enum E) 0;
```

This works for C enums, but fails to compile for C++ enum classes (https://godbolt.org/z/NY8PJT):
```C++
enum class E { X };
const enum E neg_one_class_28 = (enum E) -1;
const enum E neg_one_class_29 = (enum E) ((enum E) 0 - (enum E) 1);
```
```
<source>:3:54: error: invalid operands to binary expression ('enum E' and 'enum E')
const enum E neg_one_class_29 = (enum E) ((enum E) 0 - (enum E) 1);
                                          ~~~~~~~~~~ ^ ~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by cf-natali**
@orivej @da-woods

### CODE REVIEW

**Review by orivej — APPROVED** [review]
Thank you, LGTM!

**Comment by scoder** [comment]
Note that the `GCC_DIAGNOSTIC` macro is not necessarily defined, it was local to a specific utility code section which only gets added conditionally. I renamed it and made it available for other utility code now, see a2b2efca3ef268cb29bd9bb4335384acf5dd3b4f.

Could you please rebase (or merge) your branch on the latest master,  add the `//@requires: GCCDiagnostics` dependency, and adapt the macro name in your change?

**Comment by cf-natali** [comment]
@scoder Thanks, done.

**Comment by scoder** [comment]
Thanks!

**Comment by cf-natali** [comment]
I was wondering - should this - and the commit it depends on - be backported to the 0.29.x branch?
I'm not familiar with the workflow but it looks like the master branch corresponds to Cython 3 right?

**Comment by scoder** [comment]
Yes, I picked it over.

**Comment by cf-natali** [comment]
Great, thanks!

**Pull request merged**
